import {
  EQUIP_SLOTS,
  Tile,
  distance,
  pixelToTile,
  tileProps,
  type PlayerState,
  type StructureState,
} from '@survive/protocol';
import type { SimContext } from '../../core/context';
import { durabilityFraction } from '../../core/items';
import { structureCenter } from '../../core/structures';
import { structureAtTile } from '../../core/queries';
import {
  CROUCH_NEED_SCALE,
  FIRE_DEFAULT_RADIUS,
  FIRE_SEARCH_RADIUS,
  FIRE_WARMTH_SCALE,
  LIGHT_ONLY_HEAT,
  REST_STAMINA_FRACTION,
  SPRINT_NEED_SCALE,
  SPRINT_WARMTH,
  WALK_NEED_SCALE,
  WALK_WARMTH,
  WARMTH_SCALE,
  WET_DEEP,
  WET_SHALLOW,
} from './tuning';

/**
 * What the world is doing to the player.
 *
 * Everything in here is a read-only query over state the survival system needs but
 * does not own: how hard the player is working, what they are wearing, whether
 * there is a fire nearby, whether they are standing in the rain. Keeping them pure
 * and separate means the needs and temperature code reads as arithmetic over named
 * inputs rather than a pile of lookups.
 */

/**
 * Whether the player is putting effort in this tick.
 *
 * Prefers the authoritative input frame, because that is the one signal that
 * distinguishes standing still from walking - `moveMode` is `'walk'` for both. When
 * no frame is available (a starved network, or a test running survival on its own)
 * it falls back to `moveMode`, which still catches sprinting.
 */
export function isMoving(ctx: SimContext, player: PlayerState): boolean {
  const frame = ctx.inputs.get(player.id);
  if (frame) return Math.abs(frame.moveX) > 0.05 || Math.abs(frame.moveY) > 0.05;
  return player.moveMode === 'run';
}

/** Multiplier applied to every need rate for how hard the player is working. */
export function activityScale(ctx: SimContext, player: PlayerState): number {
  const moving = isMoving(ctx, player);
  if (!moving) return 1;
  switch (player.moveMode) {
    case 'run':
      return SPRINT_NEED_SCALE;
    case 'crouch':
      return CROUCH_NEED_SCALE;
    default:
      return WALK_NEED_SCALE;
  }
}

/** Effective ambient degrees generated by moving around. */
export function activityWarmth(ctx: SimContext, player: PlayerState): number {
  if (!isMoving(ctx, player)) return 0;
  return player.moveMode === 'run' ? SPRINT_WARMTH : WALK_WARMTH;
}

/**
 * Whether the player counts as resting: the precondition for regeneration.
 *
 * Sleeping always counts. Otherwise the player must not be moving, must not be
 * mid-swing, and must have their wind back - which is what stops "rest" from being
 * something you get for free while jogging across the map.
 */
export function isResting(ctx: SimContext, player: PlayerState, asleep: boolean): boolean {
  if (asleep) return true;
  if (isMoving(ctx, player)) return false;
  if (player.moveMode === 'run') return false;
  if (ctx.state.tick < player.attackReadyTick) return false;
  if (ctx.state.tick < player.actionLockedUntilTick) return false;
  return player.stamina >= player.maxStamina * REST_STAMINA_FRACTION;
}

/**
 * Total insulation from worn gear, in effective ambient degrees.
 *
 * Worn-out clothing insulates worse but never uselessly: a threadbare jacket is
 * still a jacket, so the condition term floors at half value.
 */
export function clothingWarmth(ctx: SimContext, player: PlayerState): number {
  let total = 0;
  for (const slot of EQUIP_SLOTS) {
    const stack = player.equipment[slot];
    if (!stack) continue;
    const def = ctx.data.items.get(stack.defId);
    const warmth = def?.armor?.warmth ?? 0;
    if (warmth <= 0) continue;
    total += warmth * (0.5 + 0.5 * durabilityFraction(stack, ctx.data));
  }
  return total * WARMTH_SCALE;
}

/** Heat output of a lit structure, falling back to its definition when unset. */
function structureHeat(ctx: SimContext, structure: StructureState): number {
  const def = ctx.data.structures.get(structure.defId);
  const lit = structure.station?.lit === true || structure.light?.on === true;
  if (!lit) return 0;
  const stationHeat = structure.station?.heat ?? 0;
  if (stationHeat > 0) return stationHeat;
  const definedHeat = def?.station?.heat ?? 0;
  if (definedHeat > 0) return definedHeat;
  // A wall torch is warm enough to matter if you huddle against it, barely.
  return structure.light || def?.light ? LIGHT_ONLY_HEAT : 0;
}

/**
 * Effective ambient degrees contributed by the warmest nearby fire.
 *
 * Fires do not add up - standing between two campfires is not twice as warm as
 * standing in one - so the strongest source wins. Falls off linearly to nothing at
 * the light radius, which is also roughly where the fire stops looking warm.
 */
export function nearbyFireWarmth(ctx: SimContext, player: PlayerState): number {
  let best = 0;
  const entries = ctx.spatial.queryKinds(player.x, player.y, FIRE_SEARCH_RADIUS, ['structure']);
  for (const entry of entries) {
    const structure = ctx.state.structures[entry.id];
    if (!structure || structure.progress < 1 || structure.health <= 0) continue;
    const heat = structureHeat(ctx, structure);
    if (heat <= 0) continue;
    const def = ctx.data.structures.get(structure.defId);
    const radius = structure.light?.radius ?? def?.light?.radius ?? FIRE_DEFAULT_RADIUS;
    const centre = def ? structureCenter(structure, def) : { x: entry.x, y: entry.y };
    const d = distance(player.x, player.y, centre.x, centre.y);
    if (d >= radius) continue;
    best = Math.max(best, heat * (1 - d / radius));
  }
  return best * FIRE_WARMTH_SCALE;
}

/** Interior floor tiles, which stand in for "has a roof over it". */
const SHELTER_TILES: readonly number[] = [Tile.FloorWood, Tile.FloorTile, Tile.FloorConcrete];

/**
 * Whether the player is out of the weather.
 *
 * There is no roof layer in the tile world, so shelter is inferred from standing on
 * an interior floor - generated or player-built. It is a proxy, but it is the same
 * proxy the renderer uses to decide you are indoors, so the two agree.
 */
export function isSheltered(ctx: SimContext, player: PlayerState): boolean {
  const tileX = pixelToTile(player.x);
  const tileY = pixelToTile(player.y);
  if (SHELTER_TILES.includes(ctx.world.getTile(tileX, tileY))) return true;
  const structure = structureAtTile(ctx.state, tileX, tileY);
  if (!structure) return false;
  const def = ctx.data.structures.get(structure.defId);
  return def?.category === 'floor' && structure.progress >= 1;
}

/**
 * How wet the player is being made right now, 0..1.
 *
 * Water underfoot soaks you regardless of shelter; precipitation only counts when
 * there is nothing overhead.
 */
export function wetnessSource(ctx: SimContext, player: PlayerState): number {
  const props = tileProps(ctx.world.getTileAt(player.x, player.y));
  if (props.water) return props.deep ? WET_DEEP : WET_SHALLOW;
  const weather = ctx.state.weather;
  const precipitating =
    weather.type === 'rain' || weather.type === 'storm' || weather.type === 'snow';
  if (!precipitating) return 0;
  if (isSheltered(ctx, player)) return 0;
  // Snow settles rather than soaks, so it wets you more slowly than rain.
  const severity = Math.max(0.25, weather.intensity);
  return weather.type === 'snow' ? severity * 0.5 : severity;
}
