import { Biome } from '@survive/protocol';
import type { AnimalDef } from '../types';
import { seconds } from './units';

/**
 * The animal table.
 *
 * Wildlife is the only renewable food source that does not need a farm, so the spread
 * of `behavior` is the difficulty dial on eating:
 *
 * - `skittish` (rabbit, deer, fox, chicken) bolt at `fleeRange` and outrun a sprinting
 *   player, so they are a bow-and-patience problem, not a melee one.
 * - `passive` (cow) stands there. Farmland is worth walking to.
 * - `territorial` (boar) only charges if you crowd it - `fleeRange` is short, so it
 *   holds ground long enough to be a mistake.
 * - `aggressive` (wolf, bear) come to you. A bear at 260 HP and 38 damage a swing will
 *   end an early run outright.
 *
 * `skill` is `foraging` across the board: the weapon already grants melee or ranged XP
 * on the hit, so this field is the hunting-and-butchery half of the reward.
 */
export const ANIMAL_DEFS: readonly AnimalDef[] = [
  {
    id: 'rabbit',
    name: 'Rabbit',
    maxHealth: 18,
    speedWalk: 55,
    speedRun: 210,
    radius: 7,
    behavior: 'skittish',
    sightRange: 260,
    fleeRange: 220,
    damage: 0,
    damageType: 'blunt',
    attackRange: 0,
    attackTicks: seconds(1),
    lootTableId: 'animal_rabbit',
    xp: 8,
    skill: 'foraging',
    spawnWeight: 100,
    spawnBiomes: {
      [Biome.Grassland]: 1.5,
      [Biome.Forest]: 1.2,
      [Biome.Farmland]: 1.3,
      [Biome.DeepForest]: 0.7,
    },
    nocturnal: false,
    densityPerChunk: 3,
    sprite: 'animal_rabbit',
  },
  {
    id: 'chicken',
    name: 'Chicken',
    maxHealth: 12,
    speedWalk: 40,
    speedRun: 110,
    radius: 6,
    behavior: 'skittish',
    sightRange: 180,
    fleeRange: 150,
    damage: 0,
    damageType: 'blunt',
    attackRange: 0,
    attackTicks: seconds(1),
    lootTableId: 'animal_chicken',
    xp: 5,
    skill: 'foraging',
    spawnWeight: 70,
    spawnBiomes: { [Biome.Farmland]: 1.8, [Biome.Town]: 0.6, [Biome.Grassland]: 0.4 },
    nocturnal: false,
    densityPerChunk: 2.2,
    sprite: 'animal_chicken',
  },
  {
    id: 'fox',
    name: 'Fox',
    maxHealth: 35,
    speedWalk: 70,
    speedRun: 215,
    radius: 9,
    behavior: 'skittish',
    sightRange: 320,
    fleeRange: 260,
    damage: 8,
    damageType: 'slash',
    attackRange: 26,
    attackTicks: seconds(0.9),
    lootTableId: 'animal_fox',
    xp: 18,
    skill: 'foraging',
    spawnWeight: 40,
    spawnBiomes: { [Biome.Forest]: 1.1, [Biome.DeepForest]: 0.9, [Biome.Grassland]: 0.6 },
    nocturnal: true,
    densityPerChunk: 0.9,
    sprite: 'animal_fox',
  },
  {
    id: 'deer',
    name: 'Deer',
    maxHealth: 70,
    speedWalk: 70,
    speedRun: 265,
    radius: 14,
    behavior: 'skittish',
    sightRange: 380,
    fleeRange: 340,
    damage: 6,
    damageType: 'blunt',
    attackRange: 32,
    attackTicks: seconds(1.3),
    lootTableId: 'animal_deer',
    xp: 32,
    skill: 'foraging',
    spawnWeight: 55,
    spawnBiomes: { [Biome.Forest]: 1.4, [Biome.DeepForest]: 1.6, [Biome.Grassland]: 0.6 },
    nocturnal: false,
    densityPerChunk: 1.3,
    sprite: 'animal_deer',
  },
  {
    id: 'cow',
    name: 'Cow',
    maxHealth: 150,
    speedWalk: 35,
    speedRun: 95,
    radius: 18,
    behavior: 'passive',
    sightRange: 220,
    fleeRange: 170,
    damage: 8,
    damageType: 'blunt',
    attackRange: 36,
    attackTicks: seconds(1.8),
    lootTableId: 'animal_cow',
    xp: 42,
    skill: 'foraging',
    spawnWeight: 30,
    spawnBiomes: { [Biome.Farmland]: 1.6, [Biome.Grassland]: 0.5 },
    nocturnal: false,
    densityPerChunk: 0.8,
    sprite: 'animal_cow',
  },
  {
    id: 'boar',
    name: 'Boar',
    maxHealth: 110,
    speedWalk: 55,
    speedRun: 175,
    radius: 15,
    behavior: 'territorial',
    sightRange: 300,
    fleeRange: 110,
    damage: 19,
    damageType: 'pierce',
    attackRange: 34,
    attackTicks: seconds(1.1),
    lootTableId: 'animal_boar',
    xp: 48,
    skill: 'foraging',
    spawnWeight: 35,
    spawnBiomes: { [Biome.Forest]: 1.2, [Biome.DeepForest]: 1.4, [Biome.Swamp]: 1 },
    nocturnal: false,
    densityPerChunk: 0.9,
    sprite: 'animal_boar',
  },
  {
    id: 'wolf',
    name: 'Wolf',
    maxHealth: 85,
    speedWalk: 80,
    speedRun: 235,
    radius: 12,
    behavior: 'aggressive',
    sightRange: 420,
    fleeRange: 60,
    damage: 16,
    damageType: 'slash',
    attackRange: 30,
    attackTicks: seconds(0.9),
    lootTableId: 'animal_wolf',
    xp: 55,
    skill: 'foraging',
    spawnWeight: 22,
    spawnBiomes: { [Biome.DeepForest]: 1.5, [Biome.Forest]: 0.8, [Biome.Rocky]: 0.7 },
    nocturnal: true,
    densityPerChunk: 0.7,
    sprite: 'animal_wolf',
  },
  {
    id: 'bear',
    name: 'Bear',
    maxHealth: 260,
    speedWalk: 65,
    speedRun: 200,
    radius: 20,
    behavior: 'aggressive',
    sightRange: 360,
    fleeRange: 0,
    damage: 38,
    damageType: 'slash',
    attackRange: 44,
    attackTicks: seconds(1.5),
    lootTableId: 'animal_bear',
    xp: 145,
    skill: 'foraging',
    spawnWeight: 8,
    spawnBiomes: { [Biome.DeepForest]: 1.2, [Biome.Rocky]: 0.6 },
    nocturnal: false,
    densityPerChunk: 0.25,
    sprite: 'animal_bear',
  },
];
