import type { CropSource } from '../types';
import { days } from './units';

/**
 * The crop table.
 *
 * Timings are in in-game days (one day = 28 800 ticks = 24 real minutes at the shipped
 * clock), and every crop lands between three and eight days from seed to harvest. The
 * fast crops - carrots, onions, herbs - are the ones worth planting to survive the
 * week; wheat and pumpkins are what you plant because you intend to still be here.
 *
 * `ticksPerStage` always has exactly `stages - 1` entries: it lists the *transitions*
 * between visible stages, not the stages themselves. `validateGameData` enforces that,
 * because an off-by-one here silently freezes a crop at its last stage forever.
 *
 * Moisture and fertility are 0..100 point scales shared with `StructureDef.plot`. A
 * plain `farm_plot` starts at 40 moisture, so most crops need watering at least once
 * before harvest; a `planter_box` starts at 70 and holds more.
 *
 * `blightChance` is per tick, so the numbers look absurdly small on purpose: 2e-6 over
 * a five-day crop is roughly a one-in-four risk across its whole life.
 */
export const CROP_DEFS: readonly CropSource[] = [
  {
    id: 'wheat',
    seedDefId: 'seed_wheat',
    produceDefId: 'wheat',
    stages: 5,
    ticksPerStage: [days(1), days(1.25), days(1.25), days(1.5)],
    waterPerTick: 0.00035,
    minMoisture: 12,
    idealTemperature: [10, 28],
    frostTemperature: -4,
    seasons: ['spring', 'summer', 'autumn'],
    yieldMin: 3,
    yieldMax: 5,
    seedYield: [1, 3],
    regrows: false,
    harvestsPerPlant: 1,
    fertilityCost: 10,
    blightChance: 1.4e-6,
    xpPerHarvest: 10,
    sprite: 'crop_wheat',
  },
  {
    id: 'corn',
    seedDefId: 'seed_corn',
    produceDefId: 'corn',
    stages: 6,
    ticksPerStage: [days(1), days(1.25), days(1.25), days(1.5), days(2)],
    waterPerTick: 0.0006,
    minMoisture: 20,
    idealTemperature: [16, 32],
    frostTemperature: 1,
    seasons: ['summer'],
    yieldMin: 2,
    yieldMax: 4,
    seedYield: [1, 2],
    regrows: false,
    harvestsPerPlant: 1,
    fertilityCost: 22,
    blightChance: 1.8e-6,
    xpPerHarvest: 18,
    sprite: 'crop_corn',
  },
  {
    id: 'potato',
    seedDefId: 'seed_potato',
    produceDefId: 'potato',
    stages: 4,
    ticksPerStage: [days(1.25), days(1.25), days(1.5)],
    waterPerTick: 0.0004,
    minMoisture: 14,
    idealTemperature: [8, 26],
    frostTemperature: -3,
    seasons: ['spring', 'summer', 'autumn'],
    yieldMin: 3,
    yieldMax: 6,
    seedYield: [1, 2],
    regrows: false,
    harvestsPerPlant: 1,
    fertilityCost: 14,
    blightChance: 2.4e-6,
    xpPerHarvest: 10,
    sprite: 'crop_potato',
  },
  {
    id: 'carrot',
    seedDefId: 'seed_carrot',
    produceDefId: 'carrot',
    stages: 4,
    ticksPerStage: [days(1), days(1), days(1)],
    waterPerTick: 0.00045,
    minMoisture: 16,
    idealTemperature: [7, 24],
    frostTemperature: -5,
    seasons: ['spring', 'summer', 'autumn'],
    yieldMin: 2,
    yieldMax: 4,
    seedYield: [1, 2],
    regrows: false,
    harvestsPerPlant: 1,
    fertilityCost: 8,
    blightChance: 1.2e-6,
    xpPerHarvest: 8,
    sprite: 'crop_carrot',
  },
  {
    id: 'tomato',
    seedDefId: 'seed_tomato',
    produceDefId: 'tomato',
    stages: 5,
    ticksPerStage: [days(1.25), days(1.25), days(1.5), days(1.5)],
    waterPerTick: 0.0007,
    minMoisture: 24,
    idealTemperature: [16, 32],
    frostTemperature: 2,
    seasons: ['summer'],
    yieldMin: 2,
    yieldMax: 4,
    // Indeterminate: it keeps fruiting until the frost or the blight gets it.
    seedYield: [0, 2],
    regrows: true,
    harvestsPerPlant: 4,
    fertilityCost: 9,
    blightChance: 3.2e-6,
    xpPerHarvest: 12,
    sprite: 'crop_tomato',
  },
  {
    id: 'cabbage',
    seedDefId: 'seed_cabbage',
    produceDefId: 'cabbage',
    stages: 4,
    ticksPerStage: [days(1.5), days(1.5), days(1.5)],
    waterPerTick: 0.0005,
    minMoisture: 18,
    idealTemperature: [4, 22],
    // The one crop that shrugs off a hard frost, which makes it the winter answer.
    // Below the mid-winter night floor, with a margin: cabbage is the crop that lists
    // winter, so it has to live through one. See the seasonal-survival test in
    // `farming.test.ts` for the floor this is measured against.
    frostTemperature: -10,
    seasons: ['spring', 'autumn', 'winter'],
    yieldMin: 1,
    yieldMax: 2,
    seedYield: [1, 2],
    regrows: false,
    harvestsPerPlant: 1,
    fertilityCost: 16,
    blightChance: 1.6e-6,
    xpPerHarvest: 12,
    sprite: 'crop_cabbage',
  },
  {
    id: 'pumpkin',
    seedDefId: 'seed_pumpkin',
    produceDefId: 'pumpkin',
    stages: 6,
    ticksPerStage: [days(1.5), days(1.5), days(1.5), days(1.5), days(1.5)],
    waterPerTick: 0.00075,
    minMoisture: 22,
    idealTemperature: [14, 30],
    // Frost-tender by design, but it lists autumn and mid-autumn nights reach -1.6C,
    // so a pumpkin that died at 0C could never be grown for the season it belongs to.
    frostTemperature: -3,
    seasons: ['summer', 'autumn'],
    yieldMin: 1,
    yieldMax: 2,
    seedYield: [2, 4],
    regrows: false,
    harvestsPerPlant: 1,
    fertilityCost: 26,
    blightChance: 1.5e-6,
    xpPerHarvest: 22,
    sprite: 'crop_pumpkin',
  },
  {
    id: 'onion',
    seedDefId: 'seed_onion',
    produceDefId: 'onion',
    stages: 4,
    ticksPerStage: [days(1.25), days(1.25), days(1.25)],
    waterPerTick: 0.0004,
    minMoisture: 14,
    idealTemperature: [8, 26],
    frostTemperature: -4,
    seasons: ['spring', 'summer'],
    yieldMin: 2,
    yieldMax: 4,
    seedYield: [1, 2],
    regrows: false,
    harvestsPerPlant: 1,
    fertilityCost: 9,
    blightChance: 1.2e-6,
    xpPerHarvest: 9,
    sprite: 'crop_onion',
  },
  {
    id: 'beans',
    seedDefId: 'seed_beans',
    produceDefId: 'beans',
    stages: 5,
    ticksPerStage: [days(1), days(1.25), days(1.25), days(1.5)],
    waterPerTick: 0.00055,
    minMoisture: 18,
    idealTemperature: [12, 30],
    frostTemperature: 0,
    seasons: ['spring', 'summer'],
    yieldMin: 2,
    yieldMax: 4,
    seedYield: [1, 3],
    regrows: true,
    harvestsPerPlant: 3,
    // Legumes give fertility back rather than taking it, so the cost is deliberately
    // token: rotating beans through a plot is the cheap way to keep it alive.
    fertilityCost: 3,
    blightChance: 1.8e-6,
    xpPerHarvest: 12,
    sprite: 'crop_beans',
  },
  {
    id: 'herb',
    seedDefId: 'seed_herb',
    produceDefId: 'herb',
    stages: 3,
    ticksPerStage: [days(1.5), days(1.5)],
    waterPerTick: 0.0003,
    minMoisture: 10,
    idealTemperature: [6, 30],
    frostTemperature: -6,
    seasons: ['spring', 'summer', 'autumn'],
    yieldMin: 2,
    yieldMax: 4,
    seedYield: [1, 2],
    regrows: true,
    harvestsPerPlant: 5,
    fertilityCost: 5,
    blightChance: 1e-6,
    xpPerHarvest: 8,
    sprite: 'crop_herb',
  },
];
