import type {
  ArmorProps,
  DrinkProps,
  FoodProps,
  ItemDef,
  MedicalProps,
  PerishableProps,
  WeaponProps,
} from '../types';
import { days, gameHours, seconds } from './units';

/**
 * The item table.
 *
 * Conventions used throughout, so the numbers stay comparable:
 *
 * - **Weight is kilograms.** A fresh character carries 30 kg before the
 *   `overencumbered` effect bites, so a stack of twenty logs (2 kg each) is already
 *   more than one trip. Hauling is meant to be a decision.
 * - **Durability is "uses"**, spent through `tool.durabilityPerUse` /
 *   `weapon.durabilityPerHit`. A stone hatchet at 60 lasts an afternoon; a steel one
 *   at 400 lasts a season.
 * - **`loudness` is a radius in world pixels** (one tile = 32 px, one chunk =
 *   1024 px). Melee is a room; a rifle is six chunks. That single number is the whole
 *   reason firing a gun is a strategic act rather than a free win.
 * - **Nutrition and hydration are need points**, on the same 0..100 scale as
 *   `hunger` / `thirst`. A cooked steak at 30 is roughly a third of a day's food.
 * - **`fuel.burnTicks` is the currency of every burning station.** A station's
 *   `maxFuel` and a recipe's `fuelCost` are in the same ticks, so one log (2400) pays
 *   for four smelts (600 each).
 *
 * Anything with per-item state (durability, a liquid fill, loaded ammunition) is
 * declared `stackSize: 1`, matching `maxStackSize()` in the simulation, so the table
 * and the runtime agree instead of quietly disagreeing.
 */

// ---------------------------------------------------------------------------
// Builders
// ---------------------------------------------------------------------------

type ItemSpec = Pick<ItemDef, 'id' | 'name' | 'description' | 'category'> &
  Omit<Partial<ItemDef>, 'id' | 'name' | 'description' | 'category'>;

function item(spec: ItemSpec): ItemDef {
  return {
    stackSize: 20,
    weight: 0.5,
    icon: `item_${spec.id}`,
    rarity: 'common',
    tags: [],
    ...spec,
  };
}

type MeleeSpec = Pick<WeaponProps, 'damage' | 'damageType' | 'range'> & Partial<WeaponProps>;

/** Melee defaults: a one-handed swing, ~0.8 s between hits, audible across a room. */
function melee(spec: MeleeSpec): WeaponProps {
  return {
    kind: 'melee',
    arcDegrees: 70,
    attackTicks: seconds(0.8),
    windupTicks: seconds(0.2),
    staminaCost: 6,
    knockback: 60,
    critChance: 0.05,
    critMultiplier: 1.8,
    armorPen: 0,
    skill: 'melee',
    durabilityPerHit: 1,
    loudness: 140,
    twoHanded: false,
    maxTargets: 1,
    ...spec,
  };
}

type RangedSpec = Pick<WeaponProps, 'damage' | 'damageType' | 'range' | 'ammoDefIds'> &
  Partial<WeaponProps>;

/** Ranged defaults lean firearm-ish; bows override the quiet, slow half. */
function ranged(spec: RangedSpec): WeaponProps {
  return {
    kind: 'ranged',
    arcDegrees: 0,
    attackTicks: seconds(0.7),
    windupTicks: seconds(0.1),
    staminaCost: 1,
    knockback: 40,
    critChance: 0.08,
    critMultiplier: 2.2,
    armorPen: 0.15,
    skill: 'ranged',
    durabilityPerHit: 1,
    loudness: 4000,
    twoHanded: true,
    maxTargets: 1,
    magazineSize: 1,
    reloadTicks: seconds(2),
    spreadDegrees: 3,
    pellets: 1,
    ...spec,
  };
}

type ThrownSpec = Pick<WeaponProps, 'damage' | 'damageType' | 'range' | 'projectileDefId'> &
  Partial<WeaponProps>;

function thrown(spec: ThrownSpec): WeaponProps {
  return {
    kind: 'thrown',
    arcDegrees: 0,
    attackTicks: seconds(1.2),
    windupTicks: seconds(0.35),
    staminaCost: 5,
    knockback: 40,
    critChance: 0.05,
    critMultiplier: 1.6,
    armorPen: 0,
    skill: 'ranged',
    durabilityPerHit: 0,
    loudness: 260,
    twoHanded: false,
    maxTargets: 1,
    ...spec,
  };
}

type ArmorSpec = Pick<ArmorProps, 'slot' | 'coverage' | 'protection'> & Partial<ArmorProps>;

function armor(spec: ArmorSpec): ArmorProps {
  return {
    warmth: 0,
    encumbrance: 0,
    durabilityPerHit: 1,
    biteResistance: 1,
    ...spec,
  };
}

type FoodSpec = Pick<FoodProps, 'nutrition'> & Partial<FoodProps>;

function food(spec: FoodSpec): FoodProps {
  return {
    hydration: 0,
    stamina: 0,
    health: 0,
    eatTicks: seconds(1.5),
    sicknessChance: 0,
    ...spec,
  };
}

type DrinkSpec = Pick<DrinkProps, 'hydration'> & Partial<DrinkProps>;

function drink(spec: DrinkSpec): DrinkProps {
  return {
    nutrition: 0,
    sicknessChance: 0,
    drinkTicks: seconds(1.2),
    ...spec,
  };
}

type MedicalSpec = Pick<MedicalProps, 'kind'> & Partial<MedicalProps>;

function medical(spec: MedicalSpec): MedicalProps {
  return {
    bleedStop: 0,
    heal: 0,
    painRelief: 0,
    infectionCure: 0,
    fixesFracture: false,
    cleanliness: 0.5,
    useTicks: seconds(2),
    skillLevel: 0,
    ...spec,
  };
}

/** Perishable shorthand. Cool storage roughly triples shelf life. */
function spoils(dayCount: number, spoiledDefId?: string): PerishableProps {
  return spoiledDefId
    ? { spoilTicks: days(dayCount), spoiledDefId, refrigeratedMultiplier: 0.35 }
    : { spoilTicks: days(dayCount), refrigeratedMultiplier: 0.35 };
}

// ---------------------------------------------------------------------------
// Raw resources and components
// ---------------------------------------------------------------------------

const RESOURCES: ItemDef[] = [
  item({
    id: 'wood_log',
    name: 'Wood Log',
    description: 'A rough length of trunk. Everything wooden starts here.',
    category: 'resource',
    weight: 2,
    stackSize: 20,
    fuel: { burnTicks: 2400, heat: 12 },
    tags: ['wood', 'fuel', 'gatherable'],
  }),
  item({
    id: 'wood_plank',
    name: 'Wood Plank',
    description: 'Sawn flat and square. Structural, and far less wasteful than logs.',
    category: 'component',
    weight: 1,
    fuel: { burnTicks: 1400, heat: 10 },
    tags: ['wood', 'fuel'],
  }),
  item({
    id: 'stick',
    name: 'Stick',
    description: 'A trimmed branch. Handles, shafts, kindling.',
    category: 'resource',
    weight: 0.25,
    stackSize: 40,
    fuel: { burnTicks: 400, heat: 5 },
    tags: ['wood', 'fuel', 'gatherable'],
  }),
  item({
    id: 'bark',
    name: 'Bark',
    description: 'Strips of bark. Tannin for curing hides, tinder for a fire.',
    category: 'resource',
    weight: 0.15,
    stackSize: 40,
    fuel: { burnTicks: 260, heat: 4 },
    tags: ['wood', 'fuel', 'gatherable'],
  }),
  item({
    id: 'plant_fiber',
    name: 'Plant Fiber',
    description:
      'Tough stringy stems. The first thing anyone gathers, and the last thing they run out of.',
    category: 'resource',
    weight: 0.05,
    stackSize: 60,
    tags: ['fiber', 'gatherable'],
  }),
  item({
    id: 'stone',
    name: 'Stone',
    description: 'A hand-sized rock. Sharp enough to cut with, heavy enough to build with.',
    category: 'resource',
    weight: 1.2,
    stackSize: 30,
    tags: ['stone', 'gatherable'],
  }),
  item({
    id: 'flint',
    name: 'Flint',
    description: 'Knaps to a shaving edge and throws a spark. Two problems, one stone.',
    category: 'resource',
    weight: 0.3,
    stackSize: 30,
    tags: ['stone', 'gatherable'],
  }),
  item({
    id: 'stone_block',
    name: 'Stone Block',
    description: 'Dressed masonry. Heavy, slow to make, and it does not burn.',
    category: 'component',
    weight: 4.5,
    stackSize: 10,
    tags: ['stone'],
  }),
  item({
    id: 'sand',
    name: 'Sand',
    description: 'Silica. Useless until it is molten.',
    category: 'resource',
    weight: 1.4,
    stackSize: 30,
    tags: ['gatherable'],
  }),
  item({
    id: 'clay',
    name: 'Clay',
    description: 'Wet grey clay dug out of a riverbank. Mortar now, brick after firing.',
    category: 'resource',
    weight: 1.3,
    stackSize: 30,
    tags: ['gatherable'],
  }),
  item({
    id: 'clay_brick',
    name: 'Clay Brick',
    description: 'Kiln-fired and hard. Lines a burner without cracking.',
    category: 'component',
    weight: 2,
    stackSize: 20,
    tags: ['stone'],
  }),
  item({
    id: 'coal',
    name: 'Coal',
    description: 'Dense black rock that burns hotter and longer than anything you can grow.',
    category: 'fuel',
    weight: 1,
    stackSize: 30,
    fuel: { burnTicks: 6000, heat: 26 },
    tags: ['fuel', 'gatherable'],
  }),
  item({
    id: 'charcoal',
    name: 'Charcoal',
    description: 'Wood cooked without air. Smelting fuel, and the black half of gunpowder.',
    category: 'fuel',
    weight: 0.6,
    stackSize: 30,
    fuel: { burnTicks: 4000, heat: 22 },
    tags: ['fuel'],
  }),
  item({
    id: 'iron_ore',
    name: 'Iron Ore',
    description: 'Rust-red rock. Worthless without a furnace, priceless with one.',
    category: 'resource',
    weight: 2,
    stackSize: 20,
    tags: ['ore'],
  }),
  item({
    id: 'iron_ingot',
    name: 'Iron Ingot',
    description: 'Smelted iron. The line between scraping by and building something.',
    category: 'component',
    weight: 1.8,
    stackSize: 20,
    tags: ['metal'],
  }),
  item({
    id: 'copper_ore',
    name: 'Copper Ore',
    description: 'Green-streaked rock. Soft metal, but it draws into wire and cases a round.',
    category: 'resource',
    weight: 2,
    stackSize: 20,
    tags: ['ore'],
  }),
  item({
    id: 'copper_ingot',
    name: 'Copper Ingot',
    description: 'Soft, conductive, easy to work. Wire and cartridge brass.',
    category: 'component',
    weight: 1.7,
    stackSize: 20,
    tags: ['metal'],
  }),
  item({
    id: 'steel_ingot',
    name: 'Steel Ingot',
    description: 'Iron married to carbon in a hot fire. Holds an edge through a whole horde.',
    category: 'component',
    weight: 1.9,
    stackSize: 20,
    rarity: 'uncommon',
    tags: ['metal'],
  }),
  item({
    id: 'scrap_metal',
    name: 'Scrap Metal',
    description: 'Twisted offcuts of the old world. Re-smelt it, or nail it to something.',
    category: 'resource',
    weight: 1,
    stackSize: 30,
    tags: ['metal', 'gatherable'],
  }),
  item({
    id: 'nail',
    name: 'Nail',
    description: 'Small, dull, and the reason your roof stays on.',
    category: 'component',
    weight: 0.02,
    stackSize: 200,
    tags: ['metal'],
  }),
  item({
    id: 'rope',
    name: 'Rope',
    description: 'Twisted fibre cordage. Lashings, bowstrings, snares.',
    category: 'component',
    weight: 0.4,
    stackSize: 20,
    tags: ['fiber'],
  }),
  item({
    id: 'cloth_rag',
    name: 'Cloth Rag',
    description: 'A torn scrap of fabric. Dirty, but it soaks up blood.',
    category: 'component',
    weight: 0.15,
    stackSize: 40,
    fuel: { burnTicks: 300, heat: 4 },
    tags: ['cloth', 'fuel'],
  }),
  item({
    id: 'cloth',
    name: 'Cloth',
    description: 'A woven square. Clothing, bandages, packs.',
    category: 'component',
    weight: 0.3,
    stackSize: 30,
    tags: ['cloth'],
  }),
  item({
    id: 'leather',
    name: 'Leather',
    description: 'Cured hide. Turns a bite into a bruise more often than it does not.',
    category: 'component',
    weight: 0.5,
    stackSize: 20,
    tags: ['leather'],
  }),
  item({
    id: 'hide',
    name: 'Animal Hide',
    description: 'Raw, greasy and starting to smell. Tan it before it turns.',
    category: 'resource',
    weight: 1.2,
    stackSize: 10,
    tags: ['leather'],
  }),
  item({
    id: 'bone',
    name: 'Bone',
    description: 'Sturdy and sharp when split. Burned to ash it makes fertiliser and powder.',
    category: 'resource',
    weight: 0.4,
    stackSize: 20,
    tags: ['bone'],
  }),
  item({
    id: 'sinew',
    name: 'Sinew',
    description: 'Dried tendon. Stronger than any cord you can twist from grass.',
    category: 'resource',
    weight: 0.05,
    stackSize: 30,
    tags: ['fiber'],
  }),
  item({
    id: 'feather',
    name: 'Feather',
    description: 'Fletching. Without it an arrow is just a stick going roughly forward.',
    category: 'resource',
    weight: 0.02,
    stackSize: 60,
    tags: [],
  }),
  item({
    id: 'resin',
    name: 'Pine Resin',
    description: 'Sticky sap. Glue, waterproofing, and it makes a torch burn honestly.',
    category: 'resource',
    weight: 0.2,
    stackSize: 30,
    fuel: { burnTicks: 900, heat: 14 },
    tags: ['fuel'],
  }),
  item({
    id: 'gunpowder',
    name: 'Gunpowder',
    description: 'Charcoal, saltpetre and bone ash, milled fine. Handle it dry and gently.',
    category: 'component',
    weight: 0.1,
    stackSize: 40,
    rarity: 'uncommon',
    tags: ['explosive'],
  }),
  item({
    id: 'glass_shard',
    name: 'Glass Shard',
    description: 'A broken edge. Cuts whatever holds it about as often as what it is aimed at.',
    category: 'resource',
    weight: 0.1,
    stackSize: 40,
    tags: ['glass', 'gatherable'],
  }),
  item({
    id: 'glass',
    name: 'Glass Pane',
    description: 'Cast flat and cooled slowly. Windows, lanterns, bottles.',
    category: 'component',
    weight: 0.8,
    stackSize: 20,
    tags: ['glass'],
  }),
  item({
    id: 'wire',
    name: 'Wire',
    description: 'Drawn copper. Snares, traps, and anything that needs to conduct.',
    category: 'component',
    weight: 0.1,
    stackSize: 40,
    tags: ['metal'],
  }),
  item({
    id: 'duct_tape',
    name: 'Duct Tape',
    description: 'Half a roll left. Fixes everything, once.',
    category: 'component',
    weight: 0.2,
    stackSize: 10,
    rarity: 'uncommon',
    tags: [],
  }),
  item({
    id: 'plastic',
    name: 'Plastic Scrap',
    description: 'Cracked panels and bottle bodies. Light, waterproof, everywhere.',
    category: 'resource',
    weight: 0.3,
    stackSize: 30,
    tags: ['gatherable'],
  }),
  item({
    id: 'rubber',
    name: 'Rubber',
    description: 'Cut from a tyre wall. Seals, straps, sling bands.',
    category: 'resource',
    weight: 0.4,
    stackSize: 20,
    tags: ['gatherable'],
  }),
  item({
    id: 'battery',
    name: 'Battery',
    description: 'Most of a charge left. Radios and torches only.',
    category: 'component',
    weight: 0.3,
    stackSize: 10,
    rarity: 'uncommon',
    tags: [],
  }),
  item({
    id: 'fuel_canister',
    name: 'Fuel Canister',
    description:
      'Jerrycan of petrol, going stale but still furious. Burns hotter than anything else you own.',
    category: 'fuel',
    weight: 5,
    stackSize: 4,
    rarity: 'uncommon',
    fuel: { burnTicks: 12000, heat: 40 },
    tags: ['fuel', 'flammable'],
  }),
  item({
    id: 'ammo_casing',
    name: 'Cartridge Casing',
    description: 'Drawn brass, ready to be primed, charged and crimped.',
    category: 'component',
    weight: 0.02,
    stackSize: 100,
    tags: ['metal'],
  }),
  item({
    id: 'fertilizer',
    name: 'Fertilizer',
    description: 'Bone meal and rotted greens. Buys back the fertility a harvest takes.',
    category: 'misc',
    weight: 0.6,
    stackSize: 20,
    fertilizerTicks: days(0.5),
    tags: ['farming'],
  }),
  item({
    id: 'compost',
    name: 'Compost',
    description: 'A season of kitchen scraps, gone black and sweet-smelling.',
    category: 'misc',
    weight: 0.8,
    stackSize: 20,
    fertilizerTicks: days(0.2),
    tags: ['farming'],
  }),
];

// ---------------------------------------------------------------------------
// Tools
// ---------------------------------------------------------------------------

const TOOLS: ItemDef[] = [
  item({
    id: 'stone_hatchet',
    name: 'Stone Hatchet',
    description: 'A flake of stone lashed to a branch. It will fell a tree and it will fall apart.',
    category: 'tool',
    stackSize: 1,
    weight: 1.4,
    maxDurability: 60,
    tool: { kinds: ['axe'], tier: 1, efficiency: 1, durabilityPerUse: 1 },
    weapon: melee({
      damage: 9,
      damageType: 'slash',
      range: 44,
      durabilityPerHit: 2,
      staminaCost: 7,
    }),
    tags: ['tier1'],
  }),
  item({
    id: 'iron_axe',
    name: 'Iron Axe',
    description: 'A proper felling axe. Trees stop being an afternoon and become a minute.',
    category: 'tool',
    stackSize: 1,
    weight: 2.4,
    maxDurability: 220,
    tool: { kinds: ['axe'], tier: 2, efficiency: 1.8, durabilityPerUse: 1 },
    weapon: melee({
      damage: 18,
      damageType: 'slash',
      range: 48,
      attackTicks: seconds(1),
      staminaCost: 9,
      knockback: 90,
      durabilityPerHit: 2,
    }),
    tags: [],
  }),
  item({
    id: 'steel_axe',
    name: 'Steel Axe',
    description: 'Forged, tempered, and balanced. Bites deeper than iron and shrugs it off.',
    category: 'tool',
    stackSize: 1,
    weight: 2.5,
    maxDurability: 420,
    rarity: 'uncommon',
    tool: { kinds: ['axe'], tier: 3, efficiency: 2.5, durabilityPerUse: 1 },
    weapon: melee({
      damage: 24,
      damageType: 'slash',
      range: 48,
      attackTicks: seconds(0.95),
      staminaCost: 9,
      knockback: 95,
      armorPen: 0.1,
      durabilityPerHit: 2,
    }),
    tags: [],
  }),
  item({
    id: 'stone_pickaxe',
    name: 'Stone Pickaxe',
    description: 'Blunt and brittle. Enough for loose rock and coal, hopeless on ore.',
    category: 'tool',
    stackSize: 1,
    weight: 1.8,
    maxDurability: 60,
    tool: { kinds: ['pickaxe'], tier: 1, efficiency: 1, durabilityPerUse: 1 },
    weapon: melee({
      damage: 10,
      damageType: 'pierce',
      range: 46,
      staminaCost: 8,
      durabilityPerHit: 2,
    }),
    tags: ['tier1'],
  }),
  item({
    id: 'iron_pickaxe',
    name: 'Iron Pickaxe',
    description: 'The tool that opens up iron and copper. Everything metal waits behind it.',
    category: 'tool',
    stackSize: 1,
    weight: 3,
    maxDurability: 220,
    tool: { kinds: ['pickaxe'], tier: 2, efficiency: 1.8, durabilityPerUse: 1 },
    weapon: melee({
      damage: 17,
      damageType: 'pierce',
      range: 48,
      attackTicks: seconds(1.05),
      staminaCost: 10,
      armorPen: 0.15,
      durabilityPerHit: 2,
    }),
    tags: [],
  }),
  item({
    id: 'steel_pickaxe',
    name: 'Steel Pickaxe',
    description: 'Hardened point, sprung haft. Boulders come apart in handfuls.',
    category: 'tool',
    stackSize: 1,
    weight: 3.1,
    maxDurability: 440,
    rarity: 'uncommon',
    tool: { kinds: ['pickaxe'], tier: 3, efficiency: 2.5, durabilityPerUse: 1 },
    weapon: melee({
      damage: 22,
      damageType: 'pierce',
      range: 48,
      attackTicks: seconds(1),
      staminaCost: 10,
      armorPen: 0.25,
      durabilityPerHit: 2,
    }),
    tags: [],
  }),
  item({
    id: 'shovel',
    name: 'Shovel',
    description: 'Digs clay, sand and graves.',
    category: 'tool',
    stackSize: 1,
    weight: 2.2,
    maxDurability: 200,
    tool: { kinds: ['shovel'], tier: 2, efficiency: 1.6, durabilityPerUse: 1 },
    weapon: melee({ damage: 12, damageType: 'blunt', range: 50, staminaCost: 8, knockback: 80 }),
    tags: [],
  }),
  item({
    id: 'hoe',
    name: 'Hoe',
    description: 'Breaks sod into a seed bed. Farming starts with this or not at all.',
    category: 'tool',
    stackSize: 1,
    weight: 1.9,
    maxDurability: 180,
    tool: { kinds: ['hoe'], tier: 2, efficiency: 1.5, durabilityPerUse: 1 },
    weapon: melee({ damage: 9, damageType: 'blunt', range: 50, staminaCost: 7 }),
    tags: [],
  }),
  item({
    id: 'stone_knife',
    name: 'Stone Knife',
    description: 'A knapped flint edge. It skins, it whittles, it wears out.',
    category: 'tool',
    stackSize: 1,
    weight: 0.4,
    maxDurability: 45,
    tool: { kinds: ['knife'], tier: 1, efficiency: 1, durabilityPerUse: 1 },
    weapon: melee({
      damage: 7,
      damageType: 'slash',
      range: 34,
      attackTicks: seconds(0.55),
      staminaCost: 4,
      critChance: 0.14,
      critMultiplier: 2.4,
      knockback: 20,
    }),
    tags: ['tier1'],
  }),
  item({
    id: 'iron_knife',
    name: 'Iron Knife',
    description: 'Thin, quick, and it keeps its edge. Butchering and back alleys.',
    category: 'tool',
    stackSize: 1,
    weight: 0.5,
    maxDurability: 160,
    tool: { kinds: ['knife'], tier: 2, efficiency: 1.7, durabilityPerUse: 1 },
    weapon: melee({
      damage: 13,
      damageType: 'slash',
      range: 36,
      attackTicks: seconds(0.5),
      staminaCost: 4,
      critChance: 0.18,
      critMultiplier: 2.6,
      armorPen: 0.1,
      knockback: 20,
    }),
    tags: [],
  }),
  item({
    id: 'hammer',
    name: 'Hammer',
    description: 'Drives nails, dresses stone, and settles arguments.',
    category: 'tool',
    stackSize: 1,
    weight: 1.2,
    maxDurability: 260,
    tool: { kinds: ['hammer'], tier: 2, efficiency: 1.5, durabilityPerUse: 1 },
    weapon: melee({ damage: 12, damageType: 'blunt', range: 38, staminaCost: 6, knockback: 100 }),
    tags: [],
  }),
  item({
    id: 'saw',
    name: 'Saw',
    description: 'Turns logs into planks instead of splinters.',
    category: 'tool',
    stackSize: 1,
    weight: 1.1,
    maxDurability: 220,
    tool: { kinds: ['saw'], tier: 2, efficiency: 1.6, durabilityPerUse: 1 },
    weapon: melee({ damage: 8, damageType: 'slash', range: 40, staminaCost: 6 }),
    tags: [],
  }),
  item({
    id: 'watering_can',
    name: 'Watering Can',
    description: 'Beaten from scrap. Carries enough for a bed of crops, if you walk carefully.',
    category: 'tool',
    stackSize: 1,
    weight: 1,
    maxDurability: 150,
    tool: { kinds: ['wateringCan'], tier: 1, efficiency: 1, durabilityPerUse: 1 },
    liquid: { capacity: 20, fillable: true },
    tags: ['farming'],
  }),
  item({
    id: 'sickle',
    name: 'Sickle',
    description: 'Harvests grain and fibre in armfuls rather than handfuls.',
    category: 'tool',
    stackSize: 1,
    weight: 0.8,
    maxDurability: 180,
    tool: { kinds: ['sickle'], tier: 2, efficiency: 1.6, durabilityPerUse: 1 },
    weapon: melee({
      damage: 11,
      damageType: 'slash',
      range: 40,
      attackTicks: seconds(0.6),
      critChance: 0.12,
      staminaCost: 5,
    }),
    tags: ['farming'],
  }),
  item({
    id: 'wrench',
    name: 'Wrench',
    description: 'Strips a car down to its useful bones.',
    category: 'tool',
    stackSize: 1,
    weight: 1.3,
    maxDurability: 240,
    tool: { kinds: ['wrench'], tier: 2, efficiency: 1.6, durabilityPerUse: 1 },
    weapon: melee({ damage: 13, damageType: 'blunt', range: 36, staminaCost: 6, knockback: 90 }),
    tags: [],
  }),
  item({
    id: 'lighter',
    name: 'Lighter',
    description: 'A few dozen flicks left in it. Worth more than it looks on a wet night.',
    category: 'tool',
    stackSize: 1,
    weight: 0.05,
    maxDurability: 40,
    rarity: 'uncommon',
    tool: { kinds: ['lighter'], tier: 1, efficiency: 1, durabilityPerUse: 1 },
    tags: ['ignition'],
  }),
  item({
    id: 'fishing_rod',
    name: 'Fishing Rod',
    description: 'Stick, line, bent nail. Quiet food, if you can sit still.',
    category: 'tool',
    stackSize: 1,
    weight: 0.9,
    maxDurability: 120,
    tool: { kinds: ['fishingRod'], tier: 1, efficiency: 1, durabilityPerUse: 1 },
    tags: [],
  }),
  item({
    id: 'multitool',
    name: 'Multitool',
    description:
      'Pre-collapse alloy, still tight in the joints. Four tools in a pocket, and irreplaceable.',
    category: 'tool',
    stackSize: 1,
    weight: 0.3,
    maxDurability: 300,
    rarity: 'rare',
    tool: {
      kinds: ['knife', 'saw', 'wrench', 'hammer'],
      tier: 4,
      efficiency: 2.2,
      durabilityPerUse: 1,
    },
    weapon: melee({
      damage: 9,
      damageType: 'slash',
      range: 30,
      attackTicks: seconds(0.5),
      staminaCost: 3,
      critChance: 0.14,
    }),
    tags: [],
  }),
];

// ---------------------------------------------------------------------------
// Melee weapons
//
// `fists` is deliberately absent: unarmed damage belongs to the combat system, not
// to a phantom item that would have to be in every inventory. Axes, knives, the
// hammer and the sledge double as weapons rather than shipping a second "combat"
// copy of each, which is why there is no separate `hatchet_weapon`.
// ---------------------------------------------------------------------------

const MELEE_WEAPONS: ItemDef[] = [
  item({
    id: 'wooden_club',
    name: 'Wooden Club',
    description: 'A log with one end narrowed. Crude, and it caves a skull in anyway.',
    category: 'weapon',
    stackSize: 1,
    weight: 1.6,
    maxDurability: 90,
    weapon: melee({
      damage: 12,
      damageType: 'blunt',
      range: 42,
      attackTicks: seconds(0.85),
      knockback: 110,
      staminaCost: 7,
    }),
    tags: ['tier1'],
  }),
  item({
    id: 'baseball_bat',
    name: 'Baseball Bat',
    description: 'Ash, taped grip, somebody else’s initials burned into the barrel.',
    category: 'weapon',
    stackSize: 1,
    weight: 1.1,
    maxDurability: 150,
    weapon: melee({
      damage: 17,
      damageType: 'blunt',
      range: 52,
      attackTicks: seconds(0.85),
      arcDegrees: 90,
      knockback: 150,
      staminaCost: 8,
      maxTargets: 2,
      blockReduction: 0.2,
    }),
    tags: [],
  }),
  item({
    id: 'nail_bat',
    name: 'Nail Bat',
    description: 'A bat with a dozen nails hammered through it. Every hit tears on the way out.',
    category: 'weapon',
    stackSize: 1,
    weight: 1.4,
    maxDurability: 120,
    weapon: melee({
      damage: 22,
      damageType: 'blunt',
      range: 52,
      attackTicks: seconds(0.9),
      arcDegrees: 85,
      knockback: 140,
      staminaCost: 9,
      critChance: 0.14,
      critMultiplier: 2.1,
      armorPen: 0.18,
      maxTargets: 2,
      durabilityPerHit: 2,
    }),
    tags: [],
  }),
  item({
    id: 'machete',
    name: 'Machete',
    description: 'Long, heavy at the tip, and it takes an arm off at the elbow.',
    category: 'weapon',
    stackSize: 1,
    weight: 1,
    maxDurability: 220,
    rarity: 'uncommon',
    weapon: melee({
      damage: 25,
      damageType: 'slash',
      range: 50,
      attackTicks: seconds(0.7),
      arcDegrees: 80,
      staminaCost: 7,
      critChance: 0.12,
      critMultiplier: 2.2,
      armorPen: 0.15,
      maxTargets: 2,
      blockReduction: 0.15,
    }),
    tags: [],
  }),
  item({
    id: 'spear',
    name: 'Spear',
    description: 'Reach. The only thing standing between you and a bite you cannot take back.',
    category: 'weapon',
    stackSize: 1,
    weight: 1.7,
    maxDurability: 110,
    weapon: melee({
      damage: 20,
      damageType: 'pierce',
      range: 74,
      attackTicks: seconds(1),
      arcDegrees: 30,
      knockback: 100,
      staminaCost: 8,
      critChance: 0.1,
      critMultiplier: 2.4,
      armorPen: 0.2,
      twoHanded: true,
      durabilityPerHit: 2,
    }),
    tags: ['tier1'],
  }),
  item({
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'Somebody’s idea of a sword, forged from what was to hand. It works.',
    category: 'weapon',
    stackSize: 1,
    weight: 1.9,
    maxDurability: 320,
    rarity: 'uncommon',
    weapon: melee({
      damage: 31,
      damageType: 'slash',
      range: 54,
      attackTicks: seconds(0.8),
      arcDegrees: 95,
      knockback: 110,
      staminaCost: 9,
      critChance: 0.13,
      critMultiplier: 2.3,
      armorPen: 0.2,
      maxTargets: 3,
      blockReduction: 0.35,
    }),
    tags: [],
  }),
  item({
    id: 'sledgehammer',
    name: 'Sledgehammer',
    description: 'Slow as a season, and nothing it connects with gets back up. Doors included.',
    category: 'weapon',
    stackSize: 1,
    weight: 5.5,
    maxDurability: 280,
    weapon: melee({
      damage: 38,
      damageType: 'blunt',
      range: 56,
      attackTicks: seconds(1.7),
      windupTicks: seconds(0.5),
      arcDegrees: 110,
      knockback: 260,
      staminaCost: 18,
      critChance: 0.08,
      critMultiplier: 2,
      armorPen: 0.3,
      maxTargets: 3,
      loudness: 320,
      twoHanded: true,
    }),
    tags: ['demolition'],
  }),
  item({
    id: 'crowbar',
    name: 'Crowbar',
    description: 'Prying tool first, weapon second, and never quite bad at either.',
    category: 'weapon',
    stackSize: 1,
    weight: 2.3,
    maxDurability: 340,
    weapon: melee({
      damage: 18,
      damageType: 'blunt',
      range: 44,
      attackTicks: seconds(0.85),
      knockback: 120,
      staminaCost: 8,
      armorPen: 0.12,
      blockReduction: 0.25,
    }),
    tags: ['pry'],
  }),
  item({
    id: 'kitchen_knife',
    name: 'Kitchen Knife',
    description: 'Out of somebody’s drawer. Fine for onions, honest about anything larger.',
    category: 'weapon',
    stackSize: 1,
    weight: 0.3,
    maxDurability: 80,
    tool: { kinds: ['knife'], tier: 1, efficiency: 1.1, durabilityPerUse: 1 },
    weapon: melee({
      damage: 11,
      damageType: 'slash',
      range: 32,
      attackTicks: seconds(0.5),
      staminaCost: 4,
      critChance: 0.16,
      critMultiplier: 2.5,
      knockback: 15,
    }),
    tags: [],
  }),
  item({
    id: 'pitchfork',
    name: 'Pitchfork',
    description: 'Four tines, farm-length handle. Pins one and pushes two.',
    category: 'weapon',
    stackSize: 1,
    weight: 2.6,
    maxDurability: 150,
    weapon: melee({
      damage: 19,
      damageType: 'pierce',
      range: 70,
      attackTicks: seconds(1.05),
      arcDegrees: 40,
      knockback: 130,
      staminaCost: 9,
      armorPen: 0.12,
      maxTargets: 2,
      twoHanded: true,
    }),
    tags: [],
  }),
];

// ---------------------------------------------------------------------------
// Ranged weapons and ammunition
//
// A firearm's `loudness` is the whole balance lever for late game: 4 000-6 400 px is
// four to six chunks of zombies turning towards the noise. `weapon.projectileDefId`
// is only the fallback for the default ammunition - the loaded round's own
// `projectileDefId` wins, which is how iron arrows out-perform wooden ones from the
// same bow.
// ---------------------------------------------------------------------------

const RANGED_WEAPONS: ItemDef[] = [
  item({
    id: 'hunting_bow',
    name: 'Hunting Bow',
    description: 'Stick, sinew, patience. Kills deer and walkers without telling the street.',
    category: 'weapon',
    stackSize: 1,
    weight: 1.2,
    maxDurability: 220,
    weapon: ranged({
      damage: 22,
      damageType: 'pierce',
      range: 640,
      ammoDefIds: ['arrow_wooden', 'arrow_iron'],
      projectileDefId: 'arrow_wooden',
      attackTicks: seconds(1.5),
      windupTicks: seconds(0.6),
      staminaCost: 6,
      magazineSize: 1,
      reloadTicks: seconds(1.3),
      spreadDegrees: 4,
      loudness: 260,
      critChance: 0.12,
      critMultiplier: 2.5,
      armorPen: 0.1,
    }),
    tags: ['tier1', 'quiet'],
  }),
  item({
    id: 'crossbow',
    name: 'Crossbow',
    description: 'Slow to crank, brutal on release, and it barely whispers.',
    category: 'weapon',
    stackSize: 1,
    weight: 3,
    maxDurability: 260,
    rarity: 'uncommon',
    weapon: ranged({
      damage: 34,
      damageType: 'pierce',
      range: 760,
      ammoDefIds: ['bolt'],
      projectileDefId: 'bolt',
      attackTicks: seconds(1.1),
      windupTicks: seconds(0.25),
      staminaCost: 4,
      magazineSize: 1,
      reloadTicks: seconds(3),
      spreadDegrees: 2,
      loudness: 240,
      critChance: 0.15,
      critMultiplier: 2.6,
      armorPen: 0.3,
    }),
    tags: ['quiet'],
  }),
  item({
    id: 'pistol_9mm',
    name: '9mm Pistol',
    description: 'Fifteen rounds and a very loud opinion. Everything within four chunks hears it.',
    category: 'weapon',
    stackSize: 1,
    weight: 1,
    maxDurability: 420,
    rarity: 'rare',
    weapon: ranged({
      damage: 26,
      damageType: 'bullet',
      range: 900,
      ammoDefIds: ['ammo_9mm'],
      projectileDefId: 'bullet_9mm',
      attackTicks: seconds(0.35),
      magazineSize: 15,
      reloadTicks: seconds(2.5),
      spreadDegrees: 3.5,
      loudness: 4200,
      twoHanded: false,
      armorPen: 0.25,
    }),
    tags: ['firearm', 'loud'],
  }),
  item({
    id: 'rifle_308',
    name: '.308 Hunting Rifle',
    description: 'Reaches across a field and ends the argument. Then the field fills up.',
    category: 'weapon',
    stackSize: 1,
    weight: 3.8,
    maxDurability: 420,
    rarity: 'rare',
    weapon: ranged({
      damage: 58,
      damageType: 'bullet',
      range: 1600,
      ammoDefIds: ['ammo_308'],
      projectileDefId: 'bullet_308',
      attackTicks: seconds(1.2),
      windupTicks: seconds(0.3),
      magazineSize: 5,
      reloadTicks: seconds(3.5),
      spreadDegrees: 1.2,
      loudness: 6400,
      critChance: 0.14,
      critMultiplier: 2.8,
      armorPen: 0.45,
    }),
    tags: ['firearm', 'loud'],
  }),
  item({
    id: 'shotgun',
    name: 'Pump Shotgun',
    description: 'Eight pellets of instant regret at close range. Also a dinner bell.',
    category: 'weapon',
    stackSize: 1,
    weight: 3.4,
    maxDurability: 380,
    rarity: 'rare',
    weapon: ranged({
      damage: 15,
      damageType: 'bullet',
      range: 420,
      ammoDefIds: ['ammo_shell'],
      projectileDefId: 'pellet',
      attackTicks: seconds(0.9),
      magazineSize: 6,
      reloadTicks: seconds(4.5),
      spreadDegrees: 12,
      pellets: 8,
      loudness: 5600,
      knockback: 130,
      armorPen: 0.15,
    }),
    tags: ['firearm', 'loud'],
  }),
  item({
    id: 'molotov',
    name: 'Molotov Cocktail',
    description: 'A bottle, a rag and a bad idea. Burns a doorway shut for a minute.',
    category: 'weapon',
    stackSize: 1,
    weight: 0.9,
    weapon: thrown({
      damage: 42,
      damageType: 'fire',
      range: 420,
      projectileDefId: 'molotov_flask',
      attackTicks: seconds(1.4),
      loudness: 900,
      knockback: 0,
      maxTargets: 6,
    }),
    tags: ['flammable', 'explosive'],
  }),
  item({
    id: 'throwing_rock',
    name: 'Throwing Rock',
    description:
      'A fist-sized stone picked for balance. Barely hurts, but it lands somewhere you are not.',
    category: 'weapon',
    stackSize: 1,
    weight: 0.5,
    weapon: thrown({
      damage: 7,
      damageType: 'blunt',
      range: 300,
      projectileDefId: 'thrown_rock',
      attackTicks: seconds(0.9),
      loudness: 420,
      staminaCost: 4,
    }),
    tags: ['tier1', 'distraction'],
  }),
];

const AMMO: ItemDef[] = [
  item({
    id: 'arrow_wooden',
    name: 'Wooden Arrow',
    description: 'Fire-hardened shaft, flint head. Usually survives to be pulled out again.',
    category: 'ammo',
    weight: 0.05,
    stackSize: 40,
    projectileDefId: 'arrow_wooden',
    tags: ['arrow'],
  }),
  item({
    id: 'arrow_iron',
    name: 'Iron Arrow',
    description: 'Heavier head, punches through a leather jacket and whatever is wearing it.',
    category: 'ammo',
    weight: 0.08,
    stackSize: 40,
    projectileDefId: 'arrow_iron',
    tags: ['arrow'],
  }),
  item({
    id: 'bolt',
    name: 'Crossbow Bolt',
    description: 'Short, thick and mean. Made to be recovered.',
    category: 'ammo',
    weight: 0.07,
    stackSize: 40,
    projectileDefId: 'bolt',
    tags: ['bolt'],
  }),
  item({
    id: 'ammo_9mm',
    name: '9mm Round',
    description: 'Common before, precious now.',
    category: 'ammo',
    weight: 0.012,
    stackSize: 120,
    rarity: 'uncommon',
    projectileDefId: 'bullet_9mm',
    tags: ['bullet'],
  }),
  item({
    id: 'ammo_308',
    name: '.308 Round',
    description: 'Full-power rifle brass. Six of them are a plan.',
    category: 'ammo',
    weight: 0.024,
    stackSize: 80,
    rarity: 'rare',
    projectileDefId: 'bullet_308',
    tags: ['bullet'],
  }),
  item({
    id: 'ammo_shell',
    name: 'Shotgun Shell',
    description: 'Plastic hull, brass base, a handful of lead.',
    category: 'ammo',
    weight: 0.045,
    stackSize: 60,
    rarity: 'uncommon',
    projectileDefId: 'pellet',
    tags: ['bullet'],
  }),
];

// ---------------------------------------------------------------------------
// Armour and carry gear
//
// `coverage` is per body part, `protection` is flat reduction per damage type
// *before* penetration. `biteResistance` multiplies a zombie bite's chance of
// reaching skin, so 1 = no help at all and 0.1 = almost bite-proof.
// ---------------------------------------------------------------------------

const ARMOR: ItemDef[] = [
  item({
    id: 'leather_cap',
    name: 'Leather Cap',
    description: 'Stops a scrape and keeps the rain out. That is the extent of it.',
    category: 'armor',
    stackSize: 1,
    weight: 0.3,
    maxDurability: 120,
    armor: armor({
      slot: 'head',
      coverage: { head: 0.6 },
      protection: { blunt: 2, slash: 1 },
      warmth: 2,
      biteResistance: 0.8,
    }),
    tags: [],
  }),
  item({
    id: 'hard_hat',
    name: 'Hard Hat',
    description: 'Site helmet. Designed for falling bricks, repurposed for falling teeth.',
    category: 'armor',
    stackSize: 1,
    weight: 0.5,
    maxDurability: 220,
    armor: armor({
      slot: 'head',
      coverage: { head: 0.75 },
      protection: { blunt: 6, slash: 2, fall: 4 },
      warmth: 1,
      biteResistance: 0.6,
    }),
    tags: [],
  }),
  item({
    id: 'motorcycle_helmet',
    name: 'Motorcycle Helmet',
    description: 'Full face, tinted visor. They can bite it all day.',
    category: 'armor',
    stackSize: 1,
    weight: 1.4,
    maxDurability: 300,
    rarity: 'uncommon',
    armor: armor({
      slot: 'head',
      coverage: { head: 0.95 },
      protection: { blunt: 9, slash: 6, pierce: 4, zombieBite: 8, fall: 6 },
      warmth: 4,
      encumbrance: 0.03,
      biteResistance: 0.15,
    }),
    tags: [],
  }),
  item({
    id: 'gas_mask',
    name: 'Gas Mask',
    description:
      'Filters still good. Breathing is the only thing it helps with, and sometimes that is everything.',
    category: 'armor',
    stackSize: 1,
    weight: 0.8,
    maxDurability: 160,
    rarity: 'rare',
    armor: armor({
      slot: 'face',
      coverage: { head: 0.25 },
      protection: { poison: 24, suffocation: 20, infection: 4 },
      warmth: 1,
      encumbrance: 0.02,
      biteResistance: 0.7,
    }),
    tags: [],
  }),
  item({
    id: 'cloth_shirt',
    name: 'Cloth Shirt',
    description: 'Homespun and shapeless. Better than bare skin, barely.',
    category: 'armor',
    stackSize: 1,
    weight: 0.4,
    maxDurability: 110,
    armor: armor({
      slot: 'chest',
      coverage: { torso: 0.9, leftArm: 0.6, rightArm: 0.6 },
      protection: { blunt: 1, cold: 1 },
      warmth: 4,
    }),
    tags: ['tier1'],
  }),
  item({
    id: 'leather_jacket',
    name: 'Leather Jacket',
    description: 'Thick hide, long sleeves. Teeth catch on it instead of in you.',
    category: 'armor',
    stackSize: 1,
    weight: 2.2,
    maxDurability: 260,
    armor: armor({
      slot: 'chest',
      coverage: { torso: 0.95, leftArm: 0.85, rightArm: 0.85 },
      protection: { slash: 5, blunt: 3, pierce: 3, zombieBite: 6, cold: 3 },
      warmth: 9,
      encumbrance: 0.02,
      biteResistance: 0.45,
      durabilityPerHit: 1,
    }),
    tags: [],
  }),
  item({
    id: 'kevlar_vest',
    name: 'Kevlar Vest',
    description: 'Soft armour under a nylon shell. Stops bullets, does nothing for your arms.',
    category: 'armor',
    stackSize: 1,
    weight: 3.6,
    maxDurability: 400,
    rarity: 'rare',
    armor: armor({
      slot: 'chest',
      coverage: { torso: 0.95 },
      protection: { bullet: 14, slash: 8, pierce: 9, blunt: 5, zombieBite: 12 },
      warmth: 5,
      encumbrance: 0.06,
      biteResistance: 0.2,
    }),
    tags: [],
  }),
  item({
    id: 'plate_carrier',
    name: 'Plate Carrier',
    description: 'Ceramic plates front and back. Heavy, hot, and the best decision you will make.',
    category: 'armor',
    stackSize: 1,
    weight: 8,
    maxDurability: 520,
    rarity: 'epic',
    armor: armor({
      slot: 'chest',
      coverage: { torso: 1, leftArm: 0.3, rightArm: 0.3 },
      protection: { bullet: 20, slash: 12, pierce: 14, blunt: 9, explosive: 8, zombieBite: 16 },
      warmth: 6,
      encumbrance: 0.12,
      biteResistance: 0.1,
    }),
    tags: [],
  }),
  item({
    id: 'cloth_pants',
    name: 'Cloth Pants',
    description: 'Two legs of woven fibre held up with cord.',
    category: 'armor',
    stackSize: 1,
    weight: 0.4,
    maxDurability: 110,
    armor: armor({
      slot: 'legs',
      coverage: { leftLeg: 0.85, rightLeg: 0.85 },
      protection: { blunt: 1, cold: 1 },
      warmth: 4,
    }),
    tags: ['tier1'],
  }),
  item({
    id: 'jeans',
    name: 'Jeans',
    description: 'Denim. Tougher than it has any right to be.',
    category: 'armor',
    stackSize: 1,
    weight: 0.7,
    maxDurability: 170,
    armor: armor({
      slot: 'legs',
      coverage: { leftLeg: 0.9, rightLeg: 0.9 },
      protection: { blunt: 2, slash: 2, zombieBite: 2 },
      warmth: 5,
      biteResistance: 0.7,
    }),
    tags: [],
  }),
  item({
    id: 'leather_pants',
    name: 'Leather Pants',
    description: 'Stiff, hot, and hard to bite through. Crawlers go for legs.',
    category: 'armor',
    stackSize: 1,
    weight: 1.8,
    maxDurability: 250,
    armor: armor({
      slot: 'legs',
      coverage: { leftLeg: 0.9, rightLeg: 0.9 },
      protection: { slash: 4, pierce: 3, blunt: 3, zombieBite: 5, cold: 2 },
      warmth: 7,
      encumbrance: 0.02,
      biteResistance: 0.5,
    }),
    tags: [],
  }),
  item({
    id: 'work_boots',
    name: 'Work Boots',
    description: 'Steel toes, thick soles. You can stamp on things.',
    category: 'armor',
    stackSize: 1,
    weight: 1.5,
    maxDurability: 280,
    armor: armor({
      slot: 'feet',
      coverage: { leftLeg: 0.25, rightLeg: 0.25 },
      protection: { blunt: 3, pierce: 3, fall: 3, cold: 2 },
      warmth: 4,
      biteResistance: 0.5,
    }),
    tags: [],
  }),
  item({
    id: 'leather_gloves',
    name: 'Leather Gloves',
    description: 'Saves your hands from thorns, glass and the occasional set of teeth.',
    category: 'armor',
    stackSize: 1,
    weight: 0.2,
    maxDurability: 150,
    armor: armor({
      slot: 'hands',
      coverage: { leftArm: 0.3, rightArm: 0.3 },
      protection: { slash: 2, blunt: 1, zombieBite: 2 },
      warmth: 2,
      biteResistance: 0.65,
    }),
    tags: [],
  }),
  item({
    id: 'work_gloves',
    name: 'Work Gloves',
    description: 'Reinforced palms. Hauling stone stops taking skin off.',
    category: 'armor',
    stackSize: 1,
    weight: 0.25,
    maxDurability: 210,
    armor: armor({
      slot: 'hands',
      coverage: { leftArm: 0.35, rightArm: 0.35 },
      protection: { slash: 3, blunt: 2, pierce: 1, zombieBite: 3 },
      warmth: 2,
      biteResistance: 0.55,
    }),
    tags: [],
  }),
  item({
    id: 'backpack_small',
    name: 'Small Backpack',
    description: 'Eight more pockets. The single biggest quality-of-life upgrade in the game.',
    category: 'container',
    stackSize: 1,
    weight: 0.8,
    maxDurability: 220,
    containerSlots: 8,
    armor: armor({
      slot: 'back',
      coverage: { torso: 0.2 },
      protection: { blunt: 1 },
      warmth: 1,
      encumbrance: 0.02,
    }),
    tags: ['carry'],
  }),
  item({
    id: 'backpack_large',
    name: 'Large Backpack',
    description: 'A hiking frame pack. Sixteen slots, and you feel every one of them.',
    category: 'container',
    stackSize: 1,
    weight: 1.8,
    maxDurability: 280,
    rarity: 'uncommon',
    containerSlots: 16,
    armor: armor({
      slot: 'back',
      coverage: { torso: 0.3 },
      protection: { blunt: 2 },
      warmth: 2,
      encumbrance: 0.05,
    }),
    tags: ['carry'],
  }),
  item({
    id: 'tool_belt',
    name: 'Tool Belt',
    description:
      'Four loops of leather at the hip. Fewer slots than a pack, no weight on your back, and craftable on day one.',
    category: 'container',
    stackSize: 1,
    weight: 0.6,
    maxDurability: 240,
    containerSlots: 4,
    armor: armor({
      slot: 'back',
      coverage: {},
      protection: {},
      warmth: 0,
      encumbrance: 0,
    }),
    tags: ['carry', 'tier1'],
  }),
];

// ---------------------------------------------------------------------------
// Food
//
// Raw meat, raw fish and wild mushrooms carry a real `sicknessChance`: eating them
// is a gamble you take when the alternative is starving, not a shortcut around
// cooking.
// ---------------------------------------------------------------------------

const FOOD: ItemDef[] = [
  item({
    id: 'berry',
    name: 'Berries',
    description: 'A handful off a bush. Sweet, wet, and gone in a second.',
    category: 'food',
    weight: 0.1,
    stackSize: 30,
    food: food({ nutrition: 6, hydration: 3, eatTicks: seconds(1) }),
    perishable: spoils(3),
    tags: ['forage', 'fruit'],
  }),
  item({
    id: 'apple',
    name: 'Apple',
    description: 'Bruised on one side. Still an apple.',
    category: 'food',
    weight: 0.2,
    stackSize: 20,
    food: food({ nutrition: 9, hydration: 6, eatTicks: seconds(1.5) }),
    perishable: spoils(6),
    tags: ['forage', 'fruit'],
  }),
  item({
    id: 'mushroom',
    name: 'Wild Mushroom',
    description: 'Probably the edible kind. Probably.',
    category: 'food',
    weight: 0.1,
    stackSize: 20,
    food: food({ nutrition: 5, hydration: 1, sicknessChance: 0.28, eatTicks: seconds(1.2) }),
    perishable: spoils(2.5),
    tags: ['forage', 'raw_food'],
  }),
  item({
    id: 'raw_meat',
    name: 'Raw Meat',
    description: 'Butchered and bloody. Cook it unless you enjoy fever dreams.',
    category: 'food',
    weight: 0.5,
    stackSize: 10,
    food: food({ nutrition: 15, sicknessChance: 0.45, eatTicks: seconds(2.5) }),
    perishable: spoils(1.5),
    tags: ['meat', 'raw_food'],
  }),
  item({
    id: 'cooked_meat',
    name: 'Cooked Meat',
    description: 'Charred outside, hot through. The single best reason to keep a fire.',
    category: 'food',
    weight: 0.4,
    stackSize: 10,
    food: food({
      nutrition: 32,
      stamina: 6,
      health: 2,
      sicknessChance: 0.01,
      eatTicks: seconds(2.5),
    }),
    perishable: spoils(4),
    tags: ['meat', 'cooked'],
  }),
  item({
    id: 'raw_fish',
    name: 'Raw Fish',
    description: 'Still slick. Bones and all if you are desperate.',
    category: 'food',
    weight: 0.4,
    stackSize: 10,
    food: food({ nutrition: 12, hydration: 2, sicknessChance: 0.4, eatTicks: seconds(2.5) }),
    perishable: spoils(1),
    tags: ['meat', 'raw_food', 'fish'],
  }),
  item({
    id: 'cooked_fish',
    name: 'Cooked Fish',
    description: 'Flaky and salty. Quiet food, honestly earned.',
    category: 'food',
    weight: 0.35,
    stackSize: 10,
    food: food({
      nutrition: 25,
      hydration: 3,
      stamina: 4,
      sicknessChance: 0.01,
      eatTicks: seconds(2.5),
    }),
    perishable: spoils(3),
    tags: ['meat', 'cooked', 'fish'],
  }),
  item({
    id: 'egg',
    name: 'Egg',
    description: 'Warm from the nest. Fragile in a pack full of stone.',
    category: 'food',
    weight: 0.06,
    stackSize: 20,
    food: food({ nutrition: 9, sicknessChance: 0.14, eatTicks: seconds(1.5) }),
    perishable: spoils(5),
    tags: ['ingredient'],
  }),
  item({
    id: 'flour',
    name: 'Flour',
    description: 'Wheat put through a grindstone. Edible dry, in the way sand is.',
    category: 'food',
    weight: 0.4,
    stackSize: 20,
    food: food({ nutrition: 3, sicknessChance: 0.15, eatTicks: seconds(2) }),
    tags: ['ingredient'],
  }),
  item({
    id: 'dough',
    name: 'Dough',
    description: 'Flour and water, kneaded. One fire away from bread.',
    category: 'food',
    weight: 0.5,
    stackSize: 10,
    food: food({ nutrition: 7, sicknessChance: 0.1, eatTicks: seconds(2) }),
    perishable: spoils(1.5),
    tags: ['ingredient'],
  }),
  item({
    id: 'bread',
    name: 'Bread',
    description: 'A dense flat loaf. Keeps for days and fills you like nothing else you can grow.',
    category: 'food',
    weight: 0.4,
    stackSize: 10,
    food: food({ nutrition: 28, stamina: 5, eatTicks: seconds(2.5) }),
    perishable: spoils(7),
    tags: ['cooked'],
  }),
  item({
    id: 'baked_potato',
    name: 'Baked Potato',
    description: 'Ash on the skin, steam in the middle.',
    category: 'food',
    weight: 0.3,
    stackSize: 10,
    food: food({ nutrition: 23, hydration: 3, stamina: 4, eatTicks: seconds(2) }),
    perishable: spoils(4),
    tags: ['cooked', 'vegetable'],
  }),
  item({
    id: 'soup_vegetable',
    name: 'Vegetable Soup',
    description: 'Whatever was in the plot, boiled to nothing. Hot, wet and enormously welcome.',
    category: 'food',
    weight: 0.6,
    stackSize: 10,
    food: food({ nutrition: 22, hydration: 26, health: 2, eatTicks: seconds(3) }),
    perishable: spoils(2),
    tags: ['cooked', 'vegetable'],
  }),
  item({
    id: 'stew_meat',
    name: 'Meat Stew',
    description: 'Meat, roots and stock. The best meal in the world after four days of berries.',
    category: 'food',
    weight: 0.8,
    stackSize: 10,
    food: food({ nutrition: 42, hydration: 18, stamina: 12, health: 5, eatTicks: seconds(3.5) }),
    perishable: spoils(2.5),
    tags: ['cooked', 'meat'],
  }),
  item({
    id: 'jerky',
    name: 'Jerky',
    description: 'Dried over a low fire for hours. Ugly, tough, and it does not rot.',
    category: 'food',
    weight: 0.12,
    stackSize: 30,
    food: food({ nutrition: 19, stamina: 5, eatTicks: seconds(2.5) }),
    tags: ['cooked', 'meat', 'preserved'],
  }),
  item({
    id: 'canned_beans',
    name: 'Canned Beans',
    description: 'Dented tin, intact seal. Somebody stocked a cupboard and never came home.',
    category: 'food',
    weight: 0.45,
    stackSize: 10,
    rarity: 'uncommon',
    food: food({ nutrition: 30, hydration: 8, eatTicks: seconds(3) }),
    tags: ['canned', 'preserved'],
  }),
  item({
    id: 'canned_soup',
    name: 'Canned Soup',
    description: 'Cold from the tin, and still the highlight of the week.',
    category: 'food',
    weight: 0.45,
    stackSize: 10,
    rarity: 'uncommon',
    food: food({ nutrition: 24, hydration: 22, eatTicks: seconds(3) }),
    tags: ['canned', 'preserved'],
  }),
  item({
    id: 'chocolate_bar',
    name: 'Chocolate Bar',
    description: 'Bloomed grey with age. Sugar is sugar.',
    category: 'food',
    weight: 0.1,
    stackSize: 20,
    rarity: 'uncommon',
    food: food({ nutrition: 17, stamina: 18, eatTicks: seconds(1.2) }),
    tags: ['preserved'],
  }),
  item({
    id: 'energy_bar',
    name: 'Energy Bar',
    description: 'Tastes like cardboard, hits like a slap. Eat it while running.',
    category: 'food',
    weight: 0.08,
    stackSize: 20,
    rarity: 'uncommon',
    food: food({
      nutrition: 14,
      stamina: 30,
      eatTicks: seconds(0.8),
      effects: [{ id: 'adrenaline', durationTicks: gameHours(0.4), magnitude: 0.12 }],
    }),
    tags: ['preserved'],
  }),
];

// ---------------------------------------------------------------------------
// Produce (crop outputs that are also food)
// ---------------------------------------------------------------------------

const PRODUCE: ItemDef[] = [
  item({
    id: 'wheat',
    name: 'Wheat',
    description: 'A bundle of ripe ears. Inedible until it has been through a grindstone.',
    category: 'produce',
    weight: 0.2,
    stackSize: 30,
    food: food({ nutrition: 3, eatTicks: seconds(2), sicknessChance: 0.05 }),
    tags: ['crop', 'ingredient'],
  }),
  item({
    id: 'corn',
    name: 'Corn',
    description: 'Heavy cob, bright kernels. Food, feed and the base of any still.',
    category: 'produce',
    weight: 0.35,
    stackSize: 20,
    food: food({ nutrition: 11, hydration: 4, eatTicks: seconds(2) }),
    perishable: spoils(6),
    tags: ['crop', 'vegetable'],
  }),
  item({
    id: 'potato',
    name: 'Potato',
    description: 'Dirt-caked and dense. Grows anywhere, keeps forever, tastes of nothing.',
    category: 'produce',
    weight: 0.3,
    stackSize: 30,
    food: food({ nutrition: 8, sicknessChance: 0.1, eatTicks: seconds(2) }),
    tags: ['crop', 'vegetable'],
  }),
  item({
    id: 'carrot',
    name: 'Carrot',
    description: 'Crisp and startlingly sweet.',
    category: 'produce',
    weight: 0.15,
    stackSize: 30,
    food: food({ nutrition: 7, hydration: 5, eatTicks: seconds(1.5) }),
    perishable: spoils(8),
    tags: ['crop', 'vegetable'],
  }),
  item({
    id: 'tomato',
    name: 'Tomato',
    description: 'Splits if you look at it wrong. Mostly water, and that is the point.',
    category: 'produce',
    weight: 0.15,
    stackSize: 20,
    food: food({ nutrition: 6, hydration: 10, eatTicks: seconds(1.2) }),
    perishable: spoils(3),
    tags: ['crop', 'vegetable'],
  }),
  item({
    id: 'cabbage',
    name: 'Cabbage',
    description: 'A dense head of leaves. Survives frost that kills everything else.',
    category: 'produce',
    weight: 0.7,
    stackSize: 10,
    food: food({ nutrition: 10, hydration: 6, eatTicks: seconds(2) }),
    perishable: spoils(9),
    tags: ['crop', 'vegetable'],
  }),
  item({
    id: 'pumpkin',
    name: 'Pumpkin',
    description: 'Absurdly heavy, absurdly filling. Worth the two weeks.',
    category: 'produce',
    weight: 3.5,
    stackSize: 5,
    food: food({ nutrition: 16, hydration: 8, eatTicks: seconds(3) }),
    perishable: spoils(12),
    tags: ['crop', 'vegetable'],
  }),
  item({
    id: 'onion',
    name: 'Onion',
    description: 'Sharp raw, transformative in a pot.',
    category: 'produce',
    weight: 0.15,
    stackSize: 30,
    food: food({ nutrition: 5, hydration: 3, eatTicks: seconds(1.5) }),
    perishable: spoils(10),
    tags: ['crop', 'vegetable'],
  }),
  item({
    id: 'beans',
    name: 'Beans',
    description: 'Keeps producing all season if you let it climb.',
    category: 'produce',
    weight: 0.2,
    stackSize: 30,
    food: food({ nutrition: 10, sicknessChance: 0.08, eatTicks: seconds(2) }),
    perishable: spoils(7),
    tags: ['crop', 'vegetable'],
  }),
  item({
    id: 'herb',
    name: 'Medicinal Herb',
    description: 'Bitter leaves. Steeped for pain, mashed for wounds, mouldered for antibiotics.',
    category: 'produce',
    weight: 0.05,
    stackSize: 40,
    food: food({ nutrition: 1, sicknessChance: 0.02, eatTicks: seconds(1) }),
    tags: ['crop', 'forage', 'medicinal'],
  }),
];

// ---------------------------------------------------------------------------
// Drinks
// ---------------------------------------------------------------------------

const DRINKS: ItemDef[] = [
  item({
    id: 'water_dirty',
    name: 'Dirty Water',
    description: 'Scooped from a pond. It will keep you alive and then make you wish it had not.',
    category: 'drink',
    weight: 0.5,
    stackSize: 10,
    drink: drink({ hydration: 30, sicknessChance: 0.35 }),
    tags: ['water'],
  }),
  item({
    id: 'water_clean',
    name: 'Clean Water',
    description: 'Boiled and cooled. The most underrated item in the world.',
    category: 'drink',
    weight: 0.5,
    stackSize: 10,
    drink: drink({ hydration: 34, sicknessChance: 0.01 }),
    tags: ['water', 'ingredient'],
  }),
  item({
    id: 'water_bottle',
    name: 'Water Bottle',
    description: 'Scratched plastic, screw cap. Four swallows of carried safety.',
    category: 'container',
    stackSize: 1,
    weight: 0.2,
    liquid: { capacity: 4, contentDefId: 'water_clean', fillable: true },
    tags: ['water', 'vessel'],
  }),
  item({
    id: 'canteen',
    name: 'Canteen',
    description: 'Metal, felt-covered, holds six. Refills at any water you can reach.',
    category: 'container',
    stackSize: 1,
    weight: 0.5,
    rarity: 'uncommon',
    liquid: { capacity: 6, fillable: true },
    tags: ['water', 'vessel'],
  }),
  item({
    id: 'coffee',
    name: 'Coffee',
    description: 'Stale grounds, boiled twice. Buys you an hour you have not earned.',
    category: 'drink',
    weight: 0.3,
    stackSize: 10,
    rarity: 'uncommon',
    drink: drink({
      hydration: 20,
      nutrition: 2,
      effects: [
        { id: 'adrenaline', durationTicks: gameHours(1), magnitude: 0.1 },
        { id: 'well_rested', durationTicks: gameHours(1.5), magnitude: 0.35 },
      ],
    }),
    tags: ['brew'],
  }),
  item({
    id: 'tea_herbal',
    name: 'Herbal Tea',
    description: 'Willow bark and bitter leaves. Takes the edge off an ache.',
    category: 'drink',
    weight: 0.3,
    stackSize: 10,
    drink: drink({
      hydration: 26,
      effects: [{ id: 'painkiller', durationTicks: gameHours(1.5), magnitude: 8 }],
    }),
    tags: ['brew', 'medicinal'],
  }),
  item({
    id: 'soda',
    name: 'Soda',
    description: 'Flat, warm, and 40 grams of sugar.',
    category: 'drink',
    weight: 0.4,
    stackSize: 10,
    rarity: 'uncommon',
    drink: drink({ hydration: 18, nutrition: 9, effects: [] }),
    tags: [],
  }),
  item({
    id: 'alcohol_moonshine',
    name: 'Moonshine',
    description: 'Fruit mash run through a still. Painkiller, antiseptic, terrible idea.',
    category: 'drink',
    weight: 0.5,
    stackSize: 10,
    drink: drink({
      hydration: 4,
      nutrition: 3,
      sicknessChance: 0.05,
      effects: [{ id: 'painkiller', durationTicks: gameHours(2), magnitude: 22 }],
    }),
    medical: medical({
      kind: 'disinfect',
      infectionCure: 14,
      cleanliness: 0.85,
      useTicks: seconds(3),
      effects: [{ id: 'antiseptic', durationTicks: gameHours(3), magnitude: 0.5 }],
    }),
    tags: ['brew', 'flammable', 'medicinal'],
  }),
];

// ---------------------------------------------------------------------------
// Medical
//
// `cleanliness` is the whole infection subsystem in one number: a dirty rag stops the
// bleeding and then quietly starts something worse.
// ---------------------------------------------------------------------------

const MEDICAL: ItemDef[] = [
  item({
    id: 'bandage_dirty',
    name: 'Dirty Bandage',
    description: 'Torn rag, wrapped tight. Stops the bleeding and invites the infection.',
    category: 'medical',
    weight: 0.05,
    stackSize: 20,
    medical: medical({
      kind: 'bandage',
      bleedStop: 0.7,
      heal: 2,
      cleanliness: 0.15,
      useTicks: seconds(2),
      effects: [{ id: 'bandaged', durationTicks: gameHours(6), magnitude: 0.15 }],
    }),
    tags: ['bandage', 'tier1'],
  }),
  item({
    id: 'bandage_clean',
    name: 'Clean Bandage',
    description: 'Boiled cloth, dried in the sun. Enormously better than a rag.',
    category: 'medical',
    weight: 0.05,
    stackSize: 20,
    medical: medical({
      kind: 'bandage',
      bleedStop: 0.85,
      heal: 4,
      cleanliness: 0.6,
      useTicks: seconds(2),
      effects: [{ id: 'bandaged', durationTicks: gameHours(8), magnitude: 0.6 }],
    }),
    tags: ['bandage'],
  }),
  item({
    id: 'bandage_sterile',
    name: 'Sterile Dressing',
    description: 'Sealed, antiseptic-soaked gauze. Nothing gets in behind it.',
    category: 'medical',
    weight: 0.05,
    stackSize: 20,
    rarity: 'uncommon',
    medical: medical({
      kind: 'bandage',
      bleedStop: 0.95,
      heal: 7,
      infectionCure: 8,
      cleanliness: 1,
      useTicks: seconds(2.5),
      effects: [{ id: 'bandaged', durationTicks: gameHours(12), magnitude: 1 }],
    }),
    tags: ['bandage'],
  }),
  item({
    id: 'disinfected_rag',
    name: 'Disinfected Rag',
    description: 'A rag soaked in antiseptic. Field-grade, and it works.',
    category: 'medical',
    weight: 0.05,
    stackSize: 20,
    medical: medical({
      kind: 'bandage',
      bleedStop: 0.8,
      heal: 3,
      infectionCure: 5,
      cleanliness: 0.85,
      useTicks: seconds(2),
      effects: [{ id: 'bandaged', durationTicks: gameHours(8), magnitude: 0.8 }],
    }),
    tags: ['bandage'],
  }),
  item({
    id: 'suture_kit',
    name: 'Suture Kit',
    description: 'Needle, sinew and a steady hand. Closes what a bandage only covers.',
    category: 'medical',
    stackSize: 1,
    weight: 0.2,
    maxDurability: 5,
    rarity: 'uncommon',
    medical: medical({
      kind: 'suture',
      bleedStop: 1,
      heal: 12,
      cleanliness: 0.9,
      useTicks: seconds(8),
      skillLevel: 3,
    }),
    tags: [],
  }),
  item({
    id: 'splint_wood',
    name: 'Wooden Splint',
    description: 'Two sticks and a rag. Sets a break badly, which beats not at all.',
    category: 'medical',
    weight: 0.4,
    stackSize: 10,
    medical: medical({
      kind: 'splint',
      heal: 2,
      fixesFracture: true,
      cleanliness: 0.3,
      useTicks: seconds(6),
      skillLevel: 1,
    }),
    tags: ['tier1'],
  }),
  item({
    id: 'splint_medical',
    name: 'Medical Splint',
    description: 'Padded alloy stay with proper straps. Sets a fracture and lets you walk.',
    category: 'medical',
    weight: 0.5,
    stackSize: 10,
    rarity: 'uncommon',
    medical: medical({
      kind: 'splint',
      heal: 6,
      painRelief: 8,
      fixesFracture: true,
      cleanliness: 0.8,
      useTicks: seconds(5),
    }),
    tags: [],
  }),
  item({
    id: 'antiseptic',
    name: 'Antiseptic',
    description: 'Stings like betrayal. Buys a wound a day of grace.',
    category: 'medical',
    weight: 0.2,
    stackSize: 10,
    medical: medical({
      kind: 'disinfect',
      infectionCure: 26,
      cleanliness: 1,
      useTicks: seconds(3),
      effects: [{ id: 'antiseptic', durationTicks: gameHours(8), magnitude: 1 }],
    }),
    tags: [],
  }),
  item({
    id: 'antibiotics',
    name: 'Antibiotics',
    description: 'A short course of pills. The only thing that reliably stops sepsis.',
    category: 'medical',
    weight: 0.05,
    stackSize: 10,
    rarity: 'rare',
    medical: medical({
      kind: 'pill',
      infectionCure: 60,
      useTicks: seconds(1.5),
      effects: [{ id: 'antibiotic', durationTicks: gameHours(12), magnitude: 1 }],
    }),
    tags: [],
  }),
  item({
    id: 'painkiller',
    name: 'Painkillers',
    description: 'Two white tablets. Pain goes quiet; the injury does not go away.',
    category: 'medical',
    weight: 0.02,
    stackSize: 20,
    medical: medical({
      kind: 'pill',
      painRelief: 45,
      useTicks: seconds(1.5),
      effects: [{ id: 'painkiller', durationTicks: gameHours(4), magnitude: 45 }],
    }),
    tags: [],
  }),
  item({
    id: 'morphine',
    name: 'Morphine',
    description: 'One ampoule. Erases pain completely, and your judgement with it.',
    category: 'medical',
    weight: 0.05,
    stackSize: 5,
    rarity: 'rare',
    medical: medical({
      kind: 'injection',
      painRelief: 95,
      heal: 4,
      useTicks: seconds(2.5),
      effects: [{ id: 'painkiller', durationTicks: gameHours(8), magnitude: 95 }],
    }),
    tags: [],
  }),
  item({
    id: 'vitamins',
    name: 'Vitamins',
    description: 'A jar of chalky tablets. Slow, boring, genuinely useful.',
    category: 'medical',
    weight: 0.1,
    stackSize: 10,
    medical: medical({
      kind: 'pill',
      heal: 4,
      infectionCure: 4,
      useTicks: seconds(1.5),
      effects: [{ id: 'well_fed', durationTicks: gameHours(8), magnitude: 0.2 }],
    }),
    tags: [],
  }),
  item({
    id: 'first_aid_kit',
    name: 'First Aid Kit',
    description: 'Green box, white cross, three uses left. Everything in one place for once.',
    category: 'medical',
    stackSize: 1,
    weight: 1.2,
    maxDurability: 3,
    rarity: 'uncommon',
    medical: medical({
      kind: 'bandage',
      bleedStop: 1,
      heal: 28,
      painRelief: 20,
      infectionCure: 22,
      cleanliness: 1,
      useTicks: seconds(7),
      effects: [{ id: 'bandaged', durationTicks: gameHours(12), magnitude: 1 }],
    }),
    tags: [],
  }),
];

// ---------------------------------------------------------------------------
// Seeds
// ---------------------------------------------------------------------------

interface SeedSpec {
  id: string;
  name: string;
  crop: string;
  description: string;
}

const SEED_SPECS: SeedSpec[] = [
  {
    id: 'seed_wheat',
    name: 'Wheat Seed',
    crop: 'wheat',
    description: 'A palmful of grain held back from the last harvest.',
  },
  {
    id: 'seed_corn',
    name: 'Corn Seed',
    crop: 'corn',
    description: 'Dried kernels. Slow, heavy, worth it.',
  },
  {
    id: 'seed_potato',
    name: 'Seed Potato',
    crop: 'potato',
    description: 'A sprouting tuber, cut to the eyes.',
  },
  {
    id: 'seed_carrot',
    name: 'Carrot Seed',
    crop: 'carrot',
    description: 'Dust-fine seed. Sow thick, thin later.',
  },
  {
    id: 'seed_tomato',
    name: 'Tomato Seed',
    crop: 'tomato',
    description: 'Scraped from a ripe fruit and dried on paper.',
  },
  {
    id: 'seed_cabbage',
    name: 'Cabbage Seed',
    crop: 'cabbage',
    description: 'Cold-hardy. The last thing still growing in autumn.',
  },
  {
    id: 'seed_pumpkin',
    name: 'Pumpkin Seed',
    crop: 'pumpkin',
    description: 'Flat white seeds. Needs room and a whole season.',
  },
  {
    id: 'seed_onion',
    name: 'Onion Set',
    crop: 'onion',
    description: 'Small bulbs ready to go back in the ground.',
  },
  {
    id: 'seed_beans',
    name: 'Bean Seed',
    crop: 'beans',
    description: 'Give it something to climb and it keeps giving back.',
  },
  {
    id: 'seed_herb',
    name: 'Herb Seed',
    crop: 'herb',
    description: 'Wild medicinal seed. The start of a medicine cabinet.',
  },
];

const SEEDS: ItemDef[] = SEED_SPECS.map((spec) =>
  item({
    id: spec.id,
    name: spec.name,
    description: spec.description,
    category: 'seed',
    weight: 0.02,
    stackSize: 40,
    cropDefId: spec.crop,
    tags: ['seed', 'farming'],
  }),
);

// ---------------------------------------------------------------------------
// Placeables
//
// Walls, floors, doors and every other pure-cost structure are built straight from
// resources through the build menu, so they deliberately have no item form. Only
// things you carry as an object - a station, a box, a bed - get a "kit".
// ---------------------------------------------------------------------------

interface KitSpec {
  id: string;
  name: string;
  description: string;
  structure: string;
  weight: number;
  rarity?: ItemDef['rarity'];
  extraTags?: string[];
}

const KIT_SPECS: KitSpec[] = [
  {
    id: 'campfire_kit',
    name: 'Campfire Kit',
    description: 'A ring of stones and a bundle of kindling. Light, warmth, cooking, safety.',
    structure: 'campfire',
    weight: 3,
    extraTags: ['tier1'],
  },
  {
    id: 'workbench_kit',
    name: 'Workbench Kit',
    description: 'Trestles and a top, ready to assemble. Everything worth making needs it.',
    structure: 'workbench',
    weight: 8,
    extraTags: ['tier1'],
  },
  {
    id: 'storage_box_kit',
    name: 'Storage Box Kit',
    description: 'Flat-packed crate. Twenty slots that are not on your back.',
    structure: 'storage_box',
    weight: 6,
  },
  {
    id: 'bed_kit',
    name: 'Bed Kit',
    description: 'Frame, slats and a stuffed mattress. Sleep is how you get the night back.',
    structure: 'bed_wood',
    weight: 12,
  },
  {
    id: 'farm_plot_kit',
    name: 'Farm Plot Kit',
    description: 'Edging boards and a bag of good soil. Turns dirt into a crop bed.',
    structure: 'farm_plot',
    weight: 5,
  },
  {
    id: 'water_barrel_kit',
    name: 'Water Barrel Kit',
    description: 'Staves, hoops and pitch. Collects rain so you stop walking to the pond.',
    structure: 'water_barrel',
    weight: 9,
  },
  {
    id: 'furnace_kit',
    name: 'Furnace Kit',
    description: 'Dressed block and raw clay for the lining. Iron begins here.',
    structure: 'furnace',
    weight: 22,
  },
  {
    id: 'anvil_kit',
    name: 'Anvil Kit',
    description: 'A block of iron on a stump. Absurdly heavy, and steel needs it.',
    structure: 'anvil',
    weight: 30,
  },
  {
    id: 'loom_kit',
    name: 'Loom Kit',
    description: 'Frame, beater and heddles. Fibre becomes cloth, hide becomes leather.',
    structure: 'loom',
    weight: 10,
  },
  {
    id: 'cooking_pot_kit',
    name: 'Cooking Pot',
    description: 'A beaten iron pot and tripod. Soups, stews and boiled water in quantity.',
    structure: 'cooking_pot',
    weight: 6,
  },
  {
    id: 'grindstone_kit',
    name: 'Grindstone Kit',
    description: 'A dressed wheel and a crank. Wheat into flour, edges back onto tools.',
    structure: 'grindstone',
    weight: 18,
  },
  {
    id: 'chemistry_bench_kit',
    name: 'Chemistry Bench Kit',
    description: 'Glassware, burner and a scavenged bench top. Medicine and powder.',
    structure: 'chemistry_bench',
    weight: 14,
    rarity: 'uncommon',
  },
];

const PLACEABLES: ItemDef[] = [
  ...KIT_SPECS.map((spec) =>
    item({
      id: spec.id,
      name: spec.name,
      description: spec.description,
      category: 'placeable',
      stackSize: 5,
      weight: spec.weight,
      ...(spec.rarity ? { rarity: spec.rarity } : {}),
      placesStructureDefId: spec.structure,
      tags: ['kit', ...(spec.extraTags ?? [])],
    }),
  ),
  item({
    id: 'torch',
    name: 'Torch',
    description:
      'Resin-soaked fibre on a stick. Held it lights your way; driven into a wall it lights a room.',
    category: 'placeable',
    // Deliberately stackable and durability-free: a torch's burn life lives in
    // `fuel.burnTicks`, which is what the wall socket's `light.fuel` is filled from and
    // what a held torch is consumed against. Giving it durability instead would force
    // `stackSize: 1` (see `maxStackSize()` in the simulation) and put five torches in
    // five inventory slots.
    stackSize: 10,
    weight: 0.6,
    placesStructureDefId: 'torch_wall',
    fuel: { burnTicks: 1200, heat: 8 },
    tags: ['light', 'light_source', 'fuel', 'tier1'],
  }),
  item({
    id: 'lantern',
    name: 'Lantern',
    description: 'Glass, wick and a reservoir. Brighter and far longer-lived than a torch.',
    category: 'placeable',
    stackSize: 1,
    weight: 1.4,
    maxDurability: 900,
    placesStructureDefId: 'lantern_post',
    tags: ['light', 'light_source'],
  }),
];

// ---------------------------------------------------------------------------
// Misc: schematics, tools of the trade, navigation
//
// Schematics carry an `unlocks:<recipeId>` tag rather than a dedicated field, because
// `ItemDef` has no unlock slot. `validateGameData` resolves every one of those tags
// against the recipe table, so a renamed recipe cannot leave a dead schematic behind.
// ---------------------------------------------------------------------------

interface SchematicSpec {
  id: string;
  name: string;
  description: string;
  unlocks: string[];
}

const SCHEMATIC_SPECS: SchematicSpec[] = [
  {
    id: 'schematic_steel',
    name: 'Schematic: Crucible Steel',
    description: 'Water-stained notes on carburising iron. Hours of somebody else’s work.',
    unlocks: ['smelt_steel_ingot', 'forge_steel_axe', 'forge_steel_pickaxe'],
  },
  {
    id: 'schematic_crossbow',
    name: 'Schematic: Crossbow',
    description: 'Drawings of a prod, a nut and a trigger. Quiet, lethal, and not obvious.',
    unlocks: ['craft_crossbow'],
  },
  {
    id: 'schematic_ammunition',
    name: 'Schematic: Handloading',
    description: 'A reloading table torn from a manual. Charges, crimps, seating depths.',
    unlocks: ['forge_ammo_9mm', 'forge_ammo_308', 'forge_ammo_shell'],
  },
  {
    id: 'schematic_medicine',
    name: 'Schematic: Field Pharmacy',
    description: 'Culturing notes in a careful hand. How to grow a cure in a jar.',
    unlocks: ['make_antibiotics', 'make_first_aid_kit'],
  },
];

const MISC: ItemDef[] = [
  ...SCHEMATIC_SPECS.map((spec) =>
    item({
      id: spec.id,
      name: spec.name,
      description: spec.description,
      category: 'misc',
      stackSize: 1,
      weight: 0.1,
      rarity: 'rare',
      tags: ['schematic', ...spec.unlocks.map((recipe) => `unlocks:${recipe}`)],
    }),
  ),
  item({
    id: 'door_key',
    name: 'Door Key',
    description: 'Cut for one lock somewhere. Worth carrying until you find out which.',
    category: 'misc',
    stackSize: 10,
    weight: 0.02,
    tags: ['key'],
  }),
  item({
    id: 'lockpick',
    name: 'Lockpick',
    description: 'Bent wire and a tension bar. Opens what you did not build, sometimes.',
    category: 'misc',
    stackSize: 1,
    weight: 0.05,
    maxDurability: 12,
    tags: ['key'],
  }),
  item({
    id: 'compass',
    name: 'Compass',
    description:
      'Points north whatever the weather does. Cheap insurance against walking in circles.',
    category: 'misc',
    stackSize: 1,
    weight: 0.1,
    rarity: 'uncommon',
    tags: ['navigation'],
  }),
  item({
    id: 'map',
    name: 'Regional Map',
    description: 'Folded, torn along the creases. Reveals the ground around you as you go.',
    category: 'misc',
    stackSize: 1,
    weight: 0.1,
    rarity: 'uncommon',
    tags: ['navigation'],
  }),
  item({
    id: 'radio',
    name: 'Radio',
    description: 'Mostly static. Occasionally a voice, and then you have a decision to make.',
    category: 'misc',
    stackSize: 1,
    weight: 0.9,
    rarity: 'rare',
    tags: ['electronic'],
  }),
  item({
    id: 'flashlight',
    name: 'Flashlight',
    description: 'A tight cone of light and a battery that is always nearly done.',
    category: 'misc',
    stackSize: 1,
    weight: 0.4,
    maxDurability: 500,
    rarity: 'uncommon',
    tags: ['light', 'light_source', 'electronic'],
  }),
];

// ---------------------------------------------------------------------------

/** Every item definition in the game, in build-menu-ish reading order. */
export const ITEM_DEFS: readonly ItemDef[] = [
  ...RESOURCES,
  ...TOOLS,
  ...MELEE_WEAPONS,
  ...RANGED_WEAPONS,
  ...AMMO,
  ...ARMOR,
  ...FOOD,
  ...PRODUCE,
  ...DRINKS,
  ...MEDICAL,
  ...SEEDS,
  ...PLACEABLES,
  ...MISC,
];
