import { Biome } from '@survive/protocol';
import type { LootEntry, ResourceNodeDef } from '../types';
import { days } from './units';

/**
 * The resource-node table: everything in the world you can hit until it gives you
 * something.
 *
 * The single most important field here is `wrongToolMultiplier`, because it is what
 * decides the shape of the first hour:
 *
 * - **0 means impossible bare-handed.** Living trees, boulders and every ore vein are
 *   0. You cannot punch down a pine, and you cannot chip iron out of rock with a
 *   rock.
 * - **Small positive values mean "possible, but grim".** Dead trees (0.3), fallen logs
 *   (0.2), loose surface rock (0.15) and scrap piles (0.4) can be worked with bare
 *   hands, slowly. That is the bootstrap: fibre from a patch, sticks and logs from
 *   dead wood, stone and flint from loose rock - which is exactly enough for a stone
 *   hatchet, and the hatchet opens up the living forest.
 *
 * `minToolTier` gates the second step. Iron and copper need tier 2 (an iron pickaxe),
 * and an iron pickaxe needs ingots, which come from re-smelting scavenged scrap. So
 * mining is unlocked by scavenging, not the other way round.
 *
 * `densityPerChunk` is at world density 1; the biome's own `resourceWeight` and the
 * `resourceDensity` config multiply into it.
 */

/** A drop line. `chance` 1 always drops; below that it is a roll per harvest. */
function y(defId: string, min: number, max: number, chance = 1): LootEntry {
  return { defId, min, max, chance, weight: 1 };
}

/**
 * Water never runs out, and `ResourceNodeDef` has no "infinite" flag, so the health
 * pool is simply larger than any plausible number of scoops.
 */
const INFINITE_NODE_HEALTH = 1_000_000_000;

export const RESOURCE_NODE_DEFS: readonly ResourceNodeDef[] = [
  // --- trees ------------------------------------------------------------
  {
    id: 'tree_pine',
    name: 'Pine',
    category: 'tree',
    maxHealth: 120,
    toolKinds: ['axe'],
    minToolTier: 1,
    wrongToolMultiplier: 0,
    yields: [y('wood_log', 3, 5), y('stick', 1, 3), y('resin', 1, 2, 0.5), y('bark', 1, 2, 0.6)],
    yieldPerHit: [y('stick', 1, 1, 0.2)],
    respawnTicks: days(6),
    radius: 14,
    blocksMovement: true,
    blocksSight: true,
    skill: 'woodcutting',
    xpPerHit: 1,
    xpOnDeplete: 12,
    variants: 3,
    sprite: 'node_tree_pine',
    noise: 240,
    spawnBiomes: {
      [Biome.Forest]: 1,
      [Biome.DeepForest]: 1.5,
      [Biome.Grassland]: 0.25,
      [Biome.Rocky]: 0.4,
      [Biome.Swamp]: 0.3,
    },
    densityPerChunk: 14,
  },
  {
    id: 'tree_oak',
    name: 'Oak',
    category: 'tree',
    maxHealth: 190,
    toolKinds: ['axe'],
    minToolTier: 1,
    wrongToolMultiplier: 0,
    yields: [y('wood_log', 4, 7), y('stick', 2, 4), y('bark', 2, 3)],
    yieldPerHit: [y('stick', 1, 1, 0.25)],
    respawnTicks: days(8),
    radius: 16,
    blocksMovement: true,
    blocksSight: true,
    skill: 'woodcutting',
    xpPerHit: 1,
    xpOnDeplete: 18,
    variants: 3,
    sprite: 'node_tree_oak',
    noise: 280,
    spawnBiomes: {
      [Biome.Forest]: 1.2,
      [Biome.DeepForest]: 1,
      [Biome.Grassland]: 0.35,
      [Biome.Farmland]: 0.3,
    },
    densityPerChunk: 8,
  },
  {
    id: 'tree_birch',
    name: 'Birch',
    category: 'tree',
    maxHealth: 100,
    toolKinds: ['axe'],
    minToolTier: 1,
    wrongToolMultiplier: 0,
    yields: [y('wood_log', 3, 4), y('bark', 3, 5), y('stick', 1, 2)],
    yieldPerHit: [y('bark', 1, 1, 0.3)],
    respawnTicks: days(5),
    radius: 12,
    blocksMovement: true,
    blocksSight: true,
    skill: 'woodcutting',
    xpPerHit: 1,
    xpOnDeplete: 10,
    variants: 2,
    sprite: 'node_tree_birch',
    noise: 220,
    spawnBiomes: {
      [Biome.Forest]: 0.8,
      [Biome.DeepForest]: 0.6,
      [Biome.Grassland]: 0.4,
      [Biome.Swamp]: 0.5,
    },
    densityPerChunk: 7,
  },
  {
    id: 'tree_dead',
    name: 'Dead Tree',
    category: 'tree',
    maxHealth: 70,
    toolKinds: ['axe'],
    minToolTier: 1,
    // Dry and brittle: the one tree you can break apart with your hands, and therefore
    // the source of the very first wood in a new world.
    wrongToolMultiplier: 0.3,
    yields: [y('wood_log', 2, 3), y('stick', 2, 4), y('bark', 1, 2, 0.4)],
    yieldPerHit: [y('stick', 1, 1, 0.35)],
    respawnTicks: -1,
    radius: 12,
    blocksMovement: true,
    blocksSight: false,
    skill: 'woodcutting',
    xpPerHit: 1,
    xpOnDeplete: 6,
    variants: 2,
    sprite: 'node_tree_dead',
    noise: 200,
    spawnBiomes: {
      [Biome.Grassland]: 0.7,
      [Biome.Forest]: 0.8,
      [Biome.DeepForest]: 0.6,
      [Biome.Rocky]: 0.8,
      [Biome.Swamp]: 1.2,
      [Biome.Farmland]: 0.5,
    },
    densityPerChunk: 5,
  },
  {
    id: 'fallen_log',
    name: 'Fallen Log',
    category: 'tree',
    maxHealth: 80,
    toolKinds: ['axe'],
    minToolTier: 1,
    wrongToolMultiplier: 0.2,
    yields: [y('wood_log', 3, 5), y('bark', 1, 3), y('mushroom', 1, 2, 0.3)],
    yieldPerHit: [],
    respawnTicks: -1,
    radius: 18,
    blocksMovement: true,
    blocksSight: false,
    skill: 'woodcutting',
    xpPerHit: 1,
    xpOnDeplete: 8,
    variants: 2,
    sprite: 'node_fallen_log',
    noise: 200,
    spawnBiomes: {
      [Biome.Forest]: 1,
      [Biome.DeepForest]: 1.4,
      [Biome.Swamp]: 0.8,
      [Biome.Grassland]: 0.3,
    },
    densityPerChunk: 4,
  },
  {
    id: 'stump',
    name: 'Tree Stump',
    category: 'tree',
    maxHealth: 60,
    toolKinds: ['axe'],
    minToolTier: 1,
    wrongToolMultiplier: 0.25,
    yields: [y('wood_log', 1, 2), y('resin', 1, 2, 0.6), y('stick', 1, 2, 0.5)],
    yieldPerHit: [],
    respawnTicks: -1,
    radius: 10,
    blocksMovement: false,
    blocksSight: false,
    skill: 'woodcutting',
    xpPerHit: 1,
    xpOnDeplete: 5,
    variants: 2,
    sprite: 'node_stump',
    noise: 180,
    spawnBiomes: {
      [Biome.Forest]: 0.9,
      [Biome.DeepForest]: 0.7,
      [Biome.Grassland]: 0.4,
      [Biome.Farmland]: 0.6,
      [Biome.Town]: 0.3,
    },
    densityPerChunk: 4,
  },

  // --- bushes and plants ------------------------------------------------
  {
    id: 'bush_berry',
    name: 'Berry Bush',
    category: 'bush',
    maxHealth: 20,
    toolKinds: [],
    minToolTier: 1,
    wrongToolMultiplier: 1,
    yields: [y('berry', 2, 4), y('plant_fiber', 1, 2), y('stick', 0, 1, 0.4)],
    yieldPerHit: [y('berry', 1, 2, 0.6)],
    respawnTicks: days(2),
    radius: 0,
    blocksMovement: false,
    blocksSight: false,
    skill: 'foraging',
    xpPerHit: 1,
    xpOnDeplete: 4,
    variants: 3,
    sprite: 'node_bush_berry',
    noise: 60,
    spawnBiomes: {
      [Biome.Grassland]: 1.2,
      [Biome.Forest]: 1,
      [Biome.DeepForest]: 0.7,
      [Biome.Swamp]: 0.6,
      [Biome.Farmland]: 0.5,
    },
    densityPerChunk: 6,
  },
  {
    id: 'bush_thorn',
    name: 'Thorn Bush',
    category: 'bush',
    maxHealth: 34,
    toolKinds: ['knife', 'sickle'],
    minToolTier: 1,
    wrongToolMultiplier: 0.4,
    yields: [y('plant_fiber', 3, 5), y('stick', 1, 2)],
    yieldPerHit: [y('plant_fiber', 1, 1, 0.5)],
    respawnTicks: days(3),
    radius: 12,
    blocksMovement: true,
    blocksSight: false,
    skill: 'foraging',
    xpPerHit: 1,
    xpOnDeplete: 5,
    variants: 2,
    sprite: 'node_bush_thorn',
    noise: 80,
    spawnBiomes: {
      [Biome.Grassland]: 0.8,
      [Biome.Forest]: 1,
      [Biome.DeepForest]: 1.1,
      [Biome.Swamp]: 1.2,
    },
    densityPerChunk: 5,
  },
  {
    id: 'plant_fiber_patch',
    name: 'Fiber Grass',
    category: 'plant',
    maxHealth: 12,
    toolKinds: [],
    minToolTier: 1,
    wrongToolMultiplier: 1,
    // Wild grass sets seed, and wild carrot grows in rough grass with it. These stray
    // seeds are the only bootstrap into farming that does not require finding a seed
    // packet in somebody's shed - which is why wheat and carrots are the two crops a
    // player can always get to, and why everything else waits on scavenging.
    yields: [y('plant_fiber', 3, 6), y('seed_wheat', 1, 2, 0.14), y('seed_carrot', 1, 1, 0.1)],
    yieldPerHit: [y('plant_fiber', 1, 2, 0.7)],
    respawnTicks: days(1.5),
    radius: 0,
    blocksMovement: false,
    blocksSight: false,
    skill: 'foraging',
    xpPerHit: 1,
    xpOnDeplete: 3,
    variants: 3,
    sprite: 'node_plant_fiber',
    noise: 40,
    spawnBiomes: {
      [Biome.Grassland]: 1.6,
      [Biome.Forest]: 1,
      [Biome.DeepForest]: 0.6,
      [Biome.Swamp]: 1.1,
      [Biome.Farmland]: 1.2,
      [Biome.Beach]: 0.3,
      [Biome.Rocky]: 0.4,
    },
    densityPerChunk: 12,
  },
  {
    id: 'mushroom_patch',
    name: 'Mushroom Patch',
    category: 'plant',
    maxHealth: 10,
    toolKinds: [],
    minToolTier: 1,
    wrongToolMultiplier: 1,
    yields: [y('mushroom', 2, 4)],
    yieldPerHit: [y('mushroom', 1, 1, 0.5)],
    respawnTicks: days(3),
    radius: 0,
    blocksMovement: false,
    blocksSight: false,
    skill: 'foraging',
    xpPerHit: 1,
    xpOnDeplete: 5,
    variants: 2,
    sprite: 'node_mushroom_patch',
    noise: 30,
    spawnBiomes: {
      [Biome.DeepForest]: 1.6,
      [Biome.Forest]: 0.9,
      [Biome.Swamp]: 1.4,
    },
    densityPerChunk: 4,
  },
  {
    id: 'herb_patch',
    name: 'Herb Patch',
    category: 'plant',
    maxHealth: 10,
    toolKinds: ['knife', 'sickle'],
    minToolTier: 1,
    wrongToolMultiplier: 0.6,
    // Wild onion comes up among the herbs.
    yields: [y('herb', 2, 3), y('seed_herb', 1, 1, 0.35), y('seed_onion', 1, 1, 0.16)],
    yieldPerHit: [y('herb', 1, 1, 0.4)],
    respawnTicks: days(3),
    radius: 0,
    blocksMovement: false,
    blocksSight: false,
    skill: 'foraging',
    xpPerHit: 1,
    xpOnDeplete: 6,
    variants: 2,
    sprite: 'node_herb_patch',
    noise: 30,
    spawnBiomes: {
      [Biome.Grassland]: 0.9,
      [Biome.Forest]: 1,
      [Biome.DeepForest]: 0.8,
      [Biome.Swamp]: 1.1,
      [Biome.Rocky]: 0.5,
    },
    densityPerChunk: 4,
  },

  // --- rock, ore and earth ----------------------------------------------
  {
    id: 'rock_small',
    name: 'Loose Rock',
    category: 'rock',
    maxHealth: 40,
    toolKinds: ['pickaxe'],
    minToolTier: 1,
    // Surface rock breaks apart in your hands, badly. This is where the first stone
    // and the first flint come from, and therefore where every tool starts.
    wrongToolMultiplier: 0.15,
    yields: [y('stone', 2, 4), y('flint', 1, 2, 0.5)],
    yieldPerHit: [y('stone', 1, 1, 0.3)],
    respawnTicks: days(6),
    radius: 12,
    blocksMovement: true,
    blocksSight: false,
    skill: 'mining',
    xpPerHit: 1,
    xpOnDeplete: 6,
    variants: 3,
    sprite: 'node_rock_small',
    noise: 220,
    spawnBiomes: {
      [Biome.Rocky]: 1.6,
      [Biome.Grassland]: 0.6,
      [Biome.Forest]: 0.6,
      [Biome.DeepForest]: 0.5,
      [Biome.Beach]: 0.5,
      [Biome.Swamp]: 0.3,
    },
    densityPerChunk: 8,
  },
  {
    id: 'rock_boulder',
    name: 'Boulder',
    category: 'rock',
    maxHealth: 240,
    toolKinds: ['pickaxe'],
    minToolTier: 1,
    // Solid granite. Bare hands accomplish exactly nothing.
    wrongToolMultiplier: 0,
    yields: [y('stone', 8, 14), y('flint', 1, 3, 0.6), y('coal', 1, 2, 0.15)],
    yieldPerHit: [y('stone', 1, 2, 0.4)],
    respawnTicks: -1,
    radius: 22,
    blocksMovement: true,
    blocksSight: true,
    skill: 'mining',
    xpPerHit: 2,
    xpOnDeplete: 20,
    variants: 3,
    sprite: 'node_rock_boulder',
    noise: 320,
    spawnBiomes: {
      [Biome.Rocky]: 1.8,
      [Biome.Forest]: 0.3,
      [Biome.DeepForest]: 0.3,
      [Biome.Grassland]: 0.2,
    },
    densityPerChunk: 3,
  },
  {
    id: 'ore_iron',
    name: 'Iron Vein',
    category: 'ore',
    maxHealth: 220,
    toolKinds: ['pickaxe'],
    minToolTier: 2,
    wrongToolMultiplier: 0,
    yields: [y('iron_ore', 3, 6), y('stone', 2, 4)],
    yieldPerHit: [y('iron_ore', 1, 1, 0.25)],
    respawnTicks: -1,
    radius: 18,
    blocksMovement: true,
    blocksSight: false,
    skill: 'mining',
    xpPerHit: 2,
    xpOnDeplete: 30,
    variants: 2,
    sprite: 'node_ore_iron',
    noise: 340,
    spawnBiomes: { [Biome.Rocky]: 1.5, [Biome.DeepForest]: 0.2 },
    densityPerChunk: 2.2,
  },
  {
    id: 'ore_copper',
    name: 'Copper Vein',
    category: 'ore',
    maxHealth: 180,
    toolKinds: ['pickaxe'],
    minToolTier: 2,
    wrongToolMultiplier: 0,
    yields: [y('copper_ore', 3, 5), y('stone', 2, 3)],
    yieldPerHit: [y('copper_ore', 1, 1, 0.25)],
    respawnTicks: -1,
    radius: 18,
    blocksMovement: true,
    blocksSight: false,
    skill: 'mining',
    xpPerHit: 2,
    xpOnDeplete: 26,
    variants: 2,
    sprite: 'node_ore_copper',
    noise: 340,
    spawnBiomes: { [Biome.Rocky]: 1.1, [Biome.Grassland]: 0.15 },
    densityPerChunk: 1.6,
  },
  {
    id: 'ore_coal',
    name: 'Coal Seam',
    category: 'ore',
    maxHealth: 150,
    toolKinds: ['pickaxe'],
    minToolTier: 1,
    wrongToolMultiplier: 0,
    yields: [y('coal', 3, 6)],
    yieldPerHit: [y('coal', 1, 1, 0.3)],
    respawnTicks: -1,
    radius: 16,
    blocksMovement: true,
    blocksSight: false,
    skill: 'mining',
    xpPerHit: 1,
    xpOnDeplete: 18,
    variants: 2,
    sprite: 'node_ore_coal',
    noise: 300,
    spawnBiomes: { [Biome.Rocky]: 1.3, [Biome.Forest]: 0.15 },
    densityPerChunk: 2,
  },
  {
    id: 'clay_deposit',
    name: 'Clay Deposit',
    category: 'rock',
    maxHealth: 50,
    toolKinds: ['shovel'],
    minToolTier: 1,
    wrongToolMultiplier: 0.25,
    yields: [y('clay', 3, 6)],
    yieldPerHit: [y('clay', 1, 1, 0.4)],
    respawnTicks: days(6),
    radius: 0,
    blocksMovement: false,
    blocksSight: false,
    skill: 'mining',
    xpPerHit: 1,
    xpOnDeplete: 6,
    variants: 2,
    sprite: 'node_clay_deposit',
    noise: 120,
    spawnBiomes: { [Biome.Swamp]: 1.4, [Biome.Lake]: 1.2, [Biome.Beach]: 0.8 },
    densityPerChunk: 4,
  },
  {
    id: 'sand_deposit',
    name: 'Sand Pit',
    category: 'rock',
    maxHealth: 40,
    toolKinds: ['shovel'],
    minToolTier: 1,
    wrongToolMultiplier: 0.3,
    yields: [y('sand', 4, 8), y('glass_shard', 1, 1, 0.1)],
    yieldPerHit: [y('sand', 1, 2, 0.5)],
    respawnTicks: days(4),
    radius: 0,
    blocksMovement: false,
    blocksSight: false,
    skill: 'mining',
    xpPerHit: 1,
    xpOnDeplete: 5,
    variants: 2,
    sprite: 'node_sand_deposit',
    noise: 100,
    spawnBiomes: { [Biome.Beach]: 1.8, [Biome.Lake]: 0.6, [Biome.Rocky]: 0.3 },
    densityPerChunk: 5,
  },

  // --- salvage ----------------------------------------------------------
  {
    id: 'scrap_pile',
    name: 'Scrap Pile',
    category: 'scrap',
    maxHealth: 70,
    toolKinds: ['wrench', 'hammer'],
    minToolTier: 1,
    // Pulling a pile of junk apart by hand works. This is the door into the metal age
    // for a player who has no metal to make a pickaxe with.
    wrongToolMultiplier: 0.4,
    yields: [
      y('scrap_metal', 2, 5),
      y('nail', 2, 6, 0.5),
      y('wire', 1, 2, 0.35),
      y('plastic', 1, 3, 0.4),
      y('cloth_rag', 1, 2, 0.3),
    ],
    yieldPerHit: [y('scrap_metal', 1, 1, 0.3)],
    respawnTicks: -1,
    radius: 14,
    blocksMovement: false,
    blocksSight: false,
    skill: 'mining',
    xpPerHit: 1,
    xpOnDeplete: 8,
    variants: 3,
    sprite: 'node_scrap_pile',
    noise: 260,
    spawnBiomes: {
      [Biome.Town]: 1.8,
      [Biome.Road]: 1.4,
      [Biome.Farmland]: 0.5,
      [Biome.Grassland]: 0.15,
    },
    densityPerChunk: 5,
  },
  {
    id: 'car_wreck',
    name: 'Car Wreck',
    category: 'scrap',
    maxHealth: 320,
    toolKinds: ['wrench'],
    minToolTier: 2,
    wrongToolMultiplier: 0.1,
    yields: [
      y('scrap_metal', 6, 12),
      y('rubber', 2, 4),
      y('plastic', 2, 5),
      y('glass_shard', 2, 5),
      y('wire', 2, 4, 0.7),
      y('battery', 1, 1, 0.25),
      y('fuel_canister', 1, 1, 0.12),
      y('duct_tape', 1, 1, 0.1),
    ],
    yieldPerHit: [y('scrap_metal', 1, 1, 0.2)],
    respawnTicks: -1,
    radius: 26,
    blocksMovement: true,
    blocksSight: true,
    skill: 'mining',
    xpPerHit: 2,
    xpOnDeplete: 26,
    variants: 4,
    sprite: 'node_car_wreck',
    noise: 400,
    spawnBiomes: { [Biome.Road]: 1.8, [Biome.Town]: 1.2, [Biome.Farmland]: 0.2 },
    densityPerChunk: 1.4,
  },

  // --- water ------------------------------------------------------------
  {
    id: 'water_source',
    name: 'Water',
    category: 'water',
    maxHealth: INFINITE_NODE_HEALTH,
    toolKinds: [],
    minToolTier: 1,
    wrongToolMultiplier: 1,
    yields: [],
    yieldPerHit: [y('water_dirty', 1, 1)],
    respawnTicks: -1,
    radius: 0,
    blocksMovement: false,
    blocksSight: false,
    skill: 'foraging',
    xpPerHit: 0,
    xpOnDeplete: 0,
    variants: 1,
    sprite: 'node_water_source',
    noise: 20,
    spawnBiomes: { [Biome.Lake]: 2, [Biome.Swamp]: 1.4, [Biome.Beach]: 0.6 },
    densityPerChunk: 3,
  },
  /**
   * The only thing in the world that accepts a `fishingRod`.
   *
   * `ResourceNodeDef.toolKinds` is the sole place the contract can express "this needs
   * that tool", so without this node the `fishingRod` kind, the `fishing_rod` item and
   * the whole `raw_fish` -> `cook_fish` -> `cooked_fish` chain are unreachable content.
   *
   * `wrongToolMultiplier` is 0 on purpose: fish are the one food you cannot get by
   * hand, which is what makes the rod worth the sinew. Like water it never depletes -
   * the cost is the 55% of casts that come back empty, not a finite stock.
   */
  {
    id: 'fishing_spot',
    name: 'Fishing Spot',
    category: 'water',
    maxHealth: INFINITE_NODE_HEALTH,
    toolKinds: ['fishingRod'],
    minToolTier: 1,
    wrongToolMultiplier: 0,
    yields: [],
    yieldPerHit: [y('raw_fish', 1, 1, 0.45)],
    respawnTicks: -1,
    radius: 0,
    blocksMovement: false,
    blocksSight: false,
    skill: 'foraging',
    xpPerHit: 4,
    xpOnDeplete: 0,
    variants: 1,
    sprite: 'node_fishing_spot',
    noise: 20,
    spawnBiomes: { [Biome.Lake]: 2.2, [Biome.Beach]: 1.4, [Biome.Swamp]: 0.8 },
    densityPerChunk: 1.2,
  },
];
