import type { RecipeDef, RecipeInput, RecipeOutput } from '../types';
import { seconds } from './units';

/**
 * The recipe table: the game's progression curve, expressed as a dependency graph.
 *
 * The shape of the tree is the design:
 *
 * 1. **Hand-crafting** (no station) covers fibre, sticks, stone tools, a torch, a
 *    campfire and a workbench. Nothing here needs anything you cannot pick up with
 *    your hands, which is what makes the first twenty minutes survivable at all.
 * 2. **Workbench** unlocks planks, nails and the whole iron tool set - but planks
 *    need a saw and a saw needs an ingot, so the workbench alone is not enough.
 * 3. **Furnace** is the real gate. Its kit costs dressed stone and raw clay (never
 *    fired brick, which would be circular), and its first job is turning scavenged
 *    scrap into iron. Scrap is bare-hands gatherable, so the metal age starts with
 *    scavenging rather than mining, and mining then opens up because you finally have
 *    a tier-2 pickaxe.
 * 4. **Anvil / chemistry / loom / grindstone / cooking pot** are the specialisations.
 * 5. Four recipes sets are **schematic-locked** (`unlockedByDefault: false`): steel,
 *    the crossbow, handloaded ammunition and cultured antibiotics. Those are the
 *    things you find rather than deduce.
 *
 * `fuelCost` is in the same units as `FuelProps.burnTicks` and a station's `maxFuel`,
 * i.e. simulation ticks of burn time. One log is 2 400, so a log pays for four
 * smelts at 600 each.
 */

type RecipeSpec = Pick<RecipeDef, 'id' | 'name' | 'category' | 'inputs' | 'outputs'> &
  Partial<RecipeDef>;

function recipe(spec: RecipeSpec): RecipeDef {
  return {
    tools: [],
    craftTicks: seconds(3),
    xp: { skill: 'crafting', amount: 3 },
    unlockedByDefault: true,
    ...spec,
  };
}

/** Consumed input. */
function inp(defId: string, count = 1): RecipeInput {
  return { defId, count };
}

/** Produced output. `chance` below 1 makes an output a bonus rather than a promise. */
function out(defId: string, count = 1, chance?: number): RecipeOutput {
  return chance === undefined ? { defId, count } : { defId, count, chance };
}

// ---------------------------------------------------------------------------
// Tier 0: bare hands
// ---------------------------------------------------------------------------

const HAND_RECIPES: RecipeDef[] = [
  recipe({
    id: 'craft_rope',
    name: 'Rope',
    category: 'basic',
    inputs: [inp('plant_fiber', 5)],
    outputs: [out('rope', 1)],
    craftTicks: seconds(4),
    xp: { skill: 'crafting', amount: 2 },
  }),
  recipe({
    id: 'craft_stick',
    name: 'Sticks',
    category: 'basic',
    inputs: [inp('wood_log', 1)],
    outputs: [out('stick', 4)],
    craftTicks: seconds(3),
    xp: { skill: 'crafting', amount: 1 },
  }),
  recipe({
    id: 'craft_cloth_rag',
    name: 'Cloth Rag',
    category: 'textiles',
    inputs: [inp('plant_fiber', 5)],
    outputs: [out('cloth_rag', 1)],
    craftTicks: seconds(5),
    xp: { skill: 'crafting', amount: 2 },
  }),
  recipe({
    id: 'craft_rag_from_cloth',
    name: 'Tear Cloth Into Rags',
    category: 'textiles',
    inputs: [inp('cloth', 1)],
    outputs: [out('cloth_rag', 3)],
    craftTicks: seconds(2),
    xp: { skill: 'crafting', amount: 1 },
  }),
  recipe({
    id: 'craft_stone_hatchet',
    name: 'Stone Hatchet',
    category: 'tools',
    inputs: [inp('stone', 1), inp('stick', 1), inp('plant_fiber', 3)],
    outputs: [out('stone_hatchet', 1)],
    craftTicks: seconds(8),
    xp: { skill: 'crafting', amount: 6 },
  }),
  recipe({
    id: 'craft_stone_pickaxe',
    name: 'Stone Pickaxe',
    category: 'tools',
    inputs: [inp('stone', 2), inp('stick', 1), inp('plant_fiber', 3)],
    outputs: [out('stone_pickaxe', 1)],
    craftTicks: seconds(8),
    xp: { skill: 'crafting', amount: 6 },
  }),
  recipe({
    id: 'craft_stone_knife',
    name: 'Stone Knife',
    category: 'tools',
    inputs: [inp('flint', 1), inp('stick', 1), inp('plant_fiber', 2)],
    outputs: [out('stone_knife', 1)],
    craftTicks: seconds(6),
    xp: { skill: 'crafting', amount: 5 },
  }),
  recipe({
    id: 'craft_torch',
    name: 'Torch',
    category: 'basic',
    inputs: [inp('stick', 1), inp('plant_fiber', 2), inp('resin', 1)],
    outputs: [out('torch', 1)],
    craftTicks: seconds(4),
    xp: { skill: 'crafting', amount: 2 },
  }),
  recipe({
    id: 'craft_campfire_kit',
    name: 'Campfire Kit',
    category: 'building',
    inputs: [inp('stick', 5), inp('stone', 4), inp('plant_fiber', 3)],
    outputs: [out('campfire_kit', 1)],
    craftTicks: seconds(10),
    xp: { skill: 'building', amount: 8 },
  }),
  recipe({
    id: 'craft_workbench_kit',
    name: 'Workbench Kit',
    category: 'building',
    inputs: [inp('wood_log', 5), inp('stick', 6), inp('rope', 2)],
    outputs: [out('workbench_kit', 1)],
    craftTicks: seconds(20),
    xp: { skill: 'building', amount: 15 },
  }),
  recipe({
    id: 'craft_bandage_dirty',
    name: 'Dirty Bandage',
    category: 'medical',
    inputs: [inp('cloth_rag', 1)],
    outputs: [out('bandage_dirty', 2)],
    craftTicks: seconds(3),
    xp: { skill: 'medicine', amount: 2 },
  }),
  recipe({
    id: 'craft_splint_wood',
    name: 'Wooden Splint',
    category: 'medical',
    inputs: [inp('stick', 2), inp('cloth_rag', 1)],
    outputs: [out('splint_wood', 1)],
    craftTicks: seconds(5),
    xp: { skill: 'medicine', amount: 4 },
  }),
  recipe({
    id: 'craft_disinfected_rag',
    name: 'Disinfected Rag',
    category: 'medical',
    inputs: [inp('cloth_rag', 2), inp('antiseptic', 1)],
    outputs: [out('disinfected_rag', 2)],
    craftTicks: seconds(4),
    xp: { skill: 'medicine', amount: 5 },
  }),
  recipe({
    id: 'craft_spear',
    name: 'Spear',
    category: 'weapons',
    inputs: [inp('stick', 2), inp('flint', 1), inp('plant_fiber', 3)],
    outputs: [out('spear', 1)],
    craftTicks: seconds(9),
    xp: { skill: 'crafting', amount: 7 },
  }),
  recipe({
    id: 'craft_wooden_club',
    name: 'Wooden Club',
    category: 'weapons',
    inputs: [inp('wood_log', 1)],
    outputs: [out('wooden_club', 1)],
    craftTicks: seconds(6),
    xp: { skill: 'crafting', amount: 4 },
  }),
  recipe({
    id: 'craft_throwing_rock',
    name: 'Throwing Rocks',
    category: 'weapons',
    inputs: [inp('stone', 1)],
    outputs: [out('throwing_rock', 2)],
    craftTicks: seconds(1.5),
    xp: { skill: 'crafting', amount: 1 },
  }),
];

// ---------------------------------------------------------------------------
// Workbench
// ---------------------------------------------------------------------------

const WORKBENCH_RECIPES: RecipeDef[] = [
  recipe({
    id: 'craft_wood_plank',
    name: 'Wood Planks',
    category: 'basic',
    inputs: [inp('wood_log', 1)],
    tools: ['saw'],
    outputs: [out('wood_plank', 3)],
    station: 'workbench',
    craftTicks: seconds(6),
    xp: { skill: 'crafting', amount: 3 },
  }),
  recipe({
    id: 'craft_stone_block',
    name: 'Stone Block',
    category: 'building',
    inputs: [inp('stone', 4)],
    tools: ['pickaxe'],
    outputs: [out('stone_block', 1)],
    station: 'workbench',
    craftTicks: seconds(10),
    xp: { skill: 'building', amount: 5 },
  }),
  recipe({
    id: 'craft_nail',
    name: 'Nails',
    category: 'basic',
    inputs: [inp('scrap_metal', 1)],
    tools: ['hammer'],
    outputs: [out('nail', 8)],
    station: 'workbench',
    craftTicks: seconds(6),
    xp: { skill: 'crafting', amount: 3 },
  }),
  recipe({
    id: 'craft_wire',
    name: 'Wire',
    category: 'basic',
    inputs: [inp('copper_ingot', 1)],
    tools: ['hammer'],
    outputs: [out('wire', 4)],
    station: 'workbench',
    craftTicks: seconds(8),
    xp: { skill: 'crafting', amount: 4 },
  }),
  recipe({
    id: 'craft_hammer',
    name: 'Hammer',
    category: 'tools',
    inputs: [inp('iron_ingot', 1), inp('stick', 1)],
    outputs: [out('hammer', 1)],
    station: 'workbench',
    craftTicks: seconds(12),
    requiredSkill: { id: 'crafting', level: 1 },
    xp: { skill: 'crafting', amount: 10 },
  }),
  recipe({
    id: 'craft_saw',
    name: 'Saw',
    category: 'tools',
    inputs: [inp('iron_ingot', 2), inp('stick', 2)],
    outputs: [out('saw', 1)],
    station: 'workbench',
    craftTicks: seconds(14),
    requiredSkill: { id: 'crafting', level: 1 },
    xp: { skill: 'crafting', amount: 12 },
  }),
  recipe({
    id: 'craft_iron_axe',
    name: 'Iron Axe',
    category: 'tools',
    inputs: [inp('iron_ingot', 2), inp('wood_plank', 1), inp('rope', 1)],
    tools: ['hammer'],
    outputs: [out('iron_axe', 1)],
    station: 'workbench',
    craftTicks: seconds(18),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'crafting', amount: 15 },
  }),
  recipe({
    id: 'craft_iron_pickaxe',
    name: 'Iron Pickaxe',
    category: 'tools',
    inputs: [inp('iron_ingot', 3), inp('wood_plank', 1), inp('rope', 1)],
    tools: ['hammer'],
    outputs: [out('iron_pickaxe', 1)],
    station: 'workbench',
    craftTicks: seconds(20),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'crafting', amount: 16 },
  }),
  recipe({
    id: 'craft_iron_knife',
    name: 'Iron Knife',
    category: 'tools',
    inputs: [inp('iron_ingot', 1), inp('leather', 1)],
    tools: ['hammer'],
    outputs: [out('iron_knife', 1)],
    station: 'workbench',
    craftTicks: seconds(12),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'crafting', amount: 11 },
  }),
  recipe({
    id: 'craft_shovel',
    name: 'Shovel',
    category: 'tools',
    inputs: [inp('iron_ingot', 2), inp('stick', 2)],
    tools: ['hammer'],
    outputs: [out('shovel', 1)],
    station: 'workbench',
    craftTicks: seconds(14),
    requiredSkill: { id: 'crafting', level: 1 },
    xp: { skill: 'crafting', amount: 11 },
  }),
  recipe({
    id: 'craft_hoe',
    name: 'Hoe',
    category: 'tools',
    inputs: [inp('iron_ingot', 1), inp('stick', 2)],
    tools: ['hammer'],
    outputs: [out('hoe', 1)],
    station: 'workbench',
    craftTicks: seconds(12),
    xp: { skill: 'farming', amount: 10 },
  }),
  recipe({
    id: 'craft_sickle',
    name: 'Sickle',
    category: 'tools',
    inputs: [inp('iron_ingot', 1), inp('stick', 1), inp('leather', 1)],
    tools: ['hammer'],
    outputs: [out('sickle', 1)],
    station: 'workbench',
    craftTicks: seconds(12),
    xp: { skill: 'farming', amount: 10 },
  }),
  recipe({
    id: 'craft_wrench',
    name: 'Wrench',
    category: 'tools',
    inputs: [inp('iron_ingot', 2)],
    tools: ['hammer'],
    outputs: [out('wrench', 1)],
    station: 'workbench',
    craftTicks: seconds(16),
    requiredSkill: { id: 'crafting', level: 3 },
    xp: { skill: 'crafting', amount: 13 },
  }),
  recipe({
    id: 'craft_watering_can',
    name: 'Watering Can',
    category: 'tools',
    inputs: [inp('scrap_metal', 3), inp('wire', 1)],
    tools: ['hammer'],
    outputs: [out('watering_can', 1)],
    station: 'workbench',
    craftTicks: seconds(12),
    xp: { skill: 'farming', amount: 9 },
  }),
  recipe({
    id: 'craft_fishing_rod',
    name: 'Fishing Rod',
    category: 'tools',
    inputs: [inp('stick', 2), inp('rope', 1), inp('sinew', 2), inp('nail', 1)],
    outputs: [out('fishing_rod', 1)],
    station: 'workbench',
    craftTicks: seconds(10),
    xp: { skill: 'crafting', amount: 8 },
  }),
  recipe({
    id: 'craft_nail_bat',
    name: 'Nail Bat',
    category: 'weapons',
    inputs: [inp('wooden_club', 1), inp('nail', 10)],
    tools: ['hammer'],
    outputs: [out('nail_bat', 1)],
    station: 'workbench',
    craftTicks: seconds(10),
    requiredSkill: { id: 'melee', level: 1 },
    xp: { skill: 'crafting', amount: 8 },
  }),
  recipe({
    id: 'craft_sledgehammer',
    name: 'Sledgehammer',
    category: 'weapons',
    inputs: [inp('iron_ingot', 4), inp('wood_plank', 1), inp('rope', 1)],
    tools: ['hammer'],
    outputs: [out('sledgehammer', 1)],
    station: 'workbench',
    craftTicks: seconds(24),
    requiredSkill: { id: 'crafting', level: 3 },
    xp: { skill: 'crafting', amount: 18 },
  }),
  recipe({
    id: 'craft_pitchfork',
    name: 'Pitchfork',
    category: 'weapons',
    inputs: [inp('iron_ingot', 2), inp('stick', 2), inp('rope', 1)],
    tools: ['hammer'],
    outputs: [out('pitchfork', 1)],
    station: 'workbench',
    craftTicks: seconds(16),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'crafting', amount: 12 },
  }),
  recipe({
    id: 'craft_hunting_bow',
    name: 'Hunting Bow',
    category: 'weapons',
    inputs: [inp('stick', 3), inp('rope', 1), inp('sinew', 3)],
    tools: ['knife'],
    outputs: [out('hunting_bow', 1)],
    station: 'workbench',
    craftTicks: seconds(20),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'ranged', amount: 14 },
  }),
  recipe({
    id: 'craft_arrow_wooden',
    name: 'Wooden Arrows',
    category: 'ammo',
    inputs: [inp('stick', 3), inp('feather', 3), inp('flint', 2)],
    tools: ['knife'],
    outputs: [out('arrow_wooden', 6)],
    station: 'workbench',
    craftTicks: seconds(8),
    xp: { skill: 'ranged', amount: 4 },
  }),
  recipe({
    id: 'craft_arrow_iron',
    name: 'Iron Arrows',
    category: 'ammo',
    inputs: [inp('stick', 3), inp('feather', 3), inp('iron_ingot', 1)],
    tools: ['knife'],
    outputs: [out('arrow_iron', 6)],
    station: 'workbench',
    craftTicks: seconds(10),
    requiredSkill: { id: 'ranged', level: 3 },
    xp: { skill: 'ranged', amount: 8 },
  }),
  recipe({
    id: 'craft_crossbow',
    name: 'Crossbow',
    category: 'weapons',
    inputs: [inp('wood_plank', 3), inp('iron_ingot', 2), inp('rope', 1), inp('wire', 2)],
    tools: ['hammer', 'saw'],
    outputs: [out('crossbow', 1)],
    station: 'workbench',
    craftTicks: seconds(40),
    requiredSkill: { id: 'crafting', level: 4 },
    xp: { skill: 'ranged', amount: 30 },
    unlockedByDefault: false,
  }),
  recipe({
    id: 'craft_bolt',
    name: 'Crossbow Bolts',
    category: 'ammo',
    inputs: [inp('wood_plank', 1), inp('iron_ingot', 1), inp('feather', 2)],
    tools: ['knife'],
    outputs: [out('bolt', 8)],
    station: 'workbench',
    craftTicks: seconds(10),
    requiredSkill: { id: 'ranged', level: 3 },
    xp: { skill: 'ranged', amount: 8 },
  }),
  recipe({
    id: 'craft_splint_medical',
    name: 'Medical Splint',
    category: 'medical',
    inputs: [inp('wood_plank', 1), inp('cloth', 2), inp('duct_tape', 1)],
    outputs: [out('splint_medical', 1)],
    station: 'workbench',
    craftTicks: seconds(10),
    requiredSkill: { id: 'medicine', level: 2 },
    xp: { skill: 'medicine', amount: 10 },
  }),
  recipe({
    id: 'craft_suture_kit',
    name: 'Suture Kit',
    category: 'medical',
    inputs: [inp('sinew', 3), inp('wire', 1), inp('antiseptic', 1), inp('cloth', 1)],
    outputs: [out('suture_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(16),
    requiredSkill: { id: 'medicine', level: 4 },
    xp: { skill: 'medicine', amount: 18 },
  }),
  recipe({
    id: 'craft_lockpick',
    name: 'Lockpick',
    category: 'tools',
    inputs: [inp('wire', 2), inp('scrap_metal', 1)],
    outputs: [out('lockpick', 1)],
    station: 'workbench',
    craftTicks: seconds(8),
    requiredSkill: { id: 'crafting', level: 3 },
    xp: { skill: 'crafting', amount: 8 },
  }),
  recipe({
    id: 'craft_lantern',
    name: 'Lantern',
    category: 'building',
    inputs: [inp('scrap_metal', 2), inp('glass', 1), inp('wire', 1), inp('resin', 2)],
    tools: ['hammer'],
    outputs: [out('lantern', 1)],
    station: 'workbench',
    craftTicks: seconds(14),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'crafting', amount: 12 },
  }),
  recipe({
    id: 'craft_storage_box_kit',
    name: 'Storage Box Kit',
    category: 'building',
    inputs: [inp('wood_plank', 6), inp('nail', 8)],
    tools: ['hammer', 'saw'],
    outputs: [out('storage_box_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(16),
    xp: { skill: 'building', amount: 12 },
  }),
  recipe({
    id: 'craft_bed_kit',
    name: 'Bed Kit',
    category: 'building',
    inputs: [inp('wood_plank', 8), inp('cloth', 4), inp('nail', 12)],
    tools: ['hammer', 'saw'],
    outputs: [out('bed_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(30),
    requiredSkill: { id: 'building', level: 2 },
    xp: { skill: 'building', amount: 20 },
  }),
  recipe({
    id: 'craft_furnace_kit',
    name: 'Furnace Kit',
    category: 'building',
    inputs: [inp('stone_block', 10), inp('clay', 8)],
    outputs: [out('furnace_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(45),
    requiredSkill: { id: 'building', level: 2 },
    xp: { skill: 'building', amount: 30 },
  }),
  recipe({
    id: 'craft_anvil_kit',
    name: 'Anvil Kit',
    category: 'building',
    inputs: [inp('iron_ingot', 8), inp('stone_block', 2)],
    tools: ['hammer'],
    outputs: [out('anvil_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(60),
    requiredSkill: { id: 'crafting', level: 4 },
    xp: { skill: 'building', amount: 40 },
  }),
  recipe({
    id: 'craft_loom_kit',
    name: 'Loom Kit',
    category: 'building',
    inputs: [inp('wood_plank', 8), inp('stick', 4), inp('rope', 3)],
    tools: ['saw'],
    outputs: [out('loom_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(30),
    requiredSkill: { id: 'building', level: 1 },
    xp: { skill: 'building', amount: 22 },
  }),
  recipe({
    id: 'craft_cooking_pot_kit',
    name: 'Cooking Pot',
    category: 'building',
    inputs: [inp('iron_ingot', 3), inp('stick', 3), inp('wire', 1)],
    tools: ['hammer'],
    outputs: [out('cooking_pot_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(22),
    requiredSkill: { id: 'cooking', level: 1 },
    xp: { skill: 'cooking', amount: 18 },
  }),
  recipe({
    id: 'craft_grindstone_kit',
    name: 'Grindstone Kit',
    category: 'building',
    inputs: [inp('stone_block', 4), inp('wood_plank', 2), inp('iron_ingot', 1)],
    tools: ['hammer'],
    outputs: [out('grindstone_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(30),
    requiredSkill: { id: 'building', level: 2 },
    xp: { skill: 'building', amount: 24 },
  }),
  recipe({
    id: 'craft_water_barrel_kit',
    name: 'Water Barrel Kit',
    category: 'building',
    inputs: [inp('wood_plank', 8), inp('nail', 6), inp('resin', 3)],
    tools: ['hammer', 'saw'],
    outputs: [out('water_barrel_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(24),
    requiredSkill: { id: 'building', level: 1 },
    xp: { skill: 'building', amount: 18 },
  }),
  recipe({
    id: 'craft_farm_plot_kit',
    name: 'Farm Plot Kit',
    category: 'farming',
    inputs: [inp('wood_plank', 4), inp('rope', 2)],
    outputs: [out('farm_plot_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(14),
    xp: { skill: 'farming', amount: 12 },
  }),
  recipe({
    id: 'craft_chemistry_bench_kit',
    name: 'Chemistry Bench Kit',
    category: 'building',
    // The fired brick is what makes `fire_clay_brick` worth its fuel: the bench runs a
    // burner, and a burner needs a lining that does not spall. Both this and the glass
    // are furnace-gated already, so no new dependency cycle appears.
    inputs: [
      inp('wood_plank', 6),
      inp('glass', 3),
      inp('scrap_metal', 3),
      inp('wire', 2),
      inp('clay_brick', 6),
    ],
    tools: ['hammer', 'saw'],
    outputs: [out('chemistry_bench_kit', 1)],
    station: 'workbench',
    craftTicks: seconds(40),
    requiredSkill: { id: 'crafting', level: 4 },
    xp: { skill: 'crafting', amount: 30 },
  }),
];

// ---------------------------------------------------------------------------
// Furnace (smelting)
// ---------------------------------------------------------------------------

const FURNACE_RECIPES: RecipeDef[] = [
  recipe({
    id: 'smelt_charcoal',
    name: 'Charcoal',
    category: 'smelting',
    inputs: [inp('wood_log', 3)],
    outputs: [out('charcoal', 4)],
    station: 'furnace',
    craftTicks: seconds(30),
    fuelCost: 400,
    requiresHeat: true,
    xp: { skill: 'crafting', amount: 5 },
  }),
  recipe({
    id: 'smelt_iron_ingot',
    name: 'Iron Ingot',
    category: 'smelting',
    inputs: [inp('iron_ore', 2)],
    outputs: [out('iron_ingot', 1)],
    station: 'furnace',
    craftTicks: seconds(25),
    fuelCost: 600,
    requiresHeat: true,
    xp: { skill: 'crafting', amount: 8 },
  }),
  recipe({
    id: 'smelt_scrap_to_iron',
    name: 'Re-smelt Scrap',
    category: 'smelting',
    inputs: [inp('scrap_metal', 3)],
    outputs: [out('iron_ingot', 1)],
    station: 'furnace',
    craftTicks: seconds(25),
    fuelCost: 700,
    requiresHeat: true,
    xp: { skill: 'crafting', amount: 7 },
  }),
  recipe({
    id: 'smelt_copper_ingot',
    name: 'Copper Ingot',
    category: 'smelting',
    inputs: [inp('copper_ore', 2)],
    outputs: [out('copper_ingot', 1)],
    station: 'furnace',
    craftTicks: seconds(22),
    fuelCost: 500,
    requiresHeat: true,
    xp: { skill: 'crafting', amount: 7 },
  }),
  recipe({
    id: 'smelt_glass',
    name: 'Glass Pane',
    category: 'smelting',
    inputs: [inp('sand', 3)],
    outputs: [out('glass', 1)],
    station: 'furnace',
    craftTicks: seconds(20),
    fuelCost: 800,
    requiresHeat: true,
    xp: { skill: 'crafting', amount: 6 },
  }),
  recipe({
    id: 'smelt_glass_from_shards',
    name: 'Recast Glass',
    category: 'smelting',
    inputs: [inp('glass_shard', 5)],
    outputs: [out('glass', 1)],
    station: 'furnace',
    craftTicks: seconds(16),
    fuelCost: 600,
    requiresHeat: true,
    xp: { skill: 'crafting', amount: 5 },
  }),
  recipe({
    id: 'fire_clay_brick',
    name: 'Clay Brick',
    category: 'smelting',
    inputs: [inp('clay', 2)],
    outputs: [out('clay_brick', 2)],
    station: 'furnace',
    craftTicks: seconds(18),
    fuelCost: 500,
    requiresHeat: true,
    xp: { skill: 'building', amount: 5 },
  }),
  recipe({
    id: 'smelt_steel_ingot',
    name: 'Steel Ingot',
    category: 'smelting',
    inputs: [inp('iron_ingot', 2), inp('charcoal', 3)],
    outputs: [out('steel_ingot', 1)],
    station: 'furnace',
    craftTicks: seconds(50),
    fuelCost: 1800,
    requiresHeat: true,
    requiredSkill: { id: 'crafting', level: 5 },
    xp: { skill: 'crafting', amount: 25 },
    unlockedByDefault: false,
  }),
];

// ---------------------------------------------------------------------------
// Anvil (forging)
// ---------------------------------------------------------------------------

const ANVIL_RECIPES: RecipeDef[] = [
  recipe({
    id: 'forge_iron_sword',
    name: 'Iron Sword',
    category: 'weapons',
    inputs: [inp('iron_ingot', 4), inp('leather', 2), inp('wood_plank', 1)],
    tools: ['hammer'],
    outputs: [out('iron_sword', 1)],
    station: 'anvil',
    craftTicks: seconds(45),
    requiredSkill: { id: 'crafting', level: 5 },
    xp: { skill: 'crafting', amount: 28 },
  }),
  recipe({
    id: 'forge_machete',
    name: 'Machete',
    category: 'weapons',
    inputs: [inp('iron_ingot', 2), inp('leather', 1)],
    tools: ['hammer'],
    outputs: [out('machete', 1)],
    station: 'anvil',
    craftTicks: seconds(30),
    requiredSkill: { id: 'crafting', level: 3 },
    xp: { skill: 'crafting', amount: 20 },
  }),
  recipe({
    id: 'forge_crowbar',
    name: 'Crowbar',
    category: 'tools',
    inputs: [inp('iron_ingot', 3)],
    tools: ['hammer'],
    outputs: [out('crowbar', 1)],
    station: 'anvil',
    craftTicks: seconds(24),
    requiredSkill: { id: 'crafting', level: 3 },
    xp: { skill: 'crafting', amount: 16 },
  }),
  recipe({
    id: 'forge_steel_axe',
    name: 'Steel Axe',
    category: 'tools',
    inputs: [inp('steel_ingot', 3), inp('wood_plank', 1), inp('leather', 1)],
    tools: ['hammer'],
    outputs: [out('steel_axe', 1)],
    station: 'anvil',
    craftTicks: seconds(60),
    requiredSkill: { id: 'crafting', level: 6 },
    xp: { skill: 'crafting', amount: 40 },
    unlockedByDefault: false,
  }),
  recipe({
    id: 'forge_steel_pickaxe',
    name: 'Steel Pickaxe',
    category: 'tools',
    inputs: [inp('steel_ingot', 3), inp('wood_plank', 1), inp('leather', 1)],
    tools: ['hammer'],
    outputs: [out('steel_pickaxe', 1)],
    station: 'anvil',
    craftTicks: seconds(60),
    requiredSkill: { id: 'crafting', level: 6 },
    xp: { skill: 'crafting', amount: 40 },
    unlockedByDefault: false,
  }),
  recipe({
    id: 'forge_ammo_casing',
    name: 'Cartridge Casings',
    category: 'ammo',
    inputs: [inp('copper_ingot', 1)],
    tools: ['hammer'],
    outputs: [out('ammo_casing', 8)],
    station: 'anvil',
    craftTicks: seconds(16),
    requiredSkill: { id: 'crafting', level: 4 },
    xp: { skill: 'crafting', amount: 10 },
  }),
  recipe({
    id: 'forge_ammo_9mm',
    name: '9mm Rounds',
    category: 'ammo',
    inputs: [inp('ammo_casing', 8), inp('gunpowder', 2), inp('scrap_metal', 1)],
    outputs: [out('ammo_9mm', 8)],
    station: 'anvil',
    craftTicks: seconds(24),
    requiredSkill: { id: 'ranged', level: 4 },
    xp: { skill: 'ranged', amount: 14 },
    unlockedByDefault: false,
  }),
  recipe({
    id: 'forge_ammo_308',
    name: '.308 Rounds',
    category: 'ammo',
    inputs: [inp('ammo_casing', 6), inp('gunpowder', 3), inp('scrap_metal', 2)],
    outputs: [out('ammo_308', 6)],
    station: 'anvil',
    craftTicks: seconds(30),
    requiredSkill: { id: 'ranged', level: 5 },
    xp: { skill: 'ranged', amount: 18 },
    unlockedByDefault: false,
  }),
  recipe({
    id: 'forge_ammo_shell',
    name: 'Shotgun Shells',
    category: 'ammo',
    inputs: [inp('ammo_casing', 6), inp('gunpowder', 3), inp('scrap_metal', 2), inp('plastic', 2)],
    outputs: [out('ammo_shell', 6)],
    station: 'anvil',
    craftTicks: seconds(28),
    requiredSkill: { id: 'ranged', level: 4 },
    xp: { skill: 'ranged', amount: 16 },
    unlockedByDefault: false,
  }),
];

// ---------------------------------------------------------------------------
// Cooking: campfire, cooking pot, grindstone
// ---------------------------------------------------------------------------

const COOKING_RECIPES: RecipeDef[] = [
  recipe({
    id: 'cook_meat',
    name: 'Cooked Meat',
    category: 'cooking',
    inputs: [inp('raw_meat', 1)],
    outputs: [out('cooked_meat', 1)],
    station: 'campfire',
    craftTicks: seconds(12),
    fuelCost: 200,
    requiresHeat: true,
    xp: { skill: 'cooking', amount: 4 },
  }),
  recipe({
    id: 'cook_fish',
    name: 'Cooked Fish',
    category: 'cooking',
    inputs: [inp('raw_fish', 1)],
    outputs: [out('cooked_fish', 1)],
    station: 'campfire',
    craftTicks: seconds(10),
    fuelCost: 180,
    requiresHeat: true,
    xp: { skill: 'cooking', amount: 4 },
  }),
  recipe({
    id: 'bake_potato',
    name: 'Baked Potato',
    category: 'cooking',
    inputs: [inp('potato', 1)],
    outputs: [out('baked_potato', 1)],
    station: 'campfire',
    craftTicks: seconds(10),
    fuelCost: 150,
    requiresHeat: true,
    xp: { skill: 'cooking', amount: 3 },
  }),
  recipe({
    id: 'boil_water',
    name: 'Boil Water',
    category: 'cooking',
    inputs: [inp('water_dirty', 1)],
    outputs: [out('water_clean', 1)],
    station: 'campfire',
    craftTicks: seconds(10),
    fuelCost: 200,
    requiresHeat: true,
    xp: { skill: 'cooking', amount: 2 },
  }),
  recipe({
    id: 'bake_bread',
    name: 'Bread',
    category: 'cooking',
    inputs: [inp('dough', 1)],
    outputs: [out('bread', 1)],
    station: 'campfire',
    craftTicks: seconds(18),
    fuelCost: 300,
    requiresHeat: true,
    requiredSkill: { id: 'cooking', level: 2 },
    xp: { skill: 'cooking', amount: 8 },
  }),
  recipe({
    id: 'make_jerky',
    name: 'Jerky',
    category: 'cooking',
    inputs: [inp('raw_meat', 2)],
    tools: ['knife'],
    outputs: [out('jerky', 3)],
    station: 'campfire',
    craftTicks: seconds(60),
    fuelCost: 900,
    requiresHeat: true,
    requiredSkill: { id: 'cooking', level: 3 },
    xp: { skill: 'cooking', amount: 12 },
  }),
  recipe({
    id: 'make_dough',
    name: 'Dough',
    category: 'cooking',
    inputs: [inp('flour', 2), inp('water_clean', 1)],
    outputs: [out('dough', 2)],
    station: 'cookingPot',
    craftTicks: seconds(8),
    xp: { skill: 'cooking', amount: 4 },
  }),
  recipe({
    id: 'cook_soup_vegetable',
    name: 'Vegetable Soup',
    category: 'cooking',
    inputs: [inp('carrot', 2), inp('cabbage', 1), inp('potato', 1), inp('water_clean', 2)],
    outputs: [out('soup_vegetable', 2)],
    station: 'cookingPot',
    craftTicks: seconds(25),
    fuelCost: 400,
    requiresHeat: true,
    requiredSkill: { id: 'cooking', level: 2 },
    xp: { skill: 'cooking', amount: 12 },
  }),
  recipe({
    id: 'cook_stew_meat',
    name: 'Meat Stew',
    category: 'cooking',
    inputs: [inp('raw_meat', 2), inp('carrot', 2), inp('onion', 1), inp('water_clean', 2)],
    outputs: [out('stew_meat', 2)],
    station: 'cookingPot',
    craftTicks: seconds(35),
    fuelCost: 600,
    requiresHeat: true,
    requiredSkill: { id: 'cooking', level: 4 },
    xp: { skill: 'cooking', amount: 20 },
  }),
  recipe({
    id: 'brew_tea_herbal',
    name: 'Herbal Tea',
    category: 'cooking',
    inputs: [inp('herb', 2), inp('water_clean', 1)],
    outputs: [out('tea_herbal', 2)],
    station: 'cookingPot',
    craftTicks: seconds(14),
    fuelCost: 200,
    requiresHeat: true,
    xp: { skill: 'cooking', amount: 6 },
  }),
  recipe({
    id: 'boil_water_batch',
    name: 'Boil Water (Batch)',
    category: 'cooking',
    inputs: [inp('water_dirty', 4)],
    outputs: [out('water_clean', 4)],
    station: 'cookingPot',
    craftTicks: seconds(20),
    fuelCost: 500,
    requiresHeat: true,
    xp: { skill: 'cooking', amount: 6 },
  }),
  recipe({
    id: 'mill_flour',
    name: 'Flour',
    category: 'cooking',
    inputs: [inp('wheat', 3)],
    outputs: [out('flour', 2)],
    station: 'grindstone',
    craftTicks: seconds(14),
    xp: { skill: 'cooking', amount: 5 },
  }),
  recipe({
    id: 'mill_bone_meal',
    name: 'Bone Meal',
    category: 'farming',
    inputs: [inp('bone', 3)],
    outputs: [out('fertilizer', 2)],
    station: 'grindstone',
    craftTicks: seconds(14),
    xp: { skill: 'farming', amount: 6 },
  }),
];

// ---------------------------------------------------------------------------
// Chemistry
// ---------------------------------------------------------------------------

const CHEMISTRY_RECIPES: RecipeDef[] = [
  recipe({
    id: 'distill_moonshine',
    name: 'Moonshine (Fruit)',
    category: 'cooking',
    inputs: [inp('berry', 8), inp('water_clean', 2)],
    outputs: [out('alcohol_moonshine', 2)],
    station: 'chemistry',
    craftTicks: seconds(45),
    fuelCost: 700,
    requiresHeat: true,
    requiredSkill: { id: 'cooking', level: 2 },
    xp: { skill: 'cooking', amount: 14 },
  }),
  recipe({
    id: 'distill_moonshine_corn',
    name: 'Moonshine (Corn)',
    category: 'cooking',
    inputs: [inp('corn', 4), inp('water_clean', 2)],
    outputs: [out('alcohol_moonshine', 3)],
    station: 'chemistry',
    craftTicks: seconds(45),
    fuelCost: 700,
    requiresHeat: true,
    requiredSkill: { id: 'cooking', level: 3 },
    xp: { skill: 'cooking', amount: 16 },
  }),
  recipe({
    id: 'make_antiseptic',
    name: 'Antiseptic',
    category: 'medical',
    inputs: [inp('herb', 3), inp('alcohol_moonshine', 1)],
    outputs: [out('antiseptic', 2)],
    station: 'chemistry',
    craftTicks: seconds(20),
    requiredSkill: { id: 'medicine', level: 2 },
    xp: { skill: 'medicine', amount: 12 },
  }),
  recipe({
    id: 'make_bandage_sterile',
    name: 'Sterile Dressing',
    category: 'medical',
    inputs: [inp('bandage_clean', 2), inp('antiseptic', 1)],
    outputs: [out('bandage_sterile', 2)],
    station: 'chemistry',
    craftTicks: seconds(16),
    requiredSkill: { id: 'medicine', level: 3 },
    xp: { skill: 'medicine', amount: 12 },
  }),
  recipe({
    id: 'make_antibiotics',
    name: 'Antibiotics',
    category: 'medical',
    inputs: [inp('mushroom', 4), inp('herb', 3), inp('water_clean', 2), inp('glass', 1)],
    outputs: [out('antibiotics', 2)],
    station: 'chemistry',
    craftTicks: seconds(90),
    requiredSkill: { id: 'medicine', level: 5 },
    xp: { skill: 'medicine', amount: 35 },
    unlockedByDefault: false,
  }),
  recipe({
    id: 'make_first_aid_kit',
    name: 'First Aid Kit',
    category: 'medical',
    inputs: [
      inp('bandage_sterile', 2),
      inp('antiseptic', 1),
      inp('painkiller', 1),
      inp('splint_medical', 1),
    ],
    outputs: [out('first_aid_kit', 1)],
    station: 'chemistry',
    craftTicks: seconds(40),
    requiredSkill: { id: 'medicine', level: 5 },
    xp: { skill: 'medicine', amount: 30 },
    unlockedByDefault: false,
  }),
  recipe({
    id: 'make_painkiller',
    name: 'Painkillers',
    category: 'medical',
    inputs: [inp('herb', 4), inp('bark', 4)],
    outputs: [out('painkiller', 2)],
    station: 'chemistry',
    craftTicks: seconds(24),
    requiredSkill: { id: 'medicine', level: 3 },
    xp: { skill: 'medicine', amount: 14 },
  }),
  recipe({
    id: 'make_gunpowder',
    name: 'Gunpowder',
    category: 'ammo',
    inputs: [inp('charcoal', 3), inp('coal', 1), inp('bone', 2)],
    outputs: [out('gunpowder', 2)],
    station: 'chemistry',
    craftTicks: seconds(30),
    requiredSkill: { id: 'crafting', level: 4 },
    xp: { skill: 'crafting', amount: 16 },
  }),
  recipe({
    id: 'make_molotov',
    name: 'Molotov Cocktail',
    category: 'weapons',
    inputs: [inp('glass', 1), inp('cloth_rag', 1), inp('alcohol_moonshine', 1)],
    outputs: [out('molotov', 1)],
    station: 'chemistry',
    craftTicks: seconds(14),
    requiredSkill: { id: 'crafting', level: 3 },
    xp: { skill: 'crafting', amount: 10 },
  }),
  recipe({
    id: 'make_compost',
    name: 'Compost',
    category: 'farming',
    inputs: [inp('plant_fiber', 10), inp('mushroom', 2), inp('water_dirty', 1)],
    outputs: [out('compost', 2)],
    station: 'chemistry',
    craftTicks: seconds(24),
    xp: { skill: 'farming', amount: 8 },
  }),
  recipe({
    id: 'make_fertilizer',
    name: 'Fertilizer',
    category: 'farming',
    inputs: [inp('compost', 2), inp('bone', 1)],
    outputs: [out('fertilizer', 3)],
    station: 'chemistry',
    craftTicks: seconds(18),
    requiredSkill: { id: 'farming', level: 2 },
    xp: { skill: 'farming', amount: 10 },
  }),
];

// ---------------------------------------------------------------------------
// Loom (textiles and leather)
// ---------------------------------------------------------------------------

const LOOM_RECIPES: RecipeDef[] = [
  recipe({
    id: 'weave_cloth_fiber',
    name: 'Cloth (from Fiber)',
    category: 'textiles',
    inputs: [inp('plant_fiber', 8)],
    outputs: [out('cloth', 1)],
    station: 'loom',
    craftTicks: seconds(14),
    xp: { skill: 'crafting', amount: 5 },
  }),
  recipe({
    id: 'weave_cloth_rags',
    name: 'Cloth (from Rags)',
    category: 'textiles',
    inputs: [inp('cloth_rag', 4)],
    outputs: [out('cloth', 1)],
    station: 'loom',
    craftTicks: seconds(10),
    xp: { skill: 'crafting', amount: 4 },
  }),
  recipe({
    id: 'tan_leather',
    name: 'Tan Leather',
    category: 'textiles',
    inputs: [inp('hide', 1), inp('bark', 3), inp('water_clean', 1)],
    tools: ['knife'],
    outputs: [out('leather', 2)],
    station: 'loom',
    craftTicks: seconds(30),
    requiredSkill: { id: 'crafting', level: 1 },
    xp: { skill: 'crafting', amount: 10 },
  }),
  recipe({
    id: 'make_bandage_clean',
    name: 'Clean Bandage',
    category: 'medical',
    inputs: [inp('cloth', 1), inp('water_clean', 1)],
    outputs: [out('bandage_clean', 3)],
    station: 'loom',
    craftTicks: seconds(10),
    requiredSkill: { id: 'medicine', level: 1 },
    xp: { skill: 'medicine', amount: 6 },
  }),
  recipe({
    id: 'sew_cloth_shirt',
    name: 'Cloth Shirt',
    category: 'armor',
    inputs: [inp('cloth', 4), inp('plant_fiber', 4)],
    outputs: [out('cloth_shirt', 1)],
    station: 'loom',
    craftTicks: seconds(20),
    xp: { skill: 'crafting', amount: 10 },
  }),
  recipe({
    id: 'sew_cloth_pants',
    name: 'Cloth Pants',
    category: 'armor',
    inputs: [inp('cloth', 4), inp('plant_fiber', 4)],
    outputs: [out('cloth_pants', 1)],
    station: 'loom',
    craftTicks: seconds(20),
    xp: { skill: 'crafting', amount: 10 },
  }),
  recipe({
    id: 'sew_leather_cap',
    name: 'Leather Cap',
    category: 'armor',
    inputs: [inp('leather', 2), inp('cloth', 1)],
    outputs: [out('leather_cap', 1)],
    station: 'loom',
    craftTicks: seconds(18),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'crafting', amount: 12 },
  }),
  recipe({
    id: 'sew_leather_gloves',
    name: 'Leather Gloves',
    category: 'armor',
    inputs: [inp('leather', 2), inp('sinew', 1)],
    outputs: [out('leather_gloves', 1)],
    station: 'loom',
    craftTicks: seconds(16),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'crafting', amount: 12 },
  }),
  recipe({
    id: 'sew_leather_pants',
    name: 'Leather Pants',
    category: 'armor',
    inputs: [inp('leather', 6), inp('sinew', 2)],
    outputs: [out('leather_pants', 1)],
    station: 'loom',
    craftTicks: seconds(32),
    requiredSkill: { id: 'crafting', level: 4 },
    xp: { skill: 'crafting', amount: 22 },
  }),
  recipe({
    id: 'sew_leather_jacket',
    name: 'Leather Jacket',
    category: 'armor',
    inputs: [inp('leather', 8), inp('cloth', 2), inp('sinew', 3)],
    outputs: [out('leather_jacket', 1)],
    station: 'loom',
    craftTicks: seconds(45),
    requiredSkill: { id: 'crafting', level: 5 },
    xp: { skill: 'crafting', amount: 30 },
  }),
  recipe({
    id: 'sew_backpack_small',
    name: 'Small Backpack',
    category: 'armor',
    inputs: [inp('cloth', 5), inp('rope', 2), inp('leather', 1)],
    outputs: [out('backpack_small', 1)],
    station: 'loom',
    craftTicks: seconds(30),
    requiredSkill: { id: 'crafting', level: 2 },
    xp: { skill: 'crafting', amount: 20 },
  }),
  recipe({
    id: 'sew_backpack_large',
    name: 'Large Backpack',
    category: 'armor',
    // Rubber is the load-bearing half of a strap that carries 30 kg; it is also the
    // only recipe that consumes it, which is what keeps a tyre wall worth cutting.
    inputs: [
      inp('leather', 6),
      inp('cloth', 3),
      inp('rope', 3),
      inp('duct_tape', 1),
      inp('rubber', 2),
    ],
    outputs: [out('backpack_large', 1)],
    station: 'loom',
    craftTicks: seconds(50),
    requiredSkill: { id: 'crafting', level: 4 },
    xp: { skill: 'crafting', amount: 35 },
  }),
  recipe({
    id: 'sew_tool_belt',
    name: 'Tool Belt',
    category: 'armor',
    inputs: [inp('leather', 3), inp('rope', 1)],
    outputs: [out('tool_belt', 1)],
    station: 'loom',
    craftTicks: seconds(18),
    requiredSkill: { id: 'crafting', level: 1 },
    xp: { skill: 'crafting', amount: 12 },
  }),
];

// ---------------------------------------------------------------------------

/** Every recipe in the game. */
export const RECIPE_DEFS: readonly RecipeDef[] = [
  ...HAND_RECIPES,
  ...WORKBENCH_RECIPES,
  ...FURNACE_RECIPES,
  ...ANVIL_RECIPES,
  ...COOKING_RECIPES,
  ...CHEMISTRY_RECIPES,
  ...LOOM_RECIPES,
];
