import type { ItemAmount, StructureDef } from '../types';
import { seconds } from './units';

/**
 * The buildable table.
 *
 * Design rules encoded in the numbers:
 *
 * - **Material tiers really matter.** A wood wall is 260 HP and takes 1.1x damage
 *   from zombies; the same wall in stone is 750 HP at 0.55x, and in metal 1400 HP at
 *   0.3x. That is a ~15x effective difference between the first wall you can afford
 *   and the last one, which is what makes rebuilding a base in stone worth a week.
 * - **Nothing on the tier-0 path needs nails.** `wall_wood_frame`, `fence_wood` and
 *   `bed_bedroll` are all sticks, fibre and cloth, so a first night's shelter does not
 *   require having found a furnace first.
 * - **Stations arrive as kits** (`cost` is the kit item) because they are objects you
 *   carry and place. Walls, floors and doors are paid for in raw resources straight
 *   from the build menu, which is why they have no item form at all.
 * - **`station.maxFuel` and `light.fuelPerTick` are in fuel ticks**, the same unit as
 *   `FuelProps.burnTicks` and `RecipeDef.fuelCost`. A furnace holds 24 000 - ten logs -
 *   and a smelt costs 600.
 *
 * Known contract gap: `StructureDef` has no "holds liquid" sub-state, so
 * `water_barrel` and `well` are declared as small containers and the drinking / can
 * filling interaction resolves them by def id.
 */

type StructureSpec = Pick<
  StructureDef,
  'id' | 'name' | 'description' | 'category' | 'maxHealth' | 'buildTicks' | 'cost' | 'xp'
> &
  Partial<StructureDef>;

function structure(spec: StructureSpec): StructureDef {
  return {
    width: 1,
    height: 1,
    refundRatio: 0.5,
    blocksMovement: false,
    blocksSight: false,
    stacksOver: [],
    requiresSupport: false,
    placeOn: 'ground',
    destructible: true,
    zombieDamageMultiplier: 1,
    sprite: `structure_${spec.id}`,
    sortOrder: 0,
    ...spec,
  };
}

function cost(...amounts: [string, number][]): ItemAmount[] {
  return amounts.map(([defId, count]) => ({ defId, count }));
}

/**
 * Authoring order is build-menu order; `sortOrder` is derived from it at the bottom of
 * the file so inserting a structure never means renumbering the rest.
 */
const AUTHORED: StructureDef[] = [
  // --- foundations and floors -------------------------------------------
  structure({
    id: 'foundation_wood',
    name: 'Wood Foundation',
    description: 'Logs laid and levelled. Everything else needs something to sit on.',
    category: 'foundation',
    maxHealth: 220,
    buildTicks: seconds(6),
    cost: cost(['wood_log', 3], ['stick', 2]),
    refundRatio: 0.6,
    xp: 4,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'foundation_stone',
    name: 'Stone Foundation',
    description: 'Dressed block bedded in clay. Slow, heavy, and it does not rot.',
    category: 'foundation',
    maxHealth: 700,
    buildTicks: seconds(20),
    cost: cost(['stone_block', 4], ['clay', 2]),
    refundRatio: 0.6,
    requiredSkill: { id: 'building', level: 2 },
    xp: 12,
    zombieDamageMultiplier: 0.5,
  }),
  structure({
    id: 'floor_wood',
    name: 'Wood Floor',
    description: 'Planks over the frame. Keeps the mud out and the noise up.',
    category: 'floor',
    maxHealth: 130,
    buildTicks: seconds(5),
    cost: cost(['wood_plank', 2], ['nail', 2]),
    placeOn: 'any',
    stacksOver: ['foundation'],
    xp: 3,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'floor_stone',
    name: 'Stone Floor',
    description: 'Flagstones. Silent underfoot, which matters more than it sounds.',
    category: 'floor',
    maxHealth: 420,
    buildTicks: seconds(14),
    cost: cost(['stone_block', 2]),
    placeOn: 'any',
    stacksOver: ['foundation'],
    requiredSkill: { id: 'building', level: 2 },
    xp: 8,
    zombieDamageMultiplier: 0.5,
  }),

  // --- walls ------------------------------------------------------------
  structure({
    id: 'wall_wood_frame',
    name: 'Wood Frame Wall',
    description: 'Sticks lashed into a lattice. It blocks a walker and nothing else.',
    category: 'wall',
    maxHealth: 90,
    buildTicks: seconds(5),
    cost: cost(['stick', 6], ['plant_fiber', 4]),
    blocksMovement: true,
    blocksSight: false,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    xp: 3,
    zombieDamageMultiplier: 1.4,
  }),
  structure({
    id: 'wall_wood',
    name: 'Wood Wall',
    description: 'Planked both sides. The standard early wall, and it will not last the month.',
    category: 'wall',
    maxHealth: 260,
    buildTicks: seconds(10),
    cost: cost(['wood_plank', 6], ['nail', 6]),
    blocksMovement: true,
    blocksSight: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    tool: 'hammer',
    xp: 8,
    zombieDamageMultiplier: 1.1,
  }),
  structure({
    id: 'wall_stone',
    name: 'Stone Wall',
    description: 'Coursed block. Three times the wall for four times the work.',
    category: 'wall',
    maxHealth: 750,
    buildTicks: seconds(28),
    cost: cost(['stone_block', 6], ['clay', 2]),
    blocksMovement: true,
    blocksSight: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 3 },
    xp: 20,
    zombieDamageMultiplier: 0.55,
  }),
  structure({
    id: 'wall_metal',
    name: 'Metal Wall',
    description: 'Plate over a welded frame. Brutes bounce off it and that is the point.',
    category: 'wall',
    maxHealth: 1400,
    buildTicks: seconds(40),
    cost: cost(['scrap_metal', 8], ['iron_ingot', 2], ['nail', 8]),
    blocksMovement: true,
    blocksSight: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 5 },
    xp: 40,
    zombieDamageMultiplier: 0.3,
  }),

  // --- doors, windows, ways through -------------------------------------
  structure({
    id: 'door_wood',
    name: 'Wood Door',
    description: 'A plank door on rope hinges. It closes, which is most of the job.',
    category: 'door',
    maxHealth: 190,
    buildTicks: seconds(10),
    cost: cost(['wood_plank', 5], ['nail', 4]),
    blocksMovement: true,
    blocksSight: true,
    requiresSupport: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    door: { lockable: false },
    tool: 'hammer',
    xp: 8,
    zombieDamageMultiplier: 1.2,
    spriteOpen: 'structure_door_wood_open',
  }),
  structure({
    id: 'door_reinforced',
    name: 'Reinforced Door',
    description: 'Scrap plate bolted over planks, and a bar you can drop.',
    category: 'door',
    maxHealth: 450,
    buildTicks: seconds(20),
    cost: cost(['wood_plank', 6], ['scrap_metal', 4], ['nail', 8]),
    blocksMovement: true,
    blocksSight: true,
    requiresSupport: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    door: { lockable: true },
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 2 },
    xp: 16,
    zombieDamageMultiplier: 0.7,
    spriteOpen: 'structure_door_reinforced_open',
  }),
  structure({
    id: 'door_metal',
    name: 'Metal Door',
    description: 'Steel slab in a steel frame, keyed. The last door you will need to build.',
    category: 'door',
    maxHealth: 950,
    buildTicks: seconds(35),
    cost: cost(['iron_ingot', 6], ['scrap_metal', 6], ['nail', 6]),
    blocksMovement: true,
    blocksSight: true,
    requiresSupport: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    door: { lockable: true },
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 4 },
    xp: 34,
    zombieDamageMultiplier: 0.3,
    spriteOpen: 'structure_door_metal_open',
  }),
  structure({
    id: 'window_wood',
    name: 'Window',
    description: 'Glass in a frame. You can see them coming, and they can see you.',
    category: 'window',
    maxHealth: 110,
    buildTicks: seconds(8),
    cost: cost(['wood_plank', 3], ['glass', 1], ['nail', 2]),
    blocksMovement: true,
    blocksSight: false,
    requiresSupport: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    tool: 'hammer',
    xp: 6,
    zombieDamageMultiplier: 1.5,
  }),
  structure({
    id: 'window_barred',
    name: 'Barred Window',
    description: 'Reinforcing bar welded across the opening. Light in, arms out.',
    category: 'window',
    maxHealth: 340,
    buildTicks: seconds(16),
    cost: cost(['wood_plank', 2], ['scrap_metal', 3], ['nail', 4]),
    blocksMovement: true,
    blocksSight: false,
    requiresSupport: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 2 },
    xp: 14,
    zombieDamageMultiplier: 0.6,
  }),
  structure({
    id: 'hatch',
    name: 'Hatch',
    description: 'A trapdoor in the floor, barred from the far side.',
    category: 'door',
    maxHealth: 230,
    buildTicks: seconds(14),
    cost: cost(['wood_plank', 5], ['nail', 6]),
    blocksMovement: true,
    blocksSight: false,
    requiresSupport: true,
    placeOn: 'floor',
    stacksOver: ['floor'],
    door: { lockable: true },
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 2 },
    xp: 12,
    zombieDamageMultiplier: 0.8,
    spriteOpen: 'structure_hatch_open',
  }),
  structure({
    id: 'stairs_wood',
    name: 'Wood Stairs',
    description: 'Six treads and a stringer. Gets you onto the roof.',
    category: 'misc',
    width: 1,
    height: 2,
    maxHealth: 180,
    buildTicks: seconds(14),
    cost: cost(['wood_plank', 6], ['nail', 6]),
    requiresSupport: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    tool: 'hammer',
    xp: 10,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'stairs_stone',
    name: 'Stone Stairs',
    description: 'Cut steps. Nothing burns them down.',
    category: 'misc',
    width: 1,
    height: 2,
    maxHealth: 520,
    buildTicks: seconds(30),
    cost: cost(['stone_block', 6]),
    requiresSupport: true,
    placeOn: 'any',
    stacksOver: ['floor', 'foundation'],
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 3 },
    xp: 22,
    zombieDamageMultiplier: 0.5,
  }),
  structure({
    id: 'ladder',
    name: 'Ladder',
    description: 'Two rails and eight rungs. Cheaper than stairs, and it can be pulled up.',
    category: 'misc',
    maxHealth: 120,
    buildTicks: seconds(8),
    cost: cost(['wood_plank', 4], ['nail', 4], ['rope', 2]),
    requiresSupport: true,
    placeOn: 'any',
    xp: 6,
    zombieDamageMultiplier: 1,
  }),

  // --- perimeter and defence -------------------------------------------
  structure({
    id: 'fence_wood',
    name: 'Wood Fence',
    description: 'Waist-high palings. Slows a walker, stops a rabbit.',
    category: 'defense',
    maxHealth: 90,
    buildTicks: seconds(4),
    cost: cost(['stick', 4], ['rope', 1]),
    blocksMovement: true,
    blocksSight: false,
    xp: 3,
    zombieDamageMultiplier: 1.3,
  }),
  structure({
    id: 'fence_barbed',
    name: 'Barbed Fence',
    description: 'Wire strung between stakes. They walk into it and keep walking into it.',
    category: 'defense',
    maxHealth: 120,
    buildTicks: seconds(8),
    cost: cost(['stick', 3], ['wire', 4]),
    blocksMovement: true,
    blocksSight: false,
    requiredSkill: { id: 'building', level: 1 },
    xp: 8,
    zombieDamageMultiplier: 1.2,
  }),
  structure({
    id: 'gate_wood',
    name: 'Wood Gate',
    description: 'A gap you control. Every wall needs exactly one.',
    category: 'door',
    width: 2,
    height: 1,
    maxHealth: 210,
    buildTicks: seconds(12),
    cost: cost(['wood_plank', 4], ['rope', 2], ['nail', 4]),
    blocksMovement: true,
    blocksSight: false,
    placeOn: 'any',
    door: { lockable: true },
    tool: 'hammer',
    xp: 10,
    zombieDamageMultiplier: 1.1,
    spriteOpen: 'structure_gate_wood_open',
  }),
  structure({
    id: 'gate_metal',
    name: 'Metal Gate',
    description: 'A driveway gate cut down and re-hung. Heavy enough to lean on.',
    category: 'door',
    width: 2,
    height: 1,
    maxHealth: 820,
    buildTicks: seconds(32),
    cost: cost(['iron_ingot', 4], ['scrap_metal', 6], ['nail', 6]),
    blocksMovement: true,
    blocksSight: false,
    placeOn: 'any',
    door: { lockable: true },
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 4 },
    xp: 30,
    zombieDamageMultiplier: 0.35,
    spriteOpen: 'structure_gate_metal_open',
  }),
  structure({
    id: 'barricade_wood',
    name: 'Wood Barricade',
    description: 'Planks nailed across an opening. Fast, ugly, and it buys a night.',
    category: 'defense',
    maxHealth: 270,
    buildTicks: seconds(7),
    cost: cost(['wood_plank', 4], ['nail', 4]),
    blocksMovement: true,
    blocksSight: false,
    requiresSupport: true,
    placeOn: 'any',
    tool: 'hammer',
    xp: 7,
    zombieDamageMultiplier: 0.9,
  }),
  structure({
    id: 'sandbag',
    name: 'Sandbag Wall',
    description: 'Cloth and sand, stacked. Soaks up bullets better than anything you can build.',
    category: 'defense',
    maxHealth: 520,
    buildTicks: seconds(18),
    cost: cost(['cloth', 4], ['sand', 8]),
    blocksMovement: true,
    blocksSight: false,
    requiredSkill: { id: 'building', level: 1 },
    xp: 14,
    zombieDamageMultiplier: 0.5,
  }),
  structure({
    id: 'spike_trap',
    name: 'Spike Trap',
    description:
      'Fire-hardened stakes in a shallow pit. Silent, cheap, and it does not reset itself.',
    category: 'defense',
    maxHealth: 60,
    buildTicks: seconds(10),
    cost: cost(['stick', 6], ['flint', 4], ['rope', 2]),
    blocksMovement: false,
    xp: 8,
    zombieDamageMultiplier: 1.6,
  }),
  structure({
    id: 'bear_trap',
    name: 'Bear Trap',
    description: 'Sprung steel jaws. Holds one thing in place for a long time.',
    category: 'defense',
    maxHealth: 140,
    buildTicks: seconds(12),
    cost: cost(['iron_ingot', 3], ['wire', 2]),
    blocksMovement: false,
    requiredSkill: { id: 'building', level: 2 },
    xp: 14,
    zombieDamageMultiplier: 1.2,
  }),
  structure({
    id: 'watchtower',
    name: 'Watchtower',
    description: 'Four legs and a platform. See the horde while it is still a rumour.',
    category: 'misc',
    width: 2,
    height: 2,
    maxHealth: 700,
    buildTicks: seconds(90),
    cost: cost(['wood_log', 8], ['wood_plank', 16], ['nail', 20], ['rope', 4]),
    blocksMovement: false,
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 4 },
    xp: 60,
    zombieDamageMultiplier: 0.8,
  }),

  // --- storage ----------------------------------------------------------
  structure({
    id: 'storage_box',
    name: 'Storage Box',
    description: 'Twenty slots of somewhere-else-to-put-it.',
    category: 'storage',
    maxHealth: 150,
    buildTicks: seconds(4),
    cost: cost(['storage_box_kit', 1]),
    blocksMovement: true,
    container: { slots: 20 },
    refundRatio: 0.8,
    xp: 6,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'storage_crate',
    name: 'Storage Crate',
    description: 'A proper braced crate. Thirty slots, built in place.',
    category: 'storage',
    maxHealth: 240,
    buildTicks: seconds(16),
    cost: cost(['wood_plank', 10], ['nail', 12]),
    blocksMovement: true,
    container: { slots: 30 },
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 2 },
    xp: 14,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'storage_locker',
    name: 'Steel Locker',
    description: 'Sheet steel and a hasp. Forty slots that survive a fire.',
    category: 'storage',
    maxHealth: 520,
    buildTicks: seconds(26),
    cost: cost(['scrap_metal', 10], ['iron_ingot', 2], ['nail', 8]),
    blocksMovement: true,
    container: { slots: 40 },
    tool: 'hammer',
    requiredSkill: { id: 'building', level: 3 },
    xp: 26,
    zombieDamageMultiplier: 0.4,
  }),

  // --- crafting stations ------------------------------------------------
  structure({
    id: 'workbench',
    name: 'Workbench',
    description: 'A flat surface and a vice. The single biggest jump in what you can make.',
    category: 'station',
    width: 2,
    height: 1,
    maxHealth: 260,
    buildTicks: seconds(6),
    cost: cost(['workbench_kit', 1]),
    blocksMovement: true,
    station: { kind: 'workbench', maxFuel: 0, heat: 0, needsFuel: false },
    refundRatio: 0.8,
    xp: 10,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'furnace',
    name: 'Furnace',
    description: 'Block and clay around a fire hot enough to free iron from rock.',
    category: 'station',
    maxHealth: 800,
    buildTicks: seconds(10),
    cost: cost(['furnace_kit', 1]),
    blocksMovement: true,
    station: { kind: 'furnace', maxFuel: 24000, heat: 30, needsFuel: true },
    refundRatio: 0.7,
    requiredSkill: { id: 'building', level: 2 },
    xp: 30,
    zombieDamageMultiplier: 0.5,
  }),
  structure({
    id: 'anvil',
    name: 'Anvil',
    description: 'Iron on a stump. Where tools stop being lashed together and start being forged.',
    category: 'station',
    maxHealth: 700,
    buildTicks: seconds(10),
    cost: cost(['anvil_kit', 1]),
    blocksMovement: true,
    station: { kind: 'anvil', maxFuel: 0, heat: 0, needsFuel: false },
    refundRatio: 0.8,
    requiredSkill: { id: 'building', level: 3 },
    xp: 34,
    zombieDamageMultiplier: 0.4,
  }),
  structure({
    id: 'loom',
    name: 'Loom',
    description: 'Warp, weft and a beater. Turns a pile of grass into clothing.',
    category: 'station',
    width: 2,
    height: 1,
    maxHealth: 200,
    buildTicks: seconds(8),
    cost: cost(['loom_kit', 1]),
    blocksMovement: true,
    station: { kind: 'loom', maxFuel: 0, heat: 0, needsFuel: false },
    refundRatio: 0.8,
    xp: 18,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'campfire',
    name: 'Campfire',
    description: 'Light, heat, cooked food and clean water. Nothing else does four jobs this well.',
    category: 'station',
    maxHealth: 60,
    buildTicks: seconds(4),
    cost: cost(['campfire_kit', 1]),
    blocksMovement: false,
    station: { kind: 'campfire', maxFuel: 12000, heat: 14, needsFuel: true },
    light: { radius: 240, fuelPerTick: 1 },
    refundRatio: 0.5,
    xp: 6,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'cooking_pot',
    name: 'Cooking Pot',
    description: 'Iron pot on a tripod. Soup, stew and four bottles of water at a time.',
    category: 'station',
    maxHealth: 160,
    buildTicks: seconds(5),
    cost: cost(['cooking_pot_kit', 1]),
    blocksMovement: false,
    station: { kind: 'cookingPot', maxFuel: 12000, heat: 12, needsFuel: true },
    light: { radius: 120, fuelPerTick: 1 },
    refundRatio: 0.8,
    xp: 12,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'grindstone',
    name: 'Grindstone',
    description: 'A wheel on a crank. Flour, bone meal, and an edge back on a tired blade.',
    category: 'station',
    maxHealth: 400,
    buildTicks: seconds(8),
    cost: cost(['grindstone_kit', 1]),
    blocksMovement: true,
    station: { kind: 'grindstone', maxFuel: 0, heat: 0, needsFuel: false },
    refundRatio: 0.7,
    requiredSkill: { id: 'building', level: 2 },
    xp: 20,
    zombieDamageMultiplier: 0.5,
  }),
  structure({
    id: 'chemistry_bench',
    name: 'Chemistry Bench',
    description: 'Retort, burner and a lot of careful notes. Medicine, powder and spirits.',
    category: 'station',
    width: 2,
    height: 1,
    maxHealth: 220,
    buildTicks: seconds(10),
    cost: cost(['chemistry_bench_kit', 1]),
    blocksMovement: true,
    station: { kind: 'chemistry', maxFuel: 8000, heat: 8, needsFuel: true },
    refundRatio: 0.7,
    requiredSkill: { id: 'building', level: 3 },
    xp: 30,
    zombieDamageMultiplier: 1,
  }),

  // --- beds -------------------------------------------------------------
  structure({
    id: 'bed_bedroll',
    name: 'Bedroll',
    description: 'Cloth over a fibre mat. You will wake up sore, but you will wake up.',
    category: 'bed',
    width: 1,
    height: 2,
    maxHealth: 40,
    buildTicks: seconds(4),
    cost: cost(['cloth', 6], ['plant_fiber', 8]),
    bed: { comfort: 0.45 },
    refundRatio: 0.5,
    xp: 5,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'bed_wood',
    name: 'Wood Bed',
    description: 'Frame, slats and a real mattress. Sleeping through the night, properly.',
    category: 'bed',
    width: 1,
    height: 2,
    maxHealth: 180,
    buildTicks: seconds(6),
    cost: cost(['bed_kit', 1]),
    bed: { comfort: 0.85 },
    refundRatio: 0.8,
    xp: 14,
    zombieDamageMultiplier: 1,
  }),

  // --- farming ----------------------------------------------------------
  structure({
    id: 'farm_plot',
    name: 'Farm Plot',
    description: 'Edged, dug and raked. One crop at a time, and it needs watering.',
    category: 'farm',
    maxHealth: 40,
    buildTicks: seconds(6),
    cost: cost(['farm_plot_kit', 1]),
    plot: { fertility: 100, moisture: 40 },
    tool: 'hoe',
    refundRatio: 0.5,
    xp: 8,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'planter_box',
    name: 'Planter Box',
    description: 'Raised, composted and it holds water. Grows faster and dries out slower.',
    category: 'farm',
    maxHealth: 110,
    buildTicks: seconds(14),
    cost: cost(['wood_plank', 6], ['nail', 6], ['fertilizer', 2]),
    plot: { fertility: 130, moisture: 70 },
    tool: 'hoe',
    refundRatio: 0.6,
    requiredSkill: { id: 'farming', level: 2 },
    xp: 16,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'compost_bin',
    name: 'Compost Bin',
    description: 'Slatted box for scraps and rot. Feed it the harvest you cannot eat.',
    category: 'farm',
    maxHealth: 140,
    buildTicks: seconds(12),
    cost: cost(['wood_plank', 8], ['nail', 8]),
    blocksMovement: true,
    container: { slots: 8 },
    requiredSkill: { id: 'farming', level: 1 },
    xp: 12,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'water_barrel',
    name: 'Water Barrel',
    description: 'Catches rain and holds it. Stops the daily walk to the pond.',
    category: 'furniture',
    maxHealth: 170,
    buildTicks: seconds(6),
    cost: cost(['water_barrel_kit', 1]),
    blocksMovement: true,
    container: { slots: 4 },
    refundRatio: 0.7,
    xp: 12,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'well',
    name: 'Well',
    description: 'Dug, lined and roped. Clean water forever, for two days of digging.',
    category: 'furniture',
    maxHealth: 900,
    buildTicks: seconds(120),
    cost: cost(['stone_block', 10], ['wood_plank', 4], ['rope', 4]),
    blocksMovement: true,
    container: { slots: 2 },
    refundRatio: 0.4,
    requiredSkill: { id: 'building', level: 3 },
    xp: 50,
    zombieDamageMultiplier: 0.4,
  }),

  // --- light and signage ------------------------------------------------
  structure({
    id: 'torch_wall',
    name: 'Wall Torch',
    description: 'A torch driven into a wall. Burns most of a night.',
    category: 'light',
    maxHealth: 30,
    buildTicks: seconds(2),
    cost: cost(['torch', 1]),
    requiresSupport: true,
    placeOn: 'any',
    light: { radius: 180, fuelPerTick: 0.08 },
    refundRatio: 0.5,
    xp: 2,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'lantern_post',
    name: 'Lantern Post',
    description: 'A lantern on a stake. Brighter than a torch and it lasts three nights.',
    category: 'light',
    maxHealth: 70,
    buildTicks: seconds(5),
    cost: cost(['lantern', 1], ['stick', 2]),
    light: { radius: 300, fuelPerTick: 0.04 },
    refundRatio: 0.7,
    requiredSkill: { id: 'building', level: 1 },
    xp: 8,
    zombieDamageMultiplier: 1,
  }),
  structure({
    id: 'sign',
    name: 'Sign',
    description: 'A board and a burnt-in message. The cheapest coordination tool in multiplayer.',
    category: 'misc',
    maxHealth: 60,
    buildTicks: seconds(4),
    cost: cost(['wood_plank', 2], ['nail', 2]),
    xp: 3,
    zombieDamageMultiplier: 1,
  }),
];

/** Every structure definition, numbered for the build menu in authoring order. */
export const STRUCTURE_DEFS: readonly StructureDef[] = AUTHORED.map((def, index) => ({
  ...def,
  sortOrder: (index + 1) * 10,
}));
