import type { ZombieDef } from '../types';
import { seconds } from './units';

/**
 * The zombie table.
 *
 * Speeds assume a player walks at roughly 110 px/s and sprints at roughly 185 px/s,
 * so the read across the table is:
 *
 * - **walker (82) and shambler (48)** are slower than a walking player. You can always
 *   leave. That is what makes the first week about noise discipline rather than combat.
 * - **runner (205), feral dog (240)** are faster than a sprint. From day four onwards,
 *   "I will just outrun it" stops being a plan.
 * - **brute (118)** cannot catch you, but it does not need to: it goes through the wall
 *   you were hiding behind at 60 structure damage a swing.
 *
 * `noise` is the radius, in pixels, at which this zombie's own racket pulls others in.
 * The screamer's 4 200 is the whole point of the archetype - it turns one bad encounter
 * into four chunks' worth of attention, the same order as a gunshot.
 *
 * `minDay` / `nightOnly` / `spawnWeight` are the difficulty curve. Everything above
 * tier 1 has a `minDay`, so an unlucky day-two player meets numbers, not surprises.
 *
 * The spitter attacks at 300 px with no weapon item; the AI fires the `spitter_bile`
 * projectile def, since `ZombieDef` has no projectile field of its own.
 */
export const ZOMBIE_DEFS: readonly ZombieDef[] = [
  {
    id: 'walker',
    name: 'Walker',
    tier: 1,
    maxHealth: 90,
    bodyScale: 1,
    speedWalk: 40,
    speedChase: 82,
    radius: 12,
    damage: 9,
    damageType: 'slash',
    attackRange: 30,
    attackTicks: seconds(1.2),
    windupTicks: seconds(0.35),
    biteChance: 0.35,
    infectionChance: 0.28,
    knockback: 40,
    sightRange: 340,
    sightHalfAngle: 1.1,
    hearingRange: 520,
    loseInterestTicks: seconds(8),
    armor: {},
    staggerResist: 0.1,
    canOpenDoors: false,
    attacksStructures: true,
    structureDamage: 6,
    crawlSpeedMultiplier: 0.35,
    xp: 12,
    lootTableId: 'zombie_common',
    spawnWeight: 100,
    minDay: 1,
    nightOnly: false,
    noise: 260,
    sprite: 'zombie_walker',
  },
  {
    id: 'shambler',
    name: 'Shambler',
    tier: 1,
    maxHealth: 190,
    bodyScale: 1.2,
    speedWalk: 26,
    speedChase: 48,
    radius: 14,
    damage: 13,
    damageType: 'blunt',
    attackRange: 32,
    attackTicks: seconds(1.6),
    windupTicks: seconds(0.5),
    biteChance: 0.3,
    infectionChance: 0.26,
    knockback: 70,
    sightRange: 280,
    sightHalfAngle: 0.95,
    hearingRange: 460,
    loseInterestTicks: seconds(11),
    armor: { blunt: 2, slash: 1 },
    staggerResist: 0.4,
    canOpenDoors: false,
    attacksStructures: true,
    structureDamage: 10,
    crawlSpeedMultiplier: 0.3,
    xp: 20,
    lootTableId: 'zombie_common',
    spawnWeight: 55,
    minDay: 1,
    nightOnly: false,
    noise: 280,
    sprite: 'zombie_shambler',
  },
  {
    id: 'crawler',
    name: 'Crawler',
    tier: 1,
    maxHealth: 55,
    bodyScale: 0.7,
    speedWalk: 22,
    speedChase: 42,
    radius: 10,
    damage: 12,
    damageType: 'zombieBite',
    attackRange: 26,
    attackTicks: seconds(1.1),
    windupTicks: seconds(0.3),
    // It is already at ankle height, and it goes for the leg every time.
    biteChance: 0.6,
    infectionChance: 0.34,
    knockback: 20,
    sightRange: 220,
    sightHalfAngle: 0.9,
    hearingRange: 380,
    loseInterestTicks: seconds(14),
    armor: {},
    staggerResist: 0.55,
    canOpenDoors: false,
    attacksStructures: false,
    structureDamage: 2,
    crawlSpeedMultiplier: 1,
    xp: 16,
    lootTableId: 'zombie_common',
    spawnWeight: 40,
    minDay: 2,
    nightOnly: false,
    noise: 160,
    sprite: 'zombie_crawler',
  },
  {
    id: 'runner',
    name: 'Runner',
    tier: 2,
    maxHealth: 70,
    bodyScale: 0.9,
    speedWalk: 70,
    speedChase: 205,
    radius: 11,
    damage: 11,
    damageType: 'slash',
    attackRange: 30,
    attackTicks: seconds(0.85),
    windupTicks: seconds(0.2),
    biteChance: 0.5,
    infectionChance: 0.3,
    knockback: 50,
    sightRange: 420,
    sightHalfAngle: 1.2,
    hearingRange: 600,
    loseInterestTicks: seconds(16),
    armor: {},
    staggerResist: 0.15,
    canOpenDoors: true,
    attacksStructures: true,
    structureDamage: 8,
    crawlSpeedMultiplier: 0.45,
    xp: 32,
    lootTableId: 'zombie_common',
    spawnWeight: 34,
    minDay: 4,
    nightOnly: false,
    noise: 340,
    sprite: 'zombie_runner',
  },
  {
    id: 'feral_dog_zombie',
    name: 'Feral Dog',
    tier: 2,
    maxHealth: 60,
    bodyScale: 0.6,
    speedWalk: 90,
    speedChase: 240,
    radius: 9,
    damage: 12,
    damageType: 'zombieBite',
    attackRange: 26,
    attackTicks: seconds(0.7),
    windupTicks: seconds(0.15),
    biteChance: 0.8,
    infectionChance: 0.32,
    knockback: 30,
    sightRange: 400,
    sightHalfAngle: 1.3,
    hearingRange: 700,
    loseInterestTicks: seconds(20),
    armor: {},
    staggerResist: 0.2,
    canOpenDoors: false,
    attacksStructures: false,
    structureDamage: 0,
    crawlSpeedMultiplier: 0.5,
    xp: 34,
    lootTableId: 'zombie_dog',
    spawnWeight: 18,
    minDay: 3,
    // Packs move after dark. Being caught outside at night has to mean something.
    nightOnly: true,
    noise: 360,
    sprite: 'zombie_dog',
  },
  {
    id: 'screamer',
    name: 'Screamer',
    tier: 2,
    maxHealth: 80,
    bodyScale: 0.95,
    speedWalk: 44,
    speedChase: 96,
    radius: 12,
    damage: 7,
    damageType: 'slash',
    attackRange: 30,
    attackTicks: seconds(1.3),
    windupTicks: seconds(0.4),
    biteChance: 0.25,
    infectionChance: 0.24,
    knockback: 30,
    sightRange: 480,
    sightHalfAngle: 1.25,
    hearingRange: 640,
    loseInterestTicks: seconds(18),
    armor: {},
    staggerResist: 0.2,
    canOpenDoors: false,
    attacksStructures: false,
    structureDamage: 3,
    crawlSpeedMultiplier: 0.4,
    xp: 55,
    lootTableId: 'zombie_common',
    spawnWeight: 10,
    minDay: 5,
    nightOnly: false,
    // As loud as a pistol shot. Kill it first, quietly, or do not be there.
    noise: 4200,
    sprite: 'zombie_screamer',
  },
  {
    id: 'spitter',
    name: 'Spitter',
    tier: 2,
    maxHealth: 100,
    bodyScale: 1,
    speedWalk: 34,
    speedChase: 58,
    radius: 13,
    damage: 15,
    damageType: 'poison',
    // Ranged: the AI fires the `spitter_bile` projectile at this distance.
    attackRange: 300,
    attackTicks: seconds(2.4),
    windupTicks: seconds(0.9),
    biteChance: 0.05,
    infectionChance: 0.1,
    knockback: 0,
    sightRange: 440,
    sightHalfAngle: 1.05,
    hearingRange: 460,
    loseInterestTicks: seconds(12),
    armor: { poison: 20, fire: 2 },
    staggerResist: 0.25,
    canOpenDoors: false,
    attacksStructures: false,
    structureDamage: 4,
    crawlSpeedMultiplier: 0.4,
    xp: 48,
    lootTableId: 'zombie_common',
    spawnWeight: 14,
    minDay: 7,
    nightOnly: false,
    noise: 320,
    sprite: 'zombie_spitter',
  },
  {
    id: 'bloater',
    name: 'Bloater',
    tier: 2,
    maxHealth: 230,
    bodyScale: 1.4,
    speedWalk: 24,
    speedChase: 44,
    radius: 17,
    damage: 17,
    damageType: 'poison',
    attackRange: 34,
    attackTicks: seconds(1.8),
    windupTicks: seconds(0.6),
    biteChance: 0.3,
    infectionChance: 0.4,
    knockback: 90,
    sightRange: 260,
    sightHalfAngle: 0.9,
    hearingRange: 420,
    loseInterestTicks: seconds(10),
    // All that mass soaks small arms; a blade still opens it up.
    armor: { pierce: 6, bullet: 5, poison: 20 },
    staggerResist: 0.6,
    canOpenDoors: false,
    attacksStructures: true,
    structureDamage: 14,
    crawlSpeedMultiplier: 0.25,
    xp: 62,
    lootTableId: 'zombie_common',
    spawnWeight: 12,
    minDay: 8,
    nightOnly: false,
    noise: 300,
    sprite: 'zombie_bloater',
  },
  {
    id: 'armored',
    name: 'Armored Zombie',
    tier: 3,
    maxHealth: 200,
    bodyScale: 1.1,
    speedWalk: 38,
    speedChase: 88,
    radius: 13,
    damage: 19,
    damageType: 'blunt',
    attackRange: 32,
    attackTicks: seconds(1.3),
    windupTicks: seconds(0.4),
    biteChance: 0.2,
    infectionChance: 0.26,
    knockback: 80,
    sightRange: 320,
    sightHalfAngle: 1,
    hearingRange: 480,
    loseInterestTicks: seconds(14),
    // Riot gear, still buckled on. Blunt trauma is the answer; bullets are not.
    armor: { blunt: 6, slash: 11, pierce: 9, bullet: 13, explosive: 4 },
    staggerResist: 0.7,
    canOpenDoors: true,
    attacksStructures: true,
    structureDamage: 16,
    crawlSpeedMultiplier: 0.3,
    xp: 95,
    lootTableId: 'zombie_armored',
    spawnWeight: 7,
    minDay: 12,
    nightOnly: false,
    noise: 300,
    sprite: 'zombie_armored',
  },
  {
    id: 'brute',
    name: 'Brute',
    tier: 3,
    maxHealth: 500,
    bodyScale: 1.8,
    speedWalk: 38,
    speedChase: 118,
    radius: 20,
    damage: 35,
    damageType: 'blunt',
    attackRange: 46,
    attackTicks: seconds(1.8),
    windupTicks: seconds(0.7),
    biteChance: 0.15,
    infectionChance: 0.3,
    knockback: 300,
    sightRange: 360,
    sightHalfAngle: 1,
    hearingRange: 560,
    loseInterestTicks: seconds(20),
    armor: { blunt: 4, slash: 6, pierce: 5, bullet: 3 },
    staggerResist: 0.85,
    canOpenDoors: true,
    attacksStructures: true,
    // Ten swings through a wood wall, forty through stone. Walls buy time, not safety.
    structureDamage: 60,
    crawlSpeedMultiplier: 0.5,
    xp: 130,
    lootTableId: 'zombie_brute',
    spawnWeight: 8,
    minDay: 10,
    nightOnly: false,
    noise: 520,
    sprite: 'zombie_brute',
  },
];
