import { AOI_RADIUS, CHUNK_LOAD_RADIUS, DEFAULT_PORT, SIM_HZ, SNAPSHOT_HZ } from './constants';

/**
 * How the one and only GameServer behaves in a given mode.
 *
 * Single-player and multiplayer run the *same* server binary and the *same*
 * simulation; everything that differs between them lives in this config object
 * (spec sections 11 and 12).
 */
export interface ServerModeConfig {
  /** True when this server was spawned by the game client for one local player. */
  singlePlayer: boolean;
  maxPlayers: number;
  /** Allow a client to pause the whole simulation. Single-player only. */
  pauseWhenClientPaused: boolean;
  /** Stop stepping the simulation when nobody is connected, to save CPU. */
  pauseWhenEmpty: boolean;
  /** Players can damage players. */
  pvp: boolean;
  /** Enable the `debug` command family. */
  cheatsEnabled: boolean;
}

export interface ServerNetworkConfig {
  host: string;
  port: number;
  /** Required in the join handshake. Empty string means no password. */
  password: string;
  /**
   * One-shot token the local client must present. Generated by the launcher for
   * single-player so nothing else on the machine can join (spec section 13).
   */
  token: string;
  /** Radius in pixels of the replicated area around each player. */
  aoiRadius: number;
}

export interface WorldGenConfig {
  seed: number;
  /** Fraction of the map that is town/road rather than wilderness, 0..1. */
  urbanization: number;
  /** Multiplier on zombie population density. */
  zombieDensity: number;
  /** Multiplier on animal population density. */
  animalDensity: number;
  /** Multiplier on resource-node density. */
  resourceDensity: number;
  /** Multiplier on container loot richness. */
  lootAbundance: number;
}

export interface SurvivalTuning {
  /** Multiplier on hunger/thirst/fatigue accumulation. */
  needRate: number;
  /** Multiplier on all damage dealt to players. */
  playerDamageTaken: number;
  /** Multiplier on all damage dealt by players. */
  playerDamageDealt: number;
  /** Multiplier on crop growth speed. */
  cropGrowthRate: number;
  /** Multiplier on crafting speed. */
  craftSpeed: number;
  /** Multiplier on skill XP gain. */
  xpRate: number;
  /** Ticks before a corpse's dropped loot despawns. -1 to never despawn. */
  itemDespawnTicks: number;
  /** Chance a zombie bite starts an infection, 0..1. */
  infectionChance: number;
}

export interface SimulationConfig {
  mode: ServerModeConfig;
  network: ServerNetworkConfig;
  world: WorldGenConfig;
  tuning: SurvivalTuning;
  /** Simulation ticks per second. Kept in config so profiling can retune it. */
  simHz: number;
  /** Snapshots per second. */
  snapshotHz: number;
  chunkLoadRadius: number;
  /** Save directory name, e.g. `world01`. */
  saveName: string;
}

export function defaultSurvivalTuning(): SurvivalTuning {
  return {
    needRate: 1,
    playerDamageTaken: 1,
    playerDamageDealt: 1,
    cropGrowthRate: 1,
    craftSpeed: 1,
    xpRate: 1,
    itemDespawnTicks: SIM_HZ * 60 * 30,
    infectionChance: 0.25,
  };
}

export function defaultWorldGenConfig(seed = 1337): WorldGenConfig {
  return {
    seed,
    urbanization: 0.18,
    zombieDensity: 1,
    animalDensity: 1,
    resourceDensity: 1,
    lootAbundance: 1,
  };
}

export function singlePlayerConfig(saveName = 'world01', token = ''): SimulationConfig {
  return {
    mode: {
      singlePlayer: true,
      maxPlayers: 1,
      pauseWhenClientPaused: true,
      pauseWhenEmpty: true,
      pvp: false,
      cheatsEnabled: true,
    },
    network: {
      host: '127.0.0.1',
      port: 0,
      password: '',
      token,
      aoiRadius: AOI_RADIUS,
    },
    world: defaultWorldGenConfig(),
    tuning: defaultSurvivalTuning(),
    simHz: SIM_HZ,
    snapshotHz: SNAPSHOT_HZ,
    chunkLoadRadius: CHUNK_LOAD_RADIUS,
    saveName,
  };
}

export function dedicatedConfig(saveName = 'server01'): SimulationConfig {
  return {
    mode: {
      singlePlayer: false,
      maxPlayers: 16,
      pauseWhenClientPaused: false,
      pauseWhenEmpty: true,
      pvp: true,
      cheatsEnabled: false,
    },
    network: {
      host: '0.0.0.0',
      port: DEFAULT_PORT,
      password: '',
      token: '',
      aoiRadius: AOI_RADIUS,
    },
    world: defaultWorldGenConfig(),
    tuning: defaultSurvivalTuning(),
    simHz: SIM_HZ,
    snapshotHz: SNAPSHOT_HZ,
    chunkLoadRadius: CHUNK_LOAD_RADIUS,
    saveName,
  };
}

/** The slice of server config a client is allowed to see. */
export interface ClientVisibleConfig {
  singlePlayer: boolean;
  maxPlayers: number;
  pvp: boolean;
  cheatsEnabled: boolean;
  simHz: number;
  snapshotHz: number;
  canPause: boolean;
}

export function toClientVisibleConfig(config: SimulationConfig): ClientVisibleConfig {
  return {
    singlePlayer: config.mode.singlePlayer,
    maxPlayers: config.mode.maxPlayers,
    pvp: config.mode.pvp,
    cheatsEnabled: config.mode.cheatsEnabled,
    simHz: config.simHz,
    snapshotHz: config.snapshotHz,
    canPause: config.mode.pauseWhenClientPaused,
  };
}
