import { expect, test } from '@playwright/test';
import { holdKey, joinServer, nearest, openClient, waitForTicks, walkTowards } from './helpers';

/** Where the regenerated project screenshots land. */
const SHOT_DIR = 'docs/screenshots';

/**
 * Visual verification (spec section 37's last step).
 *
 * These do not diff against golden images — procedural art plus a moving world makes that
 * a maintenance sink. Instead they capture the states a human would want to look at, and
 * assert the weak invariant that the canvas is not blank.
 */
test.describe('visual', () => {
  test('captures the menu, the world and every panel', async ({ page }, testInfo) => {
    // Written to a stable folder as well as attached to the report: these double as the
    // project's screenshots, so they are regenerated by running the suite rather than
    // being stale files somebody remembered to update.
    const shot = async (name: string) => {
      const body = await page.screenshot();
      await testInfo.attach(`${name}.png`, { body, contentType: 'image/png' });
      await page.screenshot({ path: `${SHOT_DIR}/${name}.png` });
    };

    await openClient(page);
    await shot('01-menu');

    await joinServer(page, 'Camera');
    await waitForTicks(page, 20);
    await shot('02-world');

    for (const [name, key] of [
      ['03-inventory', 'KeyI'],
      ['04-crafting', 'KeyQ'],
      ['05-build', 'KeyB'],
      ['06-body', 'KeyH'],
      ['07-map', 'KeyM'],
      ['08-debug', 'F3'],
    ] as const) {
      await page.keyboard.press(key);
      await page.waitForTimeout(450);
      await shot(name);
      await page.keyboard.press('Escape');
      await page.waitForTimeout(150);
    }
  });

  test('the world canvas is actually drawing, and it scrolls when the player moves', async ({
    page,
  }) => {
    await openClient(page);
    await joinServer(page);
    await waitForTicks(page, 20);

    // Sampling the canvas from inside the page does not work: a WebGL context without
    // `preserveDrawingBuffer` hands back blank pixels to `drawImage`, and turning that on
    // costs real frame time for a test's benefit. Playwright's screenshot captures the
    // composited frame, which is what a player actually sees.
    const before = await page.locator('#game canvas').screenshot();
    // A blank frame compresses to almost nothing; a drawn world does not.
    expect(before.byteLength).toBeGreaterThan(20_000);

    await holdKey(page, 'KeyD', 700);
    const after = await page.locator('#game canvas').screenshot();

    // The camera follows the player, so walking east has to change what is on screen.
    expect(Buffer.compare(before, after)).not.toBe(0);
    expect(after.byteLength).toBeGreaterThan(20_000);
  });

  test('shows an interaction prompt when standing next to something', async ({ page }) => {
    await openClient(page);
    await joinServer(page);
    await waitForTicks(page, 20);

    // Walked *at* a node the client can already see, rather than in hopeful directions.
    // Every gameplay test shares one server and one save, and several of them move the
    // player, so "wander east and hope" passes or fails on where the previous test left
    // them. This is the cheapest end-to-end proof that terrain, entity replication, the
    // interaction search and the HUD all agree - it just needs to be aimed.
    const node = await nearest(page, 'node');
    expect(node, 'expected a resource node within streaming range').not.toBeNull();

    const sawPrompt = await walkTowards(page, node!, () => page.locator('.hud-prompt').isVisible());
    expect(sawPrompt, 'expected an interaction prompt on reaching the node').toBe(true);
    await expect(page.locator('.hud-prompt')).toContainText(/harvest|search|open|pick up|use/i);
  });
});
