import type { UiStringTable } from './types';

/**
 * English interface text.
 *
 * Everything the player reads that is *not* a piece of game content: panel titles, button
 * labels, the messages the simulation asks for by code, and the wording for a refused
 * command. Content names live in `@survive/game-data`'s own table, next to the content
 * they describe; this one lives next to the interface it belongs to, so a change to either
 * does not drag the other along.
 *
 * `notify` and `reject` are keyed by what the *server* sends. The server names a message
 * and supplies its values - it never sends a finished sentence - because word order, where
 * a number goes and how a thing is pluralised are decisions the reader's language makes.
 */
export const EN_UI: UiStringTable = {
  /** Messages the simulation raises, keyed by the code it sends. */
  notify: {
    'notify.addedToStation': 'Added {count} x {item} to the {station}.',
    'notify.alreadyTidy': 'Already tidy.',
    'notify.bedGone': 'Your bed is gone. You wake where you started.',
    'notify.bedOccupied': 'Someone else is in your bed. You wake where you started.',
    'notify.bedSet': 'You will wake up here.',
    'notify.bedWrecked': 'Your bed is wrecked. You wake where you started.',
    'notify.biteTurning': 'The bite is turning. There is not much time.',
    'notify.bleedingOut': 'You are bleeding out.',
    'notify.bloodLossWarn': 'You have lost a lot of blood. Stop the bleeding.',
    'notify.botchedTreatment': 'You botch the {treatment} on your {part}.',
    'notify.filledDirtyWater': 'Filled with dirty water.',
    'notify.foodPoisoning': 'That was a mistake. Your stomach turns.',
    'notify.heatstroke': 'Heatstroke. Get out of the sun and drink.',
    'notify.hypothermia': 'Hypothermia. You need warmth now.',
    'notify.infectionSystemic': 'The infection is systemic. You need antibiotics.',
    'notify.inventoryFull': 'Your inventory filled up.',
    'notify.locked': 'Locked.',
    'notify.need.fatigue.critical': 'You are collapsing from exhaustion.',
    'notify.need.fatigue.urgent': 'You can barely keep your eyes open.',
    'notify.need.fatigue.warn': 'You are tired.',
    'notify.need.hunger.critical': 'You are starving to death.',
    'notify.need.hunger.urgent': 'You are famished. Find food.',
    'notify.need.hunger.warn': 'You are getting hungry.',
    'notify.need.thirst.critical': 'You are dying of thirst.',
    'notify.need.thirst.urgent': 'You are badly dehydrated. Find water.',
    'notify.need.thirst.warn': 'Your throat is dry.',
    'notify.noRoomDropped': 'No room - it fell on the ground.',
    'notify.noVessel': 'Nothing to carry water in.',
    'notify.painBlackout': 'The pain whites everything out.',
    'notify.partMended': 'Your {part} has mended.',
    'notify.plantOnPlot': 'Plant {crop} on a tilled plot.',
    'notify.plotCleared': 'Cleared the plot.',
    'notify.plotClearedOf': 'Cleared the plot of {crop}.',
    'notify.readyToPlace': '{structure} ready to place.',
    'notify.sleep.start': 'You settle down to sleep.',
    'notify.someItemsDropped': 'Some items would not fit and fell on the ground.',
    'notify.structureFinished': '{structure} finished.',
    'notify.tooExhausted': 'Too exhausted to attack.',
    'notify.unlocked': 'Unlocked.',
    'notify.wake.bedLost': 'Your bed is gone. You wake on the ground.',
    'notify.wake.commanded': 'You get up.',
    'notify.wake.died': 'You died in your sleep.',
    'notify.wake.moved': 'You stir and get up.',
    'notify.wake.rested': 'You wake up rested.',
    'notify.wake.threat': 'Something moving nearby drags you awake.',
    'notify.weatherSet': 'Weather set to {weather} ({intensity}) for {hours}h.',
    'notify.woundInfected': 'A wound has gone bad. You are running a fever.',
  },
  /**
   * Why a command was refused.
   *
   * Keyed by the reason string the simulation sends. Those reasons are a mix of short
   * codes and English phrases, and they used to be shown to the player raw - so a failed
   * gather flashed `toolIneffective` on screen. Keying by the raw value keeps the server
   * untouched while giving every one of them a sentence a person would write.
   */
  reject: {
    'already asleep': 'Already asleep',
    'already tilled': 'Already tilled',
    'bad target tile': 'Nothing there to act on.',
    badRotation: 'That will not fit facing this way.',
    blueprint: 'Blueprint',
    'both hands are on that weapon': 'Both hands are on that weapon',
    busy: 'You are busy.',
    'cannot sort equipment': 'Cannot sort equipment',
    'cannot split equipment': 'Cannot split equipment',
    'cannot split off the whole stack': 'Cannot split off the whole stack',
    'container is not open': 'Container is not open',
    cooldown: 'Not ready yet.',
    dead: 'You are dead.',
    depleted: 'There is nothing left to take.',
    'destination is full': 'Destination is full',
    'destination slot is occupied': 'Destination slot is occupied',
    'destination stack is full': 'Destination stack is full',
    'farm plots are unavailable': 'Farm plots are unavailable',
    indestructible: 'That cannot be destroyed.',
    'invalid code': 'That command made no sense.',
    'invalid count': 'Invalid count',
    'invalid destination slot': 'Invalid destination slot',
    'invalid hotbar slot': 'Invalid hotbar slot',
    'invalid inventory slot': 'Invalid inventory slot',
    'invalid slot': 'Invalid slot',
    'invalid source slot': 'Invalid source slot',
    'it is already on the ground': 'It is already on the ground',
    'it is locked': 'It is locked',
    'it is not ready yet': 'It is not ready yet',
    locked: 'It is locked.',
    'malformed container ref': 'Malformed container ref',
    missingMaterials: 'You do not have the materials.',
    missingTool: 'You do not have the right tool.',
    'no free slot to split into': 'No free slot to split into',
    'no item in that slot': 'No item in that slot',
    'no line of sight': 'No line of sight',
    'no room in your inventory': 'No room in your inventory',
    'no seed selected': 'No seed selected',
    'no such item container': 'No such item container',
    'no such structure': 'No such structure',
    noLineOfSight: 'You cannot reach it from here.',
    'not with those things so close': 'Not with those things so close',
    notADoor: 'That is not a door.',
    notBuildable: 'That cannot be built yet.',
    notDamaged: 'It is not damaged.',
    notOwner: 'That is not yours.',
    'nothing equipped there': 'Nothing equipped there',
    'nothing happens': 'Nothing happens',
    'nothing is growing here': 'Nothing is growing here',
    'nothing to clear': 'Nothing to clear',
    'nothing to sort there': 'Nothing to sort there',
    'nothing to split there': 'Nothing to split there',
    'nothing to use there': 'Nothing to use there',
    'out of reach': 'Out of reach',
    outOfRange: 'Too far away.',
    'paused must be a boolean': 'Paused must be a boolean',
    'pausing is not allowed on this server': 'Pausing is not allowed on this server',
    'slot is empty': 'Slot is empty',
    'someone is already in it': 'Someone is already in it',
    'something is already built here': 'Something is already built here',
    'something is in the way': 'Something is in the way',
    'source slot is empty': 'Source slot is empty',
    'still busy': 'Still busy',
    'that cannot be equipped': 'That cannot be equipped',
    'that cannot be placed': 'That cannot be placed',
    'that cannot be worn there': 'That cannot be worn there',
    'that container is not being worn': 'That container is not being worn',
    'that has nowhere to fit a lock': 'That has nowhere to fit a lock',
    'that is not a usable bed': 'That is not a usable bed',
    'that is not yours yet': 'That is not yours yet',
    'that item is gone': 'That item is gone',
    'that structure has no container': 'That structure has no container',
    'that will not grow': 'That will not grow',
    'the ground is blocked': 'The ground is blocked',
    'the ground is not a source': 'The ground is not a source',
    'the ground is not tilled': 'The ground is not tilled',
    'the soil is already soaked': 'The soil is already soaked',
    'there is no plot here': 'There is no plot here',
    'this ground cannot be tilled': 'This ground cannot be tilled',
    'this plant is spent': 'This plant is spent',
    'this soil needs nothing': 'This soil needs nothing',
    'too far away': 'Too far away',
    'too far from the bed': 'Too far from the bed',
    toolIneffective: 'Your tool is not good enough for that.',
    'unequip that first': 'Unequip that first',
    'unknown body part': 'Unknown body part',
    'unknown container kind': 'Unknown container kind',
    'unknown crop': 'Unknown crop',
    'unknown equipment slot': 'Unknown equipment slot',
    'unknown farm action': 'Unknown farm action',
    'unknown item': 'Unknown item',
    'unknown seed': 'Unknown seed',
    unknownNode: 'That is gone.',
    unknownStructure: 'That structure is gone.',
    'you are dead': 'You are dead',
    'you are not asleep': 'You are not asleep',
    'you are not dead': 'You are not dead',
    'you do not own that': 'You do not own that',
    'you have no fertilizer': 'You have no fertilizer',
    'you need a hoe': 'You need a hoe',
    'you need a watering can or a full vessel': 'You need a watering can or a full vessel',
  },
  /** Interface chrome: titles, labels, buttons, prompts. */
  ui: {
    'hotbar.hand': 'HAND',
    'panel.body': 'Body',
    'panel.build': 'Build',
    'panel.chat': 'Chat',
    'panel.container': 'Container',
    'panel.crafting': 'Crafting',
    'panel.death': 'You died',
    'panel.debug': 'Debug',
    'panel.inventory': 'Inventory',
    'panel.map': 'Map',
    'panel.paused': 'Paused',
    'panel.skills': 'Skills',
    'prompt.closeDoor': 'close {name}',
    'prompt.harvest': 'harvest {name}',
    'prompt.openDoor': 'open {name}',
    'prompt.pickUp': 'pick up {name}',
    'prompt.search': 'search {name}',
    'prompt.sleep': 'sleep in {name}',
    'prompt.tend': 'tend {name}',
    'prompt.useStation': 'use {name}',
    'tip.byHand': 'Harvested by hand',
    'effect.well_fed': 'Well Fed',
    'effect.hydrated': 'Hydrated',
    'effect.well_rested': 'Well Rested',
    'effect.painkiller': 'Painkiller',
    'effect.antibiotic': 'Antibiotic',
    'effect.antiseptic': 'Antiseptic',
    'effect.adrenaline': 'Adrenaline',
    'effect.bandaged': 'Bandaged',
    'effect.fever': 'Fever',
    'effect.poisoned': 'Poisoned',
    'effect.food_poisoning': 'Food Poisoning',
    'effect.bleeding': 'Bleeding',
    'effect.exhausted': 'Exhausted',
    'effect.overencumbered': 'Overencumbered',
    'effect.cold': 'Cold',
    'effect.hypothermia': 'Hypothermia',
    'effect.hot': 'Hot',
    'effect.heatstroke': 'Heatstroke',
    'effect.stunned': 'Stunned',
    'effect.wet': 'Wet',
    'effect.sepsis': 'Sepsis',
    'effect.zombification': 'Zombification',
    'bodyPart.head': 'Head',
    'bodyPart.torso': 'Torso',
    'bodyPart.leftArm': 'Left Arm',
    'bodyPart.rightArm': 'Right Arm',
    'bodyPart.leftLeg': 'Left Leg',
    'bodyPart.rightLeg': 'Right Leg',
    'chip.fractured': '{part} fractured',
    'skill.melee': 'Melee',
    'skill.ranged': 'Ranged',
    'skill.woodcutting': 'Woodcutting',
    'skill.mining': 'Mining',
    'skill.foraging': 'Foraging',
    'skill.farming': 'Farming',
    'skill.crafting': 'Crafting',
    'skill.building': 'Building',
    'skill.cooking': 'Cooking',
    'skill.medicine': 'Medicine',
    'skill.athletics': 'Athletics',
    'skill.stealth': 'Stealth',
    'entity.player': 'Player',
    'entity.zombie': 'Zombie',
    'entity.animal': 'Animal',
    'entity.item': 'Item',
    'entity.projectile': 'Projectile',
    'entity.structure': 'Structure',
    'entity.node': 'Node',
    'biome.0': 'Grassland',
    'biome.1': 'Forest',
    'biome.2': 'Deep Forest',
    'biome.3': 'Rocky Hills',
    'biome.4': 'Beach',
    'biome.5': 'Lake',
    'biome.6': 'Swamp',
    'biome.7': 'Town',
    'biome.8': 'Farmland',
    'biome.9': 'Road',
    'map.following': 'following you',
    'map.freeLook': 'free look',
    'map.nothingExplored': 'nothing explored',
    'map.pxPerTile': '{scale} px/tile',
    'map.unknownBiome': 'unknown',
    'map.viewLine': '{scale} px/tile · {chunks} chunks · {mode}',
    'build.blocksMovement': 'Blocks movement',
    'build.cat.beds': 'Beds',
    'build.cat.defences': 'Defences',
    'build.cat.doors': 'Doors',
    'build.cat.farming': 'Farming',
    'build.cat.floors': 'Floors',
    'build.cat.foundations': 'Foundations',
    'build.cat.furniture': 'Furniture',
    'build.cat.lighting': 'Lighting',
    'build.cat.other': 'Other',
    'build.cat.stations': 'Stations',
    'build.cat.storage': 'Storage',
    'build.cat.walls': 'Walls',
    'build.cat.windows': 'Windows',
    'build.clear': 'Clear',
    'build.clearHint': 'Clear the build selection',
    'build.collapseAll': 'Collapse all',
    'build.expandAll': 'Expand all',
    'build.mustTouch': 'Must touch an existing wall or foundation',
    'build.nothingSelected': 'Nothing selected. Pick a piece below, then click in the world.',
    'build.rotateCcw': 'Rotate anticlockwise (Shift+T)',
    'build.rotateCcwHint': 'Rotate selection anticlockwise',
    'build.rotateCw': 'Rotate clockwise (T)',
    'build.rotateCwHint': 'Rotate selection clockwise',
    'build.selectionControls': 'Selection controls',
    'build.toolNone': 'Tool: none',
    'build.waitingForWorld': 'The build menu fills in once the server has spawned you.',
    'cb.antisepticHint': 'Protected against new infection for this long',
    'cb.apply': 'Apply',
    'cb.bleedRateHint': 'Blood units lost per second',
    'cb.bloodLabel': 'BLOOD',
    'cb.bodyParts': 'Body parts',
    'cb.cannotApply': 'Cannot apply',
    'cb.closeBody': 'Close body panel',
    'cb.closeContainer': 'Close container',
    'cb.containerClosed': 'The container is no longer open.',
    'cb.containerSlots': 'Container slots',
    'cb.contents': 'Contents',
    'cb.coreLabel': 'CORE',
    'cb.dragHint': 'Shift-click to move across · drag to place exactly · drag out to drop',
    'cb.injuries': 'Injuries',
    'cb.needsSplint': 'Unset: needs a splint',
    'cb.noSupplies': 'No medical supplies in your pack.',
    'cb.nothingToTreat': 'Nothing for it to act on right now.',
    'cb.pack': 'Pack',
    'cb.painLabel': 'PAIN',
    'cb.setButBroken': 'Set, but still broken',
    'cb.sortContainer': 'Sort Container',
    'cb.sortPack': 'Sort Pack',
    'cb.stillBusy': 'Still busy with the last treatment.',
    'cb.takeAll': 'Take All',
    'cb.takeAllHint': 'Take everything from the container',
    'cb.treatment': 'Treatment',
    'cb.treatments': 'Treatments',
    'cb.waitingForWorld': 'Waiting for the world…',
    'cb.woundClosed': 'The wound is closed',
    'cb.yourPack': 'Your Pack',
    'cb.yourSlots': 'Your inventory slots',
    'inv.drop': 'Drop',
    'inv.equipment': 'Equipment',
    'inv.slot.back': 'Back',
    'inv.slot.chest': 'Chest',
    'inv.slot.face': 'Face',
    'inv.slot.feet': 'Feet',
    'inv.slot.hands': 'Hands',
    'inv.slot.head': 'Head',
    'inv.slot.legs': 'Legs',
    'inv.slot.mainHand': 'Main Hand',
    'inv.slot.offHand': 'Off Hand',
    'inv.slotsLabel': 'Inventory slots',
    'inv.sort': 'Sort',
    'inv.unequip': 'Unequip',
    'inv.waitingForWorld': 'Waiting for the world…',
    'inv.worn': 'Worn',
    'map.biome': 'Biome',
    'map.centreOnMe': 'Centre on me',
    'map.chunk': 'Chunk',
    'map.inView': 'In view',
    'map.legend.building': 'Building',
    'map.legend.grass': 'Grass',
    'map.legend.road': 'Road',
    'map.legend.sand': 'Sand',
    'map.legend.snow': 'Snow',
    'map.legend.water': 'Water',
    'map.lifetime': 'Lifetime',
    'map.mapLabel': 'Local map of explored terrain',
    'map.stat.animalsKilled': 'Animals killed',
    'map.stat.cropsHarvested': 'Crops harvested',
    'map.stat.daysSurvived': 'Days survived',
    'map.stat.deaths': 'Deaths',
    'map.stat.itemsCrafted': 'Items crafted',
    'map.stat.playersKilled': 'Players killed',
    'map.stat.resourcesGathered': 'Resources gathered',
    'map.stat.structuresBuilt': 'Structures built',
    'map.stat.tilesTravelled': 'Tiles travelled',
    'map.stat.zombiesKilled': 'Zombies killed',
    'map.tile': 'Tile',
    'map.view': 'View',
    'map.waitingForWorld': 'Waiting for the world…',
    'map.zoomIn': 'Zoom in',
    'map.zoomOut': 'Zoom out',
    'menu.desktopOnly':
      'Single player launches a local server, which needs the desktop build. In the browser, start a server yourself and join it below:',
    'menu.join': 'JOIN',
    'menu.joinServer': 'Join a server',
    'menu.needAddress': 'Enter a server address.',
    'menu.passwordPlaceholder': 'password (optional)',
    'menu.play': 'PLAY',
    'menu.playerName': 'Player name',
    'menu.serverAddress': 'Server address',
    'menu.serverPassword': 'Server password',
    'menu.singlePlayer': 'Single player',
    'menu.tagline': 'Scavenge. Build. Last the night.',
    'menu.title': 'Survive',
    'menu.versions': 'protocol v{protocol} · content {content}',
    'menu.worldName': 'World name',
    'session.chatChannel': 'Chat channel',
    'session.chatInput': 'Chat message',
    'session.chatLog': 'Chat messages',
    'session.chatPending': 'Sent — not yet confirmed by the server',
    'session.chatPlaceholder': 'Say something…',
    'session.controls': 'Controls',
    'session.ctl.attack': 'Attack',
    'session.ctl.block': 'Block',
    'session.ctl.build': 'Build menu',
    'session.ctl.crouch': 'Crouch',
    'session.ctl.cycleHotbar': 'Cycle hotbar',
    'session.ctl.debug': 'Debug overlay',
    'session.ctl.down': 'Move down',
    'session.ctl.drop': 'Drop held item',
    'session.ctl.interact': 'Use / interact',
    'session.ctl.left': 'Move left',
    'session.ctl.pause': 'Pause / close panel',
    'session.ctl.reload': 'Reload',
    'session.ctl.right': 'Move right',
    'session.ctl.rotate': 'Rotate placement',
    'session.ctl.selectHotbar': 'Select hotbar slot',
    'session.ctl.sleep': 'Sleep',
    'session.ctl.sprint': 'Sprint',
    'session.ctl.up': 'Move up',
    'session.death.beaten': 'Beaten to death',
    'session.death.blast': 'Caught in a blast',
    'session.death.bleeding': 'Bled out',
    'session.death.burned': 'Burned alive',
    'session.death.cold': 'Froze to death',
    'session.death.exhaustion': 'Collapsed from exhaustion',
    'session.death.fall': 'Died from the fall',
    'session.death.heat': 'Died of heatstroke',
    'session.death.infection': 'Taken by infection',
    'session.death.pierce': 'Run through',
    'session.death.poison': 'Poisoned',
    'session.death.shot': 'Shot dead',
    'session.death.slash': 'Cut down',
    'session.death.starved': 'Starved to death',
    'session.death.suffocation': 'Suffocated',
    'session.death.thirst': 'Died of thirst',
    'session.death.unknown': 'Cause unknown',
    'session.death.zombie': 'Torn apart by the dead',
    'session.disconnect': 'Disconnect',
    'session.key.altLeft': 'Left Alt',
    'session.key.altRight': 'Right Alt',
    'session.key.ctrlLeft': 'Left Ctrl',
    'session.key.ctrlRight': 'Right Ctrl',
    'session.key.escape': 'Esc',
    'session.key.mouseLeft': 'Left mouse',
    'session.key.mouseRight': 'Right mouse',
    'session.key.shiftLeft': 'Left Shift',
    'session.key.shiftRight': 'Right Shift',
    'session.key.space': 'Space',
    'session.key.wheel': 'Mouse wheel',
    'session.paused': 'The simulation is paused.',
    'session.readyToRespawn': 'Ready to respawn',
    'session.respawn': 'Respawn',
    'session.respawnAtBed': 'Respawn at bed',
    'session.resume': 'Resume',
    'session.send': 'Send',
    'session.stat.animalsKilled': 'Animals killed',
    'session.stat.cropsHarvested': 'Crops harvested',
    'session.stat.daysSurvived': 'Days survived',
    'session.stat.deaths': 'Deaths',
    'session.stat.distanceWalked': 'Distance walked',
    'session.stat.itemsCrafted': 'Items crafted',
    'session.stat.playersKilled': 'Players killed',
    'session.stat.resourcesGathered': 'Resources gathered',
    'session.stat.structuresBuilt': 'Structures built',
    'session.stat.zombiesKilled': 'Zombies killed',
    'session.thisLife': 'This life',
    'session.waitingForPause': 'Waiting for the server to pause…',
    'cb.slotsUsed': '{used}/{total} slots',
    'inv.bag': 'Bag',
    'inv.dragHint': 'Drag to move · shift-drag for half · drag out to drop · right click for more',
    'inv.load': 'LOAD',
    'inv.slotsUsed': '{used} / {total} slots',
    'build.blocked.skill': 'needs {skill} {level}',
    'build.blocked.tool': 'needs a {tool}',
    'build.cost': 'Cost: {cost}',
    'build.costEntry': '{count}x {item}',
    'build.free': 'free',
    'build.hintGhost': 'The ghost turns red where the server would refuse it.',
    'build.hintPlace': 'Left click in the world to place · <b>T</b> rotates · <b>B</b> closes.',
    'build.needsSupport': 'needs support',
    'build.readyCount': '{ready} of {total} ready to build',
    'build.requiresSkill': 'Requires {skill} level {level}',
    'build.rowFacts': '{hp} HP · {seconds} to build · {width}x{height} tiles',
    'build.skill': 'Skill: {skill} {have}/{need}',
    'build.skillProgress': '{skill} {have}/{need}',
    'build.tool': 'Tool: {tool}',
    'build.toolMissing': 'You are carrying no {tool}',
    'build.toolUsing': 'Uses your {tool}',
    'cb.carried': '{carried}/{capacity} kg',
    'cb.healthy': 'healthy',
    'cb.slotAria': '{label} slot {index}: {item}',
    'cb.tempNormal': 'normal',
    'cb.treatmentFor': 'Treatment — {part}',
    'build.waitingWorld': 'Waiting for the world…',
    'session.ctl.interactKey': 'Interact',
    'craft.all': 'All',
    'craft.allStations': 'All stations',
    'craft.anyTag': 'any {tag}',
    'craft.atStation': 'at a {station}',
    'craft.availableHere': 'Available here',
    'craft.blocked.skill': 'needs {skill} level {level}',
    'craft.blocked.station': 'needs a {station} nearby',
    'craft.blocked.tools': 'needs {tools}',
    'craft.byHand': 'By hand',
    'craft.byHandLower': 'by hand',
    'craft.byHandNote': 'craftable by hand',
    'craft.cancel': 'Cancel',
    'craft.cat.ammo': 'Ammo',
    'craft.cat.armor': 'Armor',
    'craft.cat.basic': 'Basic',
    'craft.cat.building': 'Building',
    'craft.cat.cooking': 'Cooking',
    'craft.cat.farming': 'Farming',
    'craft.cat.medical': 'Medical',
    'craft.cat.smelting': 'Smelting',
    'craft.cat.textiles': 'Textiles',
    'craft.cat.tools': 'Tools',
    'craft.cat.weapons': 'Weapons',
    'craft.categories': 'Recipe categories',
    'craft.filterByStation': 'Filter by station',
    'craft.haveSchematic': 'You are carrying the schematic',
    'craft.inProgress': 'In progress',
    'craft.inReach': 'In reach:',
    'craft.needSchematic': 'Find the schematic to learn this',
    'craft.needsHeat': 'needs heat',
    'craft.noMatch': 'No recipes match that filter.',
    'craft.noStation': 'No station in reach — hand recipes only.',
    'craft.nothingCrafting': 'Nothing being crafted.',
    'craft.quantity': 'Quantity',
    'craft.reason.dead': 'you are dead',
    'craft.reason.lowFuel': 'low on fuel',
    'craft.reason.noMaterials': 'not enough materials',
    'craft.reason.notLearned': 'you have not learned that recipe',
    'craft.reason.notLit': 'the station is not lit',
    'craft.reason.packFull': 'your pack may be full',
    'craft.reason.queueFull': 'that crafting queue is full',
    'craft.recipes': 'Recipes',
    'craft.searchLabel': 'Search recipes',
    'craft.searchPlaceholder': 'Search recipes or outputs',
    'craft.selectPrompt': 'Select a recipe to craft it.',
    'craft.skillProgress': '{skill} {have}/{need}',
    'craft.toolMissing': 'You have no {tool}',
    'craft.toolUsing': 'Using your {tool}',
    'craft.waitingForWorld': 'Waiting for the world…',
    'build.buildableCount': '{ready} of {total} buildable',
    'craft.schematicChip': 'schematic',
    'damage.bleed': 'bleed',
    'damage.blunt': 'blunt',
    'damage.bullet': 'bullet',
    'damage.cold': 'cold',
    'damage.dehydration': 'dehydration',
    'damage.exhaustion': 'exhaustion',
    'damage.explosive': 'explosive',
    'damage.fall': 'fall',
    'damage.fire': 'fire',
    'damage.heat': 'heat',
    'damage.infection': 'infection',
    'damage.pierce': 'pierce',
    'damage.poison': 'poison',
    'damage.slash': 'slash',
    'damage.starvation': 'starvation',
    'damage.zombieBite': 'zombie bite',
    'station.anvil': 'anvil',
    'station.campfire': 'campfire',
    'station.chemistry': 'chemistry',
    'station.component': 'component',
    'station.cookingPot': 'cooking pot',
    'station.furnace': 'furnace',
    'station.grindstone': 'grindstone',
    'station.loom': 'loom',
    'station.resource': 'resource',
    'station.workbench': 'workbench',
    'tool.axe': 'axe',
    'tool.fishingRod': 'fishing rod',
    'tool.hammer': 'hammer',
    'tool.hoe': 'hoe',
    'tool.knife': 'knife',
    'tool.lighter': 'lighter',
    'tool.pickaxe': 'pickaxe',
    'tool.saw': 'saw',
    'tool.shovel': 'shovel',
    'tool.sickle': 'sickle',
    'tool.wateringCan': 'watering can',
    'tool.workbench': 'workbench',
    'tool.wrench': 'wrench',
    'medical.bandage': 'bandage',
    'medical.disinfect': 'disinfect',
    'medical.injection': 'injection',
    'medical.pill': 'pill',
    'medical.splint': 'splint',
    'medical.suture': 'suture',
    'toast.crafted': 'Crafted {item}.',
    'toast.levelUp': '{skill} level {level}',
    'toast.pickedUp': '+{count} {item}',
    'tip.condition': 'Condition {percent}%',
    'tip.crawling': 'Crawling',
    'tip.damage': '{amount} {type} damage',
    'tip.depleted': 'Depleted',
    'tip.food': 'Food +{amount}',
    'tip.freshness': 'Freshness {percent}%',
    'tip.illnessRisk': 'Risk of illness: {percent}%',
    'tip.magazine': 'Magazine {rounds}',
    'tip.medical': 'Medical: {kind}',
    'tip.needsTool': 'Needs {tools} (tier {tier})',
    'tip.needsToolMissing': 'Needs {tools} (tier {tier}) - you have none',
    'tip.protects': 'Protects: {parts}',
    'tip.protectsNothing': 'nothing',
    'tip.reach': 'Reach {range}, {seconds}s swing',
    'tip.roleBed': 'bed',
    'tip.roleDoorClosed': 'door (closed)',
    'tip.roleDoorOpen': 'door (open)',
    'tip.rolePlot': 'farm plot',
    'tip.roleStation': '{kind} station',
    'tip.roleStorage': 'storage',
    'tip.tool': 'Tool: {kinds} (tier {tier})',
    'tip.trains': 'Trains {skill}',
    'tip.twoHanded': 'Two-handed',
    'tip.underConstruction': 'Under construction {percent}%',
    'tip.warmth': 'Warmth +{amount}',
    'tip.water': 'Water +{amount}',
    'tip.weight': 'Weight {kg} kg',
    'tip.yields': 'Yields {list}',
    'vital.blood': 'BLOOD',
    'vital.food': 'FOOD',
    'vital.hp': 'HP',
    'vital.rest': 'REST',
    'vital.stamina': 'STAM',
    'vital.water': 'WATER',
  },
};
