import type { UiStringTable } from './types';

/**
 * English interface text.
 *
 * Everything the player reads that is *not* a piece of game content: panel titles, button
 * labels, the messages the simulation asks for by code, and the wording for a refused
 * command. Content names live in `@survive/game-data`'s own table, next to the content
 * they describe; this one lives next to the interface it belongs to, so a change to either
 * does not drag the other along.
 *
 * `notify` and `reject` are keyed by what the *server* sends. The server names a message
 * and supplies its values - it never sends a finished sentence - because word order, where
 * a number goes and how a thing is pluralised are decisions the reader's language makes.
 */
export const EN_UI: UiStringTable = {
  /** Messages the simulation raises, keyed by the code it sends. */
  notify: {
    'notify.addedToStation': 'Added {count} x {item} to the {station}.',
    'notify.alreadyTidy': 'Already tidy.',
    'notify.bedGone': 'Your bed is gone. You wake where you started.',
    'notify.bedOccupied': 'Someone else is in your bed. You wake where you started.',
    'notify.bedSet': 'You will wake up here.',
    'notify.bedWrecked': 'Your bed is wrecked. You wake where you started.',
    'notify.biteTurning': 'The bite is turning. There is not much time.',
    'notify.bleedingOut': 'You are bleeding out.',
    'notify.bloodLossWarn': 'You have lost a lot of blood. Stop the bleeding.',
    'notify.botchedTreatment': 'You botch the {treatment} on your {part}.',
    'notify.filledDirtyWater': 'Filled with dirty water.',
    'notify.foodPoisoning': 'That was a mistake. Your stomach turns.',
    'notify.heatstroke': 'Heatstroke. Get out of the sun and drink.',
    'notify.hypothermia': 'Hypothermia. You need warmth now.',
    'notify.infectionSystemic': 'The infection is systemic. You need antibiotics.',
    'notify.inventoryFull': 'Your inventory filled up.',
    'notify.locked': 'Locked.',
    'notify.need.fatigue.critical': 'You are collapsing from exhaustion.',
    'notify.need.fatigue.urgent': 'You can barely keep your eyes open.',
    'notify.need.fatigue.warn': 'You are tired.',
    'notify.need.hunger.critical': 'You are starving to death.',
    'notify.need.hunger.urgent': 'You are famished. Find food.',
    'notify.need.hunger.warn': 'You are getting hungry.',
    'notify.need.thirst.critical': 'You are dying of thirst.',
    'notify.need.thirst.urgent': 'You are badly dehydrated. Find water.',
    'notify.need.thirst.warn': 'Your throat is dry.',
    'notify.noRoomDropped': 'No room - it fell on the ground.',
    'notify.noVessel': 'Nothing to carry water in.',
    'notify.painBlackout': 'The pain whites everything out.',
    'notify.partMended': 'Your {part} has mended.',
    'notify.plantOnPlot': 'Plant {crop} on a tilled plot.',
    'notify.plotCleared': 'Cleared the plot.',
    'notify.plotClearedOf': 'Cleared the plot of {crop}.',
    'notify.readyToPlace': '{structure} ready to place.',
    'notify.sleep.start': 'You settle down to sleep.',
    'notify.someItemsDropped': 'Some items would not fit and fell on the ground.',
    'notify.structureFinished': '{structure} finished.',
    'notify.tooExhausted': 'Too exhausted to attack.',
    'notify.unlocked': 'Unlocked.',
    'notify.wake.bedLost': 'Your bed is gone. You wake on the ground.',
    'notify.wake.commanded': 'You get up.',
    'notify.wake.died': 'You died in your sleep.',
    'notify.wake.moved': 'You stir and get up.',
    'notify.wake.rested': 'You wake up rested.',
    'notify.wake.threat': 'Something moving nearby drags you awake.',
    'notify.weatherSet': 'Weather set to {weather} ({intensity}) for {hours}h.',
    'notify.woundInfected': 'A wound has gone bad. You are running a fever.',
  },
  /**
   * Why a command was refused.
   *
   * Keyed by the reason string the simulation sends. Those reasons are a mix of short
   * codes and English phrases, and they used to be shown to the player raw - so a failed
   * gather flashed `toolIneffective` on screen. Keying by the raw value keeps the server
   * untouched while giving every one of them a sentence a person would write.
   */
  reject: {
    'already asleep': 'Already asleep',
    'already tilled': 'Already tilled',
    'bad target tile': 'Nothing there to act on.',
    badRotation: 'That will not fit facing this way.',
    blueprint: 'Blueprint',
    'both hands are on that weapon': 'Both hands are on that weapon',
    busy: 'You are busy.',
    'cannot sort equipment': 'Cannot sort equipment',
    'cannot split equipment': 'Cannot split equipment',
    'cannot split off the whole stack': 'Cannot split off the whole stack',
    'container is not open': 'Container is not open',
    cooldown: 'Not ready yet.',
    dead: 'You are dead.',
    depleted: 'There is nothing left to take.',
    'destination is full': 'Destination is full',
    'destination slot is occupied': 'Destination slot is occupied',
    'destination stack is full': 'Destination stack is full',
    'farm plots are unavailable': 'Farm plots are unavailable',
    indestructible: 'That cannot be destroyed.',
    'invalid code': 'That command made no sense.',
    'invalid count': 'Invalid count',
    'invalid destination slot': 'Invalid destination slot',
    'invalid hotbar slot': 'Invalid hotbar slot',
    'invalid inventory slot': 'Invalid inventory slot',
    'invalid slot': 'Invalid slot',
    'invalid source slot': 'Invalid source slot',
    'it is already on the ground': 'It is already on the ground',
    'it is locked': 'It is locked',
    'it is not ready yet': 'It is not ready yet',
    locked: 'It is locked.',
    'malformed container ref': 'Malformed container ref',
    missingMaterials: 'You do not have the materials.',
    missingTool: 'You do not have the right tool.',
    'no free slot to split into': 'No free slot to split into',
    'no item in that slot': 'No item in that slot',
    'no line of sight': 'No line of sight',
    'no room in your inventory': 'No room in your inventory',
    'no seed selected': 'No seed selected',
    'no such item container': 'No such item container',
    'no such structure': 'No such structure',
    noLineOfSight: 'You cannot reach it from here.',
    'not with those things so close': 'Not with those things so close',
    notADoor: 'That is not a door.',
    notBuildable: 'That cannot be built yet.',
    notDamaged: 'It is not damaged.',
    notOwner: 'That is not yours.',
    'nothing equipped there': 'Nothing equipped there',
    'nothing happens': 'Nothing happens',
    'nothing is growing here': 'Nothing is growing here',
    'nothing to clear': 'Nothing to clear',
    'nothing to sort there': 'Nothing to sort there',
    'nothing to split there': 'Nothing to split there',
    'nothing to use there': 'Nothing to use there',
    'out of reach': 'Out of reach',
    outOfRange: 'Too far away.',
    'paused must be a boolean': 'Paused must be a boolean',
    'pausing is not allowed on this server': 'Pausing is not allowed on this server',
    'slot is empty': 'Slot is empty',
    'someone is already in it': 'Someone is already in it',
    'something is already built here': 'Something is already built here',
    'something is in the way': 'Something is in the way',
    'source slot is empty': 'Source slot is empty',
    'still busy': 'Still busy',
    'that cannot be equipped': 'That cannot be equipped',
    'that cannot be placed': 'That cannot be placed',
    'that cannot be worn there': 'That cannot be worn there',
    'that container is not being worn': 'That container is not being worn',
    'that has nowhere to fit a lock': 'That has nowhere to fit a lock',
    'that is not a usable bed': 'That is not a usable bed',
    'that is not yours yet': 'That is not yours yet',
    'that item is gone': 'That item is gone',
    'that structure has no container': 'That structure has no container',
    'that will not grow': 'That will not grow',
    'the ground is blocked': 'The ground is blocked',
    'the ground is not a source': 'The ground is not a source',
    'the ground is not tilled': 'The ground is not tilled',
    'the soil is already soaked': 'The soil is already soaked',
    'there is no plot here': 'There is no plot here',
    'this ground cannot be tilled': 'This ground cannot be tilled',
    'this plant is spent': 'This plant is spent',
    'this soil needs nothing': 'This soil needs nothing',
    'too far away': 'Too far away',
    'too far from the bed': 'Too far from the bed',
    toolIneffective: 'Your tool is not good enough for that.',
    'unequip that first': 'Unequip that first',
    'unknown body part': 'Unknown body part',
    'unknown container kind': 'Unknown container kind',
    'unknown crop': 'Unknown crop',
    'unknown equipment slot': 'Unknown equipment slot',
    'unknown farm action': 'Unknown farm action',
    'unknown item': 'Unknown item',
    'unknown seed': 'Unknown seed',
    unknownNode: 'That is gone.',
    unknownStructure: 'That structure is gone.',
    'you are dead': 'You are dead',
    'you are not asleep': 'You are not asleep',
    'you are not dead': 'You are not dead',
    'you do not own that': 'You do not own that',
    'you have no fertilizer': 'You have no fertilizer',
    'you need a hoe': 'You need a hoe',
    'you need a watering can or a full vessel': 'You need a watering can or a full vessel',
  },
  /** Interface chrome: titles, labels, buttons, prompts. */
  ui: {
    'hotbar.hand': 'HAND',
    'panel.body': 'Body',
    'panel.build': 'Build',
    'panel.chat': 'Chat',
    'panel.container': 'Container',
    'panel.crafting': 'Crafting',
    'panel.death': 'You died',
    'panel.debug': 'Debug',
    'panel.inventory': 'Inventory',
    'panel.map': 'Map',
    'panel.paused': 'Paused',
    'panel.skills': 'Skills',
    'prompt.closeDoor': 'close {name}',
    'prompt.harvest': 'harvest {name}',
    'prompt.openDoor': 'open {name}',
    'prompt.pickUp': 'pick up {name}',
    'prompt.search': 'search {name}',
    'prompt.sleep': 'sleep in {name}',
    'prompt.tend': 'tend {name}',
    'prompt.useStation': 'use {name}',
    'tip.byHand': 'Harvested by hand',
    'effect.well_fed': 'Well Fed',
    'effect.hydrated': 'Hydrated',
    'effect.well_rested': 'Well Rested',
    'effect.painkiller': 'Painkiller',
    'effect.antibiotic': 'Antibiotic',
    'effect.antiseptic': 'Antiseptic',
    'effect.adrenaline': 'Adrenaline',
    'effect.bandaged': 'Bandaged',
    'effect.fever': 'Fever',
    'effect.poisoned': 'Poisoned',
    'effect.food_poisoning': 'Food Poisoning',
    'effect.bleeding': 'Bleeding',
    'effect.exhausted': 'Exhausted',
    'effect.overencumbered': 'Overencumbered',
    'effect.cold': 'Cold',
    'effect.hypothermia': 'Hypothermia',
    'effect.hot': 'Hot',
    'effect.heatstroke': 'Heatstroke',
    'effect.stunned': 'Stunned',
    'effect.wet': 'Wet',
    'effect.sepsis': 'Sepsis',
    'effect.zombification': 'Zombification',
    'bodyPart.head': 'Head',
    'bodyPart.torso': 'Torso',
    'bodyPart.leftArm': 'Left Arm',
    'bodyPart.rightArm': 'Right Arm',
    'bodyPart.leftLeg': 'Left Leg',
    'bodyPart.rightLeg': 'Right Leg',
    'chip.fractured': '{part} fractured',
    'skill.melee': 'Melee',
    'skill.ranged': 'Ranged',
    'skill.woodcutting': 'Woodcutting',
    'skill.mining': 'Mining',
    'skill.foraging': 'Foraging',
    'skill.farming': 'Farming',
    'skill.crafting': 'Crafting',
    'skill.building': 'Building',
    'skill.cooking': 'Cooking',
    'skill.medicine': 'Medicine',
    'skill.athletics': 'Athletics',
    'skill.stealth': 'Stealth',
    'entity.player': 'Player',
    'entity.zombie': 'Zombie',
    'entity.animal': 'Animal',
    'entity.item': 'Item',
    'entity.projectile': 'Projectile',
    'entity.structure': 'Structure',
    'entity.node': 'Node',
    'toast.crafted': 'Crafted {item}.',
    'toast.levelUp': '{skill} level {level}',
    'toast.pickedUp': '+{count} {item}',
    'tip.condition': 'Condition {percent}%',
    'tip.crawling': 'Crawling',
    'tip.damage': '{amount} {type} damage',
    'tip.depleted': 'Depleted',
    'tip.food': 'Food +{amount}',
    'tip.freshness': 'Freshness {percent}%',
    'tip.illnessRisk': 'Risk of illness: {percent}%',
    'tip.magazine': 'Magazine {rounds}',
    'tip.medical': 'Medical: {kind}',
    'tip.needsTool': 'Needs {tools} (tier {tier})',
    'tip.needsToolMissing': 'Needs {tools} (tier {tier}) - you have none',
    'tip.protects': 'Protects: {parts}',
    'tip.protectsNothing': 'nothing',
    'tip.reach': 'Reach {range}, {seconds}s swing',
    'tip.roleBed': 'bed',
    'tip.roleDoorClosed': 'door (closed)',
    'tip.roleDoorOpen': 'door (open)',
    'tip.rolePlot': 'farm plot',
    'tip.roleStation': '{kind} station',
    'tip.roleStorage': 'storage',
    'tip.tool': 'Tool: {kinds} (tier {tier})',
    'tip.trains': 'Trains {skill}',
    'tip.twoHanded': 'Two-handed',
    'tip.underConstruction': 'Under construction {percent}%',
    'tip.warmth': 'Warmth +{amount}',
    'tip.water': 'Water +{amount}',
    'tip.weight': 'Weight {kg} kg',
    'tip.yields': 'Yields {list}',
    'vital.blood': 'BLOOD',
    'vital.food': 'FOOD',
    'vital.hp': 'HP',
    'vital.rest': 'REST',
    'vital.stamina': 'STAM',
    'vital.water': 'WATER',
  },
};
