import type { UiStringTable } from './types';

/**
 * Korean interface text.
 *
 * The keys are fixed by `en.ts` and by what the server sends; only the values differ. Two
 * things this language makes obvious that English hid:
 *
 * - Word order. `Added 3 x Log to the campfire` becomes `모닥불에 통나무 3개를 넣었습니다` -
 *   the station moves to the front and the verb to the end. That is why the simulation sends
 *   a code and its values instead of a finished sentence.
 * - Particles. `{crop}을(는)` cannot be resolved without knowing whether the noun ends in a
 *   consonant, and the noun is a translated item name. Both forms are written out, which is
 *   what Korean interfaces conventionally do rather than inflecting at runtime.
 */
export const KO_UI: UiStringTable = {
  notify: {
    'notify.addedToStation': '{station}에 {item} {count}개를 넣었습니다.',
    'notify.alreadyTidy': '이미 정리되어 있습니다.',
    'notify.bedGone': '침대가 없어졌습니다. 처음 자리에서 깨어납니다.',
    'notify.bedOccupied': '침대에 다른 사람이 있습니다. 처음 자리에서 깨어납니다.',
    'notify.bedSet': '이제 여기서 깨어납니다.',
    'notify.bedWrecked': '침대가 부서졌습니다. 처음 자리에서 깨어납니다.',
    'notify.biteTurning': '물린 자리가 변하고 있습니다. 시간이 많지 않습니다.',
    'notify.bleedingOut': '과다출혈로 죽어가고 있습니다.',
    'notify.bloodLossWarn': '피를 많이 흘렸습니다. 지혈해야 합니다.',
    'notify.botchedTreatment': '{part}의 {treatment}을 망쳤습니다.',
    'notify.filledDirtyWater': '탁한 물을 채웠습니다.',
    'notify.foodPoisoning': '잘못 먹었습니다. 속이 뒤집힙니다.',
    'notify.heatstroke': '열사병입니다. 그늘로 들어가 물을 마셔야 합니다.',
    'notify.hypothermia': '저체온증입니다. 당장 몸을 녹여야 합니다.',
    'notify.infectionSystemic': '감염이 전신으로 퍼졌습니다. 항생제가 필요합니다.',
    'notify.inventoryFull': '인벤토리가 가득 찼습니다.',
    'notify.locked': '잠갔습니다.',
    'notify.need.fatigue.critical': '탈진으로 쓰러지고 있습니다.',
    'notify.need.fatigue.urgent': '눈을 뜨고 있기가 힘듭니다.',
    'notify.need.fatigue.warn': '피곤합니다.',
    'notify.need.hunger.critical': '굶어 죽어가고 있습니다.',
    'notify.need.hunger.urgent': '허기가 심합니다. 먹을 것을 찾아야 합니다.',
    'notify.need.hunger.warn': '배가 고파집니다.',
    'notify.need.thirst.critical': '갈증으로 죽어가고 있습니다.',
    'notify.need.thirst.urgent': '심하게 탈수되었습니다. 물을 찾아야 합니다.',
    'notify.need.thirst.warn': '목이 마릅니다.',
    'notify.noRoomDropped': '자리가 없어 바닥에 떨어졌습니다.',
    'notify.noVessel': '물을 담을 것이 없습니다.',
    'notify.painBlackout': '고통에 눈앞이 하얘집니다.',
    'notify.partMended': '{part}이(가) 나았습니다.',
    'notify.plantOnPlot': '{crop}은(는) 갈아둔 밭에 심으세요.',
    'notify.plotCleared': '밭을 비웠습니다.',
    'notify.plotClearedOf': '밭의 {crop}을(를) 치웠습니다.',
    'notify.readyToPlace': '{structure}을(를) 놓을 수 있습니다.',
    'notify.sleep.start': '자리를 잡고 잠에 듭니다.',
    'notify.someItemsDropped': '들어가지 않은 물건들이 바닥에 떨어졌습니다.',
    'notify.structureFinished': '{structure}이(가) 완성되었습니다.',
    'notify.tooExhausted': '지쳐서 공격할 수 없습니다.',
    'notify.unlocked': '잠금을 풀었습니다.',
    'notify.wake.bedLost': '침대가 없어졌습니다. 맨땅에서 깨어납니다.',
    'notify.wake.commanded': '일어납니다.',
    'notify.wake.died': '자다가 죽었습니다.',
    'notify.wake.moved': '몸을 뒤척이다 일어납니다.',
    'notify.wake.rested': '푹 자고 일어났습니다.',
    'notify.wake.threat': '가까이서 움직이는 소리에 잠이 깼습니다.',
    'notify.weatherSet': '날씨를 {hours}시간 동안 {weather}({intensity})로 설정했습니다.',
    'notify.woundInfected': '상처가 곪았습니다. 열이 오릅니다.',
  },
  reject: {
    'already asleep': '이미 잠들어 있습니다.',
    'already tilled': '이미 갈아둔 땅입니다.',
    'bad target tile': '그곳에는 다룰 것이 없습니다.',
    badRotation: '이 방향으로는 들어가지 않습니다.',
    blueprint: '아직 청사진입니다.',
    'both hands are on that weapon': '양손 무기를 들고 있습니다.',
    busy: '지금은 다른 일을 하고 있습니다.',
    'cannot sort equipment': '착용 중인 장비는 정리할 수 없습니다.',
    'cannot split equipment': '착용 중인 장비는 나눌 수 없습니다.',
    'cannot split off the whole stack': '묶음 전체를 나눌 수는 없습니다.',
    'container is not open': '열어둔 보관함이 없습니다.',
    cooldown: '아직 준비되지 않았습니다.',
    dead: '죽은 상태입니다.',
    depleted: '더 가져갈 것이 없습니다.',
    'destination is full': '옮길 곳이 가득 찼습니다.',
    'destination slot is occupied': '그 칸은 이미 차 있습니다.',
    'destination stack is full': '그 묶음은 가득 찼습니다.',
    'farm plots are unavailable': '이 서버에서는 농사를 지을 수 없습니다.',
    indestructible: '파괴할 수 없습니다.',
    'invalid code': '알 수 없는 명령입니다.',
    'invalid count': '수량이 잘못되었습니다.',
    'invalid destination slot': '옮길 칸이 잘못되었습니다.',
    'invalid hotbar slot': '핫바 칸이 잘못되었습니다.',
    'invalid inventory slot': '인벤토리 칸이 잘못되었습니다.',
    'invalid slot': '칸이 잘못되었습니다.',
    'invalid source slot': '가져올 칸이 잘못되었습니다.',
    'it is already on the ground': '이미 바닥에 있습니다.',
    'it is locked': '잠겨 있습니다.',
    'it is not ready yet': '아직 다 되지 않았습니다.',
    locked: '잠겨 있습니다.',
    'malformed container ref': '보관함 지정이 잘못되었습니다.',
    missingMaterials: '재료가 부족합니다.',
    missingTool: '알맞은 도구가 없습니다.',
    'no free slot to split into': '나눠 담을 빈 칸이 없습니다.',
    'no item in that slot': '그 칸은 비어 있습니다.',
    'no line of sight': '시야가 닿지 않습니다.',
    'no room in your inventory': '인벤토리에 자리가 없습니다.',
    'no seed selected': '심을 씨앗을 고르지 않았습니다.',
    'no such item container': '그런 보관함이 없습니다.',
    'no such structure': '그런 건축물이 없습니다.',
    noLineOfSight: '무언가에 가로막혀 있습니다.',
    'not with those things so close': '너무 가까이 있는 것들 때문에 안 됩니다.',
    notADoor: '문이 아닙니다.',
    notBuildable: '아직 만들 수 없습니다.',
    notDamaged: '손상되지 않았습니다.',
    notOwner: '내 것이 아닙니다.',
    'nothing equipped there': '그 부위에는 아무것도 착용하지 않았습니다.',
    'nothing happens': '아무 일도 일어나지 않습니다.',
    'nothing is growing here': '여기에는 자라는 것이 없습니다.',
    'nothing to clear': '치울 것이 없습니다.',
    'nothing to sort there': '정리할 것이 없습니다.',
    'nothing to split there': '나눌 것이 없습니다.',
    'nothing to use there': '쓸 것이 없습니다.',
    'out of reach': '손이 닿지 않습니다.',
    outOfRange: '너무 멉니다.',
    'paused must be a boolean': '일시정지 값이 잘못되었습니다.',
    'pausing is not allowed on this server': '이 서버에서는 일시정지할 수 없습니다.',
    'slot is empty': '빈 칸입니다.',
    'someone is already in it': '이미 누가 쓰고 있습니다.',
    'something is already built here': '여기에는 이미 뭔가 세워져 있습니다.',
    'something is in the way': '무언가 막고 있습니다.',
    'source slot is empty': '가져올 칸이 비어 있습니다.',
    'still busy': '아직 손이 바쁩니다.',
    'that cannot be equipped': '착용할 수 없는 물건입니다.',
    'that cannot be placed': '놓을 수 없는 물건입니다.',
    'that cannot be worn there': '그 부위에는 착용할 수 없습니다.',
    'that container is not being worn': '착용 중인 보관함이 아닙니다.',
    'that has nowhere to fit a lock': '자물쇠를 달 곳이 없습니다.',
    'that is not a usable bed': '쓸 수 있는 침대가 아닙니다.',
    'that is not yours yet': '아직 내 것이 아닙니다.',
    'that item is gone': '그 물건은 사라졌습니다.',
    'that structure has no container': '그 건축물에는 보관 공간이 없습니다.',
    'that will not grow': '그것은 자라지 않습니다.',
    'the ground is blocked': '바닥이 막혀 있습니다.',
    'the ground is not a source': '여기서는 물을 뜰 수 없습니다.',
    'the ground is not tilled': '갈지 않은 땅입니다.',
    'the soil is already soaked': '흙이 이미 충분히 젖었습니다.',
    'there is no plot here': '여기에는 밭이 없습니다.',
    'this ground cannot be tilled': '갈 수 없는 땅입니다.',
    'this plant is spent': '이 작물은 다 거뒀습니다.',
    'this soil needs nothing': '이 흙에는 더 필요한 것이 없습니다.',
    'too far away': '너무 멉니다.',
    'too far from the bed': '침대에서 너무 멉니다.',
    toolIneffective: '이 도구로는 어림도 없습니다.',
    'unequip that first': '먼저 벗어야 합니다.',
    'unknown body part': '알 수 없는 부위입니다.',
    'unknown container kind': '알 수 없는 보관함 종류입니다.',
    'unknown crop': '알 수 없는 작물입니다.',
    'unknown equipment slot': '알 수 없는 장비 칸입니다.',
    'unknown farm action': '알 수 없는 농사 동작입니다.',
    'unknown item': '알 수 없는 물건입니다.',
    'unknown seed': '알 수 없는 씨앗입니다.',
    unknownNode: '사라졌습니다.',
    unknownStructure: '그 건축물은 사라졌습니다.',
    'you are dead': '죽은 상태입니다.',
    'you are not asleep': '잠들어 있지 않습니다.',
    'you are not dead': '죽지 않았습니다.',
    'you do not own that': '내 것이 아닙니다.',
    'you have no fertilizer': '비료가 없습니다.',
    'you need a hoe': '괭이가 필요합니다.',
    'you need a watering can or a full vessel': '물뿌리개나 물이 든 그릇이 필요합니다.',
  },
  ui: {
    'bodyPart.head': '머리',
    'bodyPart.leftArm': '왼팔',
    'bodyPart.leftLeg': '왼다리',
    'bodyPart.rightArm': '오른팔',
    'bodyPart.rightLeg': '오른다리',
    'bodyPart.torso': '몸통',
    'biome.0': '초원',
    'biome.1': '숲',
    'biome.2': '깊은 숲',
    'biome.3': '바위 언덕',
    'biome.4': '해변',
    'biome.5': '호수',
    'biome.6': '습지',
    'biome.7': '시가지',
    'biome.8': '농지',
    'biome.9': '도로',
    'map.following': '따라가는 중',
    'map.freeLook': '자유 시점',
    'map.nothingExplored': '탐색한 곳 없음',
    'map.pxPerTile': '{scale} px/타일',
    'map.unknownBiome': '알 수 없음',
    'map.viewLine': '{scale} px/타일 · {chunks} 청크 · {mode}',
    'build.blocksMovement': '이동을 막음',
    'build.cat.beds': '침구',
    'build.cat.defences': '방어',
    'build.cat.doors': '문',
    'build.cat.farming': '농사',
    'build.cat.floors': '바닥',
    'build.cat.foundations': '기초',
    'build.cat.furniture': '가구',
    'build.cat.lighting': '조명',
    'build.cat.other': '기타',
    'build.cat.stations': '작업대',
    'build.cat.storage': '보관',
    'build.cat.walls': '벽',
    'build.cat.windows': '창',
    'build.clear': '해제',
    'build.clearHint': '건축 선택 해제',
    'build.collapseAll': '모두 접기',
    'build.expandAll': '모두 펼치기',
    'build.mustTouch': '기존 벽이나 기초에 붙어야 합니다',
    'build.nothingSelected': '선택된 것이 없습니다. 아래에서 하나 고르고 월드를 클릭하세요.',
    'build.rotateCcw': '반시계로 회전 (Shift+T)',
    'build.rotateCcwHint': '선택한 것을 반시계로 회전',
    'build.rotateCw': '시계로 회전 (T)',
    'build.rotateCwHint': '선택한 것을 시계로 회전',
    'build.selectionControls': '선택 조작',
    'build.toolNone': '도구: 없음',
    'build.waitingForWorld': '서버가 캐릭터를 만들면 건축 메뉴가 채워집니다.',
    'cb.antisepticHint': '이 시간 동안 새 감염을 막습니다',
    'cb.apply': '적용',
    'cb.bleedRateHint': '초당 잃는 혈액량',
    'cb.bloodLabel': '혈액',
    'cb.bodyParts': '신체 부위',
    'cb.cannotApply': '적용 불가',
    'cb.closeBody': '신체 창 닫기',
    'cb.closeContainer': '보관함 닫기',
    'cb.containerClosed': '보관함이 더 이상 열려 있지 않습니다.',
    'cb.containerSlots': '보관함 칸',
    'cb.contents': '내용물',
    'cb.coreLabel': '체온',
    'cb.dragHint': 'Shift+클릭으로 옮기기 · 끌어서 정확히 놓기 · 밖으로 끌어 버리기',
    'cb.injuries': '부상',
    'cb.needsSplint': '고정 안 됨: 부목이 필요합니다',
    'cb.noSupplies': '가방에 의료품이 없습니다.',
    'cb.nothingToTreat': '지금 처치할 것이 없습니다.',
    'cb.pack': '가방',
    'cb.painLabel': '고통',
    'cb.setButBroken': '고정했지만 아직 부러진 상태',
    'cb.sortContainer': '보관함 정리',
    'cb.sortPack': '가방 정리',
    'cb.stillBusy': '이전 처치가 아직 끝나지 않았습니다.',
    'cb.takeAll': '전부 가져오기',
    'cb.takeAllHint': '보관함의 모든 것을 가져오기',
    'cb.treatment': '처치',
    'cb.treatments': '처치',
    'cb.waitingForWorld': '월드를 기다리는 중…',
    'cb.woundClosed': '상처가 닫혔습니다',
    'cb.yourPack': '내 가방',
    'cb.yourSlots': '내 인벤토리 칸',
    'chip.fractured': '{part} 골절',
    'effect.adrenaline': '아드레날린',
    'effect.antibiotic': '항생제',
    'effect.antiseptic': '소독',
    'effect.bandaged': '붕대 감음',
    'effect.bleeding': '출혈',
    'effect.cold': '추위',
    'effect.exhausted': '탈진',
    'effect.fever': '발열',
    'effect.food_poisoning': '식중독',
    'effect.heatstroke': '열사병',
    'effect.hot': '더위',
    'effect.hydrated': '수분 충분',
    'effect.hypothermia': '저체온증',
    'effect.overencumbered': '과적',
    'effect.painkiller': '진통제',
    'effect.poisoned': '중독',
    'effect.sepsis': '패혈증',
    'effect.stunned': '기절',
    'effect.well_fed': '배부름',
    'effect.well_rested': '잘 쉼',
    'effect.wet': '젖음',
    'effect.zombification': '좀비화',
    'entity.animal': '동물',
    'entity.item': '아이템',
    'entity.node': '자원',
    'entity.player': '플레이어',
    'entity.projectile': '발사체',
    'entity.structure': '건축물',
    'entity.zombie': '좀비',
    'hotbar.hand': '맨손',
    'inv.drop': '버리기',
    'inv.equipment': '장비',
    'inv.slot.back': '등',
    'inv.slot.chest': '상체',
    'inv.slot.face': '얼굴',
    'inv.slot.feet': '발',
    'inv.slot.hands': '손',
    'inv.slot.head': '머리',
    'inv.slot.legs': '하체',
    'inv.slot.mainHand': '주손',
    'inv.slot.offHand': '보조손',
    'inv.slotsLabel': '인벤토리 칸',
    'inv.sort': '정리',
    'inv.unequip': '해제',
    'inv.waitingForWorld': '월드를 기다리는 중…',
    'inv.worn': '착용 중',
    'map.biome': '생물군계',
    'map.centreOnMe': '내 위치로',
    'map.chunk': '청크',
    'map.inView': '화면 안',
    'map.legend.building': '건물',
    'map.legend.grass': '풀',
    'map.legend.road': '길',
    'map.legend.sand': '모래',
    'map.legend.snow': '눈',
    'map.legend.water': '물',
    'map.lifetime': '누적',
    'map.mapLabel': '탐색한 지형의 지역 지도',
    'map.stat.animalsKilled': '잡은 동물',
    'map.stat.cropsHarvested': '수확한 작물',
    'map.stat.daysSurvived': '생존 일수',
    'map.stat.deaths': '사망 횟수',
    'map.stat.itemsCrafted': '제작한 아이템',
    'map.stat.playersKilled': '죽인 플레이어',
    'map.stat.resourcesGathered': '채집한 자원',
    'map.stat.structuresBuilt': '지은 건축물',
    'map.stat.tilesTravelled': '이동한 타일',
    'map.stat.zombiesKilled': '죽인 좀비',
    'map.tile': '타일',
    'map.view': '현재',
    'map.waitingForWorld': '월드를 기다리는 중…',
    'map.zoomIn': '확대',
    'map.zoomOut': '축소',
    'menu.desktopOnly':
      '싱글플레이는 로컬 서버를 띄우므로 데스크톱 빌드가 필요합니다. 브라우저에서는 직접 서버를 실행한 뒤 아래에서 접속하세요:',
    'menu.join': '접속',
    'menu.reset': '월드 초기화',
    'menu.resetArmed': '월드와 그 안의 모든 캐릭터가 삭제됩니다. 한 번 더 누르면 실행됩니다.',
    'menu.resetBusy': '초기화하는 중…',
    'menu.resetDone': '월드를 초기화했습니다. 접속하면 새로 시작합니다.',
    'menu.resetFailed': '서버가 월드를 초기화하지 못했습니다.',
    'menu.resetNotLocal': '서버를 실행 중인 컴퓨터에서만 초기화할 수 있습니다.',
    'menu.resetUnreachable': '서버에 연결할 수 없습니다.',
    'menu.resetUnsupported': '이 서버는 초기화를 허용하지 않습니다.',
    'menu.joinServer': '서버 접속',
    'menu.needAddress': '서버 주소를 입력하세요.',
    'menu.passwordPlaceholder': '비밀번호 (선택)',
    'menu.play': '시작',
    'menu.playerName': '플레이어 이름',
    'menu.serverAddress': '서버 주소',
    'menu.serverPassword': '서버 비밀번호',
    'menu.singlePlayer': '싱글플레이',
    'menu.tagline': '주워 모으고, 짓고, 밤을 넘겨라.',
    'menu.title': 'Survive',
    'menu.versions': '프로토콜 v{protocol} · 콘텐츠 {content}',
    'menu.worldName': '월드 이름',
    'panel.body': '신체',
    'panel.build': '건축',
    'panel.chat': '채팅',
    'panel.container': '보관함',
    'panel.crafting': '제작',
    'panel.death': '사망',
    'panel.debug': '디버그',
    'panel.inventory': '인벤토리',
    'panel.map': '지도',
    'panel.paused': '일시정지',
    'panel.skills': '스킬',
    'prompt.closeDoor': '{name} 닫기',
    'prompt.harvest': '{name} 채집',
    'prompt.openDoor': '{name} 열기',
    'prompt.pickUp': '{name} 줍기',
    'prompt.search': '{name} 뒤지기',
    'prompt.sleep': '{name}에서 자기',
    'prompt.tend': '{name} 손보기',
    'prompt.useStation': '{name} 사용',
    'session.chatChannel': '채팅 채널',
    'session.chatInput': '채팅 입력',
    'session.chatLog': '채팅 기록',
    'session.chatPending': '보냄 — 서버가 아직 확인하지 않음',
    'session.chatPlaceholder': '무슨 말이든…',
    'session.controls': '조작',
    'session.ctl.attack': '공격',
    'session.ctl.block': '방어',
    'session.ctl.build': '건축 메뉴',
    'session.ctl.crouch': '웅크리기',
    'session.ctl.cycleHotbar': '핫바 순환',
    'session.ctl.debug': '디버그 오버레이',
    'session.ctl.down': '아래로',
    'session.ctl.drop': '든 것 버리기',
    'session.ctl.interact': '사용 / 상호작용',
    'session.ctl.left': '왼쪽으로',
    'session.ctl.pause': '일시정지 / 창 닫기',
    'session.ctl.reload': '재장전',
    'session.ctl.right': '오른쪽으로',
    'session.ctl.rotate': '배치 회전',
    'session.ctl.selectHotbar': '핫바 칸 선택',
    'session.ctl.sleep': '취침',
    'session.ctl.sprint': '질주',
    'session.ctl.up': '위로',
    'session.death.beaten': '구타로 사망',
    'session.death.blast': '폭발에 휘말림',
    'session.death.bleeding': '과다출혈',
    'session.death.burned': '산 채로 불탐',
    'session.death.cold': '동사',
    'session.death.exhaustion': '탈진으로 쓰러짐',
    'session.death.fall': '낙하로 사망',
    'session.death.heat': '열사병으로 사망',
    'session.death.infection': '감염에 잠식됨',
    'session.death.pierce': '관통상',
    'session.death.poison': '독사',
    'session.death.shot': '총상으로 사망',
    'session.death.slash': '베여 사망',
    'session.death.starved': '굶어 사망',
    'session.death.suffocation': '질식',
    'session.death.thirst': '갈증으로 사망',
    'session.death.unknown': '원인 불명',
    'session.death.zombie': '죽은 것들에게 찢김',
    'session.disconnect': '접속 종료',
    'session.key.altLeft': '왼 Alt',
    'session.key.altRight': '오른 Alt',
    'session.key.ctrlLeft': '왼 Ctrl',
    'session.key.ctrlRight': '오른 Ctrl',
    'session.key.escape': 'Esc',
    'session.key.mouseLeft': '마우스 왼쪽',
    'session.key.mouseRight': '마우스 오른쪽',
    'session.key.shiftLeft': '왼 Shift',
    'session.key.shiftRight': '오른 Shift',
    'session.key.space': '스페이스',
    'session.key.wheel': '마우스 휠',
    'session.paused': '시뮬레이션이 멈췄습니다.',
    'session.readyToRespawn': '부활 준비 완료',
    'session.respawn': '부활',
    'session.respawnAtBed': '침대에서 부활',
    'session.resume': '계속하기',
    'session.send': '보내기',
    'session.stat.animalsKilled': '잡은 동물',
    'session.stat.cropsHarvested': '수확한 작물',
    'session.stat.daysSurvived': '생존 일수',
    'session.stat.deaths': '사망 횟수',
    'session.stat.distanceWalked': '이동 거리',
    'session.stat.itemsCrafted': '제작한 아이템',
    'session.stat.playersKilled': '죽인 플레이어',
    'session.stat.resourcesGathered': '채집한 자원',
    'session.stat.structuresBuilt': '지은 건축물',
    'session.stat.zombiesKilled': '죽인 좀비',
    'session.thisLife': '이번 생',
    'session.waitingForPause': '서버의 일시정지를 기다리는 중…',
    'skill.athletics': '체력',
    'skill.building': '건축',
    'skill.cooking': '요리',
    'skill.crafting': '제작',
    'skill.farming': '농사',
    'skill.foraging': '채집',
    'skill.medicine': '의술',
    'skill.melee': '근접',
    'skill.mining': '채광',
    'skill.ranged': '원거리',
    'skill.stealth': '은신',
    'skill.woodcutting': '벌목',
    'tip.byHand': '맨손으로 채집',
    'tip.condition': '상태 {percent}%',
    'tip.crawling': '기어 다님',
    'tip.damage': '{type} 피해 {amount}',
    'tip.depleted': '고갈됨',
    'tip.food': '허기 +{amount}',
    'tip.freshness': '신선도 {percent}%',
    'tip.illnessRisk': '질병 위험: {percent}%',
    'tip.magazine': '탄창 {rounds}',
    'tip.medical': '의료: {kind}',
    'tip.needsTool': '{tools} 필요 ({tier}등급)',
    'tip.needsToolMissing': '{tools} 필요 ({tier}등급) — 가진 것이 없습니다',
    'tip.protects': '보호: {parts}',
    'tip.protectsNothing': '없음',
    'tip.reach': '사거리 {range}, 휘두르기 {seconds}초',
    'tip.roleBed': '침대',
    'tip.roleDoorClosed': '문 (닫힘)',
    'tip.roleDoorOpen': '문 (열림)',
    'tip.rolePlot': '밭',
    'tip.roleStation': '{kind} 작업대',
    'tip.roleStorage': '보관',
    'tip.tool': '도구: {kinds} ({tier}등급)',
    'tip.trains': '{skill} 숙련',
    'tip.twoHanded': '양손',
    'tip.underConstruction': '건설 중 {percent}%',
    'tip.warmth': '보온 +{amount}',
    'tip.water': '수분 +{amount}',
    'tip.weight': '무게 {kg} kg',
    'tip.yields': '산출 {list}',
    'cb.slotsUsed': '{used}/{total} 칸',
    'inv.bag': '가방',
    'inv.dragHint': '끌어서 옮기기 · Shift+끌기로 절반 · 밖으로 끌어 버리기 · 우클릭으로 더 보기',
    'inv.load': '적재',
    'inv.slotsUsed': '{used} / {total} 칸',
    'build.blocked.skill': '{skill} {level} 필요',
    'build.blocked.tool': '{tool} 필요',
    'build.cost': '비용: {cost}',
    'build.costEntry': '{item} {count}개',
    'build.free': '무료',
    'build.hintGhost': '서버가 거부할 자리에서는 미리보기가 붉어집니다.',
    'build.hintPlace': '월드에서 좌클릭으로 배치 · <b>T</b> 회전 · <b>B</b> 닫기',
    'build.needsSupport': '지지대 필요',
    'build.readyCount': '{total}개 중 {ready}개 건축 가능',
    'build.requiresSkill': '{skill} 레벨 {level} 필요',
    'build.rowFacts': '{hp} HP · 건축 {seconds} · {width}x{height} 타일',
    'build.skill': '스킬: {skill} {have}/{need}',
    'build.skillProgress': '{skill} {have}/{need}',
    'build.tool': '도구: {tool}',
    'build.toolMissing': '{tool}을(를) 갖고 있지 않습니다',
    'build.toolUsing': '{tool} 사용',
    'cb.carried': '{carried}/{capacity} kg',
    'cb.healthy': '정상',
    'cb.slotAria': '{label} {index}번 칸: {item}',
    'cb.tempNormal': '정상',
    'cb.treatmentFor': '처치 — {part}',
    'build.waitingWorld': '월드를 기다리는 중…',
    'session.ctl.interactKey': '상호작용',
    'craft.all': '전체',
    'craft.allStations': '모든 작업대',
    'craft.anyTag': '{tag} 아무거나',
    'craft.atStation': '{station}에서',
    'craft.availableHere': '여기서 가능',
    'craft.blocked.skill': '{skill} 레벨 {level} 필요',
    'craft.blocked.station': '가까이 {station} 필요',
    'craft.blocked.tools': '{tools} 필요',
    'craft.byHand': '맨손',
    'craft.byHandLower': '맨손',
    'craft.byHandNote': '맨손으로 제작 가능',
    'craft.cancel': '취소',
    'craft.cat.ammo': '탄약',
    'craft.cat.armor': '방어구',
    'craft.cat.basic': '기본',
    'craft.cat.building': '건축',
    'craft.cat.cooking': '요리',
    'craft.cat.farming': '농사',
    'craft.cat.medical': '의료',
    'craft.cat.smelting': '제련',
    'craft.cat.textiles': '직물',
    'craft.cat.tools': '도구',
    'craft.cat.weapons': '무기',
    'craft.categories': '레시피 분류',
    'craft.filterByStation': '작업대로 걸러내기',
    'craft.haveSchematic': '도해를 갖고 있습니다',
    'craft.inProgress': '진행 중',
    'craft.inReach': '가까이:',
    'craft.needSchematic': '도해를 찾아야 배울 수 있습니다',
    'craft.needsHeat': '열이 필요',
    'craft.noMatch': '조건에 맞는 레시피가 없습니다.',
    'craft.noStation': '가까이 작업대가 없습니다 — 맨손 레시피만.',
    'craft.nothingCrafting': '제작 중인 것이 없습니다.',
    'craft.quantity': '수량',
    'craft.reason.dead': '죽은 상태입니다',
    'craft.reason.lowFuel': '연료가 부족합니다',
    'craft.reason.noMaterials': '재료가 부족합니다',
    'craft.reason.notLearned': '아직 배우지 않은 레시피입니다',
    'craft.reason.notLit': '작업대에 불이 붙지 않았습니다',
    'craft.reason.packFull': '가방이 가득 찼을 수 있습니다',
    'craft.reason.queueFull': '제작 대기열이 가득 찼습니다',
    'craft.recipes': '레시피',
    'craft.searchLabel': '레시피 검색',
    'craft.searchPlaceholder': '레시피나 산출물 검색',
    'craft.selectPrompt': '만들 레시피를 고르세요.',
    'craft.skillProgress': '{skill} {have}/{need}',
    'craft.toolMissing': '{tool}이(가) 없습니다',
    'craft.toolUsing': '{tool} 사용 중',
    'craft.waitingForWorld': '월드를 기다리는 중…',
    'build.buildableCount': '{total}개 중 {ready}개 건축 가능',
    'craft.schematicChip': '도해',
    'damage.bleed': '출혈',
    'damage.blunt': '타격',
    'damage.bullet': '총상',
    'damage.cold': '추위',
    'damage.dehydration': '탈수',
    'damage.exhaustion': '탈진',
    'damage.explosive': '폭발',
    'damage.fall': '낙하',
    'damage.fire': '화염',
    'damage.heat': '더위',
    'damage.infection': '감염',
    'damage.pierce': '관통',
    'damage.poison': '독',
    'damage.slash': '참격',
    'damage.starvation': '굶주림',
    'damage.zombieBite': '좀비 물림',
    'station.anvil': '모루',
    'station.campfire': '모닥불',
    'station.chemistry': '화학',
    'station.component': '부품',
    'station.cookingPot': '요리 냄비',
    'station.furnace': '용광로',
    'station.grindstone': '연마석',
    'station.loom': '직조기',
    'station.resource': '자원',
    'station.workbench': '작업대',
    'tool.axe': '도끼',
    'tool.fishingRod': '낚싯대',
    'tool.hammer': '망치',
    'tool.hoe': '괭이',
    'tool.knife': '칼',
    'tool.lighter': '라이터',
    'tool.pickaxe': '곡괭이',
    'tool.saw': '톱',
    'tool.shovel': '삽',
    'tool.sickle': '낫',
    'tool.wateringCan': '물뿌리개',
    'tool.workbench': '작업대',
    'tool.wrench': '렌치',
    'medical.bandage': '붕대',
    'medical.disinfect': '소독',
    'medical.injection': '주사',
    'medical.pill': '약',
    'medical.splint': '부목',
    'medical.suture': '봉합',
    'toast.crafted': '{item}을(를) 만들었습니다.',
    'toast.levelUp': '{skill} 레벨 {level}',
    'toast.pickedUp': '+{count} {item}',
    'vital.blood': '혈액',
    'vital.food': '허기',
    'vital.hp': '체력',
    'vital.rest': '피로',
    'vital.stamina': '기력',
    'vital.water': '수분',
  },
};
